import React, { useEffect, useMemo, useState } from "react"
import { useNavigate } from "react-router-dom"
import { BarChart3, BookOpen, Boxes, Clapperboard, FileText, FlaskConical, Image, Lightbulb, Megaphone, Mic2, PackageCheck, Search, SearchCheck, Sparkles } from "lucide-react"
import { SubToolbox } from "../Toolbox"
import { SubToolboxGrid, SubToolboxSection, SubToolboxStack } from "../subtoolbox/SubToolboxLayouts"
import { SubToolboxBadge, SubToolboxButton, SubToolboxInput, SubToolboxSelect, SubToolboxStatePanel, SubToolboxSurface, SubToolboxTextArea, SubToolboxToggle } from "../subtoolbox/SubToolboxPrimitives"
import { useBrain } from "../../context/useBrain"
import type { Project } from "../../types"
import { syncProjectToContentBuild } from "../../services/asset-engine/ProjectContentBuildBridge"

type SectionState={count:number;status:string;route:string;detail:string}
type SectionDescriptor={id:string;title:string;subtitle:string;icon:React.ElementType;derive:(project:Project,brain:any)=>SectionState}
type PublishingPackage=Record<string,any>

const hasText=(value:unknown)=>typeof value==="string"&&value.trim().length>0
const truthyCount=(values:unknown[])=>values.filter(value=>Array.isArray(value)?value.length>0:hasText(value)||Boolean(value)).length
const statusFor=(count:number,readyAt=1)=>count>=readyAt?"READY":count>0?"IN PROGRESS":"EMPTY"
const publishing=(p:Project):PublishingPackage=>p.plan?.publishingPackage||{}

const SECTIONS:SectionDescriptor[]=[
 {id:"concept",title:"Concept & Brief",subtitle:"Promise, angle, audience and production objective",icon:Lightbulb,derive:p=>{const count=truthyCount([p.concept,p.plan?.concept,p.niche,p.plan?.niche,p.plan?.audience,p.plan?.hook]);return{count,status:statusFor(count,3),route:"/projects",detail:"Project concept, niche, audience, hook and planning brief."}}},
 {id:"research",title:"Research & Evidence",subtitle:"Sources, claims, notes and evidence connections",icon:Search,derive:(p,b)=>{const count=(p.plan?.references?.length||0)+(b.researchLabState?.results?.length||0);return{count,status:statusFor(count),route:"/research-lab",detail:"Research Lab results and project-linked evidence."}}},
 {id:"script",title:"Script",subtitle:"Hook, sections, narration and revisions",icon:FileText,derive:p=>{const count=hasText(p.script)?1:0;return{count,status:statusFor(count),route:"/script-architect",detail:count?"Project script is attached.":"No project script is attached yet."}}},
 {id:"storyboard",title:"Storyboard & Visual Plan",subtitle:"Scenes, shot direction and visual structure",icon:Clapperboard,derive:p=>{const count=p.storyboard?.length||0;return{count,status:statusFor(count),route:"/storyboard-studio",detail:count?`${count} storyboard scenes attached.`:"No storyboard scenes are attached yet."}}},
 {id:"media",title:"Media Assets",subtitle:"Images, video, graphics and generated media",icon:Image,derive:p=>{const count=(p.storyboard||[]).filter(s=>hasText(s.imageUrl)).length+(hasText(p.thumbnailUrl)?1:0);return{count,status:statusFor(count),route:"/vault",detail:"Canonical media remains Vault-owned and project-linked."}}},
 {id:"audio",title:"Audio",subtitle:"Voice, music, sound effects and mix assets",icon:Mic2,derive:p=>{const count=(p.storyboard||[]).filter(s=>hasText(s.voiceoverUrl)).length;return{count,status:statusFor(count),route:"/vault",detail:"Voiceover and audio assets remain Vault-owned."}}},
 {id:"packaging",title:"Creative Packaging",subtitle:"Title and thumbnail concepts, variants and final selections",icon:Boxes,derive:(p,b)=>{const count=truthyCount([p.videoTitle,p.thumbnailUrl,b.seoState?.winningTitle,b.thumbnailState?.activeImageUrl]);return{count,status:statusFor(count,2),route:"/thumbnail-studio",detail:"Creative packaging owns title/thumbnail development; publishing owns final YouTube metadata."}}},
 {id:"edit",title:"Edit & Timeline",subtitle:"Editor handoff, sequence state and render package",icon:Sparkles,derive:p=>{const count=(p.storyboard?.length||0)>0||hasText(p.script)?1:0;return{count,status:count?"READY FOR HANDOFF":"EMPTY",route:"/editor",detail:"Open the editor with this project as production context."}}},
 {id:"publishing",title:"Publishing Package",subtitle:"Canonical YouTube metadata, routing, audience and schedule",icon:PackageCheck,derive:p=>{const x=publishing(p);const count=truthyCount([p.videoTitle,p.thumbnailUrl,p.description,p.tags,x.category,x.chapters,x.educationQuestions,x.endScreenFrame,x.endScreenLinks,x.relatedVideo,x.publishAt||p.publishDate,x.playlists,x.pinnedComment,x.communityPosts,x.audience,x.visibility,x.language,x.captions,x.cards]);return{count,status:statusFor(count,12),route:"/video-publisher",detail:"Editable canonical YouTube publishing package."}}},
 {id:"seo",title:"SEO & Entity Intelligence",subtitle:"Topics, search concepts, entities and audience vocabulary",icon:SearchCheck,derive:p=>{const x=p.plan?.seoEntityIntelligence||{};const count=truthyCount([x.primaryTopic,x.searchConcepts,x.entities,x.audienceVocabulary,x.strategy]);return{count,status:statusFor(count,3),route:"/seo-generator",detail:"Evidence-backed discovery intelligence feeding the Publishing Package."}}},
 {id:"readiness",title:"Publish Readiness",subtitle:"Requirements, warnings, blockers and completion state",icon:PackageCheck,derive:p=>{const x=publishing(p);const required=[p.videoTitle,p.thumbnailUrl,p.description,p.tags,x.category,x.audience,x.visibility,x.publishAt||p.publishDate];const count=truthyCount(required);return{count,status:count===required.length?"READY":count?"IN PROGRESS":"EMPTY",route:"/video-publisher",detail:`${count}/${required.length} core publishing requirements complete.`}}},
 {id:"launch",title:"Launch & Priming",subtitle:"Community, Shorts teaser and launch actions",icon:Megaphone,derive:p=>{const x=p.plan?.launchPriming||{};const count=truthyCount([x.prePublishPost,x.launchPost,x.shortsTeaser,x.pinnedCommentStrategy,x.earlyActions,x.sustainActions]);return{count,status:statusFor(count,2),route:"/pre-launch-priming",detail:"Pre-launch, launch and sustain assets tied to this video package."}}},
 {id:"experiments",title:"Experiments & Variants",subtitle:"Packaging, timing and launch hypotheses",icon:FlaskConical,derive:p=>{const x=p.plan?.experiments||[];const count=Array.isArray(x)?x.length:0;return{count,status:count?"READY":"EMPTY",route:"/tactics-engine",detail:"Experiment definitions reference canonical package variants."}}},
 {id:"evaluation",title:"Post-Publish Evaluation",subtitle:"Measurement contract and outcome checkpoints",icon:BarChart3,derive:p=>{const x=p.plan?.evaluationContract||{};const count=truthyCount([x.metrics,x.checkpoints,x.target,x.hypothesis]);return{count,status:statusFor(count,2),route:"/analytics",detail:"Defines what to measure after publication and links results back to used assets."}}},
 {id:"learning",title:"Performance & Learning",subtitle:"Post-publish evidence, findings and reusable lessons",icon:BookOpen,derive:(p,b)=>{const count=b.channelyticsState?.topPerformers?.length||0;return{count,status:count?"CONNECTED":"WAITING",route:"/analytics",detail:"Analytics evidence feeds governed learning back into this build."}}},
]

const ContentAssetEngine:React.FC=()=>{
 const {brain,updateProject}=useBrain()
 const navigate=useNavigate()
 const projects=Array.isArray(brain.projects)?brain.projects:[]
 const [buildId,setBuildId]=useState<string>(brain.activeProjectId||projects[0]?.id||"")
 useEffect(()=>{if(buildId&&projects.some(p=>p.id===buildId))return;setBuildId(brain.activeProjectId||projects[0]?.id||"")},[brain.activeProjectId,buildId,projects])
 const build=useMemo(()=>projects.find(p=>p.id===buildId)||null,[buildId,projects])
 useEffect(()=>{
  if(!build)return
  const canonical=syncProjectToContentBuild(build,{sourceToolId:"project-command-kanban"})
  if(build.contentBuildId!==canonical.id){
   updateProject(build.id,{contentBuildId:canonical.id})
  }
 },[build,updateProject])
 const sections=useMemo(()=>build?SECTIONS.map(s=>({...s,state:s.derive(build,brain)})):[],[brain,build])
 const ready=sections.filter(s=>["READY","CONNECTED","READY FOR HANDOFF"].includes(s.state.status)).length
 const progress=sections.length?Math.round((ready/sections.length)*100):0
 if(!build)return <SubToolboxStatePanel state="empty" message="NO CONTENT BUILDS YET — CREATE A PROJECT TO START THE ASSET ENGINE." action={<SubToolboxButton onClick={()=>navigate("/projects")}>OPEN PROJECT STUDIO</SubToolboxButton>}/>
 const pkg=publishing(build)
 const patchPackage=(field:string,value:any)=>updateProject(build.id,{plan:{...(build.plan||{concept:"",niche:""}),publishingPackage:{...pkg,[field]:value}}})
 const patchRoot=(field:keyof Project,value:any)=>updateProject(build.id,{[field]:value})
 const field=(label:string,key:string,placeholder="")=><SubToolboxSection label={label}><SubToolboxInput value={pkg[key]||""} placeholder={placeholder} onChange={e=>patchPackage(key,e.target.value)}/></SubToolboxSection>
 const area=(label:string,key:string,placeholder="")=><SubToolboxSection label={label}><SubToolboxTextArea height="compact" value={pkg[key]||""} placeholder={placeholder} onChange={e=>patchPackage(key,e.target.value)}/></SubToolboxSection>
 const publishingUI=<SubToolboxStack density="dense">
  <div className="flex flex-wrap gap-2"><SubToolboxBadge>{sections.find(s=>s.id==="publishing")?.state.status}</SubToolboxBadge><SubToolboxBadge>{sections.find(s=>s.id==="publishing")?.state.count} FIELDS</SubToolboxBadge></div>
  <SubToolboxSurface tone="subtle"><SubToolboxSection label="PACKAGING"><SubToolboxGrid minItemWidth="compact"><SubToolboxSection label="TITLE"><SubToolboxInput value={build.videoTitle||""} onChange={e=>patchRoot("videoTitle",e.target.value)}/></SubToolboxSection><SubToolboxSection label="THUMBNAIL URL"><SubToolboxInput value={build.thumbnailUrl||""} onChange={e=>patchRoot("thumbnailUrl",e.target.value)}/></SubToolboxSection></SubToolboxGrid></SubToolboxSection></SubToolboxSurface>
  <SubToolboxSurface><SubToolboxSection label="METADATA"><SubToolboxGrid minItemWidth="compact"><SubToolboxSection label="DESCRIPTION"><SubToolboxTextArea height="compact" value={build.description||""} onChange={e=>patchRoot("description",e.target.value)}/></SubToolboxSection><SubToolboxSection label="TAGS"><SubToolboxTextArea height="compact" value={build.tags||""} onChange={e=>patchRoot("tags",e.target.value)}/></SubToolboxSection><SubToolboxSection label="CATEGORY"><SubToolboxSelect value={pkg.category||""} onChange={e=>patchPackage("category",e.target.value)}><option value="">SELECT CATEGORY</option><option>Education</option><option>People & Blogs</option><option>Entertainment</option><option>Film & Animation</option><option>Howto & Style</option><option>Science & Technology</option></SubToolboxSelect></SubToolboxSection>{field("LANGUAGE","language","Video language")}{area("CHAPTERS / TIMESTAMPS","chapters","00:00 Introduction")}{area("EDUCATION QUESTIONS","educationQuestions","00:00 Question")}{field("CAPTIONS / SUBTITLE ASSET","captions","Caption asset or status")}</SubToolboxGrid></SubToolboxSection></SubToolboxSurface>
  <SubToolboxSurface tone="subtle"><SubToolboxSection label="DISCOVERY + ROUTING"><SubToolboxGrid minItemWidth="compact">{field("END SCREEN FRAME","endScreenFrame")}{field("END SCREEN LINKS","endScreenLinks")}{field("RELATED VIDEO","relatedVideo")}{field("PLAYLISTS","playlists")}{area("CARDS / IN-VIDEO ROUTING","cards","Timestamp → destination")}</SubToolboxGrid></SubToolboxSection></SubToolboxSurface>
  <SubToolboxSurface><SubToolboxSection label="PUBLISHING"><SubToolboxGrid minItemWidth="compact"><SubToolboxSection label="PUBLISH DATE / TIME"><SubToolboxInput type="datetime-local" value={pkg.publishAt||build.publishDate||""} onChange={e=>{patchPackage("publishAt",e.target.value);patchRoot("publishDate",e.target.value)}}/></SubToolboxSection>{field("TIMEZONE","timezone","America/New_York")}<SubToolboxSection label="VISIBILITY"><SubToolboxSelect value={pkg.visibility||""} onChange={e=>patchPackage("visibility",e.target.value)}><option value="">SELECT</option><option>Private</option><option>Unlisted</option><option>Public</option><option>Scheduled</option></SubToolboxSelect></SubToolboxSection><SubToolboxSection label="AUDIENCE"><SubToolboxSelect value={pkg.audience||""} onChange={e=>patchPackage("audience",e.target.value)}><option value="">SELECT</option><option value="not-made-for-kids">Not made for kids</option><option value="made-for-kids">Made for kids</option></SubToolboxSelect></SubToolboxSection><SubToolboxSection label="PREMIERE"><SubToolboxToggle pressed={Boolean(pkg.premiere)} label={pkg.premiere?"ENABLED":"DISABLED"} onClick={()=>patchPackage("premiere",!pkg.premiere)}/></SubToolboxSection></SubToolboxGrid></SubToolboxSection></SubToolboxSurface>
  <SubToolboxSurface tone="subtle"><SubToolboxSection label="AUDIENCE ACTIVATION"><SubToolboxGrid minItemWidth="compact">{area("PINNED COMMENT","pinnedComment")}{area("RELATED COMMUNITY POSTS","communityPosts")}</SubToolboxGrid></SubToolboxSection></SubToolboxSurface>
  <SubToolboxGrid minItemWidth="compact"><SubToolboxButton size="compact" onClick={()=>navigate("/video-publisher")}>OPEN PUBLISHER</SubToolboxButton><SubToolboxButton size="compact" tone="neutral" onClick={()=>navigate("/vault")}>OPEN VAULT</SubToolboxButton></SubToolboxGrid>
 </SubToolboxStack>
 return <SubToolboxStack density="comfortable">
  <SubToolboxSurface tone="subtle"><SubToolboxGrid minItemWidth="wide"><SubToolboxSection label="ACTIVE CONTENT BUILD"><SubToolboxSelect value={buildId} onChange={e=>setBuildId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.videoTitle||p.name}</option>)}</SubToolboxSelect></SubToolboxSection><SubToolboxSection label="PIPELINE READINESS"><div className="flex min-h-12 items-center gap-3"><SubToolboxBadge>{build.status||"PROJECT"}</SubToolboxBadge><strong className="text-sm font-black uppercase">{progress}% READY</strong><div className="h-3 min-w-20 flex-1 border-2 border-black bg-white"><div className="h-full bg-black" style={{width:`${progress}%`}}/></div></div></SubToolboxSection></SubToolboxGrid></SubToolboxSurface>
  <SubToolboxGrid minItemWidth="wide">{sections.map((section,index)=>{const Icon=section.icon;return <SubToolbox key={section.id} title={section.title} subtitle={section.subtitle} icon={<Icon/>} paletteIndex={index+2} isOpenInitial={section.id==="publishing"} openUnits={section.id==="publishing"?6:2}>{section.id==="publishing"?publishingUI:<SubToolboxStack density="dense"><div className="flex flex-wrap gap-2"><SubToolboxBadge>{section.state.status}</SubToolboxBadge><SubToolboxBadge>{section.state.count} ITEMS</SubToolboxBadge></div>{section.state.count===0?<SubToolboxStatePanel state={section.state.status==="WAITING"?"stale":"empty"} message={section.state.detail}/>:<SubToolboxSurface tone="subtle"><p className="text-[10px] font-black uppercase opacity-70">{section.state.detail}</p></SubToolboxSurface>}<SubToolboxGrid minItemWidth="compact"><SubToolboxButton size="compact" onClick={()=>navigate(section.state.route)}>OPEN TOOL</SubToolboxButton><SubToolboxButton size="compact" tone="neutral" onClick={()=>navigate("/vault")}>OPEN VAULT</SubToolboxButton></SubToolboxGrid></SubToolboxStack>}</SubToolbox>})}</SubToolboxGrid>
 </SubToolboxStack>
}
export default ContentAssetEngine
