import type { CanonicalIntelligenceEvidenceBundle } from "../analytics-canon"
import type { StatisticsIntelligenceSnapshot } from "./StatisticsIntelligence"
export type AudienceEvidenceConfidence = "high" | "medium" | "low" | "insufficient"
export interface AudienceEvidenceSignal { id:string; kind:"behavior"|"new_returning"|"subscriber_status"|"demographic"|"geography"|"format"|"search_language"; datasetId:string; label:string; metrics:Record<string,number>; evidenceRef:string|null; confidence:AudienceEvidenceConfidence }
export interface AudienceIntelligenceSnapshot { version:"vt-audience-intelligence-v1"; generatedAt:string; sourceSnapshotId:string; channelId:string|null; selectedWindow:CanonicalIntelligenceEvidenceBundle["selectedWindow"]; confidence:AudienceEvidenceConfidence; signals:AudienceEvidenceSignal[]; evidenceBoundary:string[]; missingEvidence:string[] }
const AUDIENCE_DATASETS:Record<string,AudienceEvidenceSignal["kind"]>={audience:"behavior",new_returning:"new_returning",subs:"subscriber_status",demographics:"demographic",geography:"geography",cities:"geography",provinces:"geography",formats_subscribers:"format",traffic_detail_search_terms:"search_language"}
const numericMetrics=(row:Record<string,unknown>):Record<string,number>=>Object.fromEntries(Object.entries(row).filter(([,v])=>typeof v==="number"&&Number.isFinite(v))) as Record<string,number>
const identityLabel=(row:Record<string,unknown>):string=>{const keys=["term","status","ageGroup","gender","countryName","country","city","province","creatorContentType","format"];const values=keys.map(k=>row[k]).filter((v):v is string=>typeof v==="string"&&Boolean(v.trim()));return values.length?values.join(" / "):"Observed audience segment"}
const confidenceFor=(s:StatisticsIntelligenceSnapshot,n:number):AudienceEvidenceConfidence=>!n||s.confidence==="insufficient"?"insufficient":s.confidence==="high"&&n>=4?"high":s.confidence==="high"||s.confidence==="medium"?"medium":"low"
/** Evidence-only aggregate audience intelligence. Never invent personas or sensitive individual traits. */
export const buildAudienceIntelligence=(evidence:CanonicalIntelligenceEvidenceBundle,statistics:StatisticsIntelligenceSnapshot):AudienceIntelligenceSnapshot=>{
 const signals:AudienceEvidenceSignal[]=[]
 evidence.datasets.forEach(dataset=>{const kind=AUDIENCE_DATASETS[dataset.id];if(!kind||!["available","partial","stale"].includes(dataset.status))return;dataset.sampleRows.slice(0,5).forEach((row,index)=>{const metrics=numericMetrics(row);if(!Object.keys(metrics).length)return;signals.push({id:evidence.snapshotId+":"+dataset.id+":audience:"+(index+1),kind,datasetId:dataset.id,label:identityLabel(row),metrics,evidenceRef:dataset.evidenceRefs[index]||null,confidence:dataset.status==="available"&&statistics.confidence==="high"?"high":dataset.status==="stale"?"low":"medium"})})})
 const required=["audience","new_returning","subs","demographics","geography","formats_subscribers"];const available=new Set(evidence.datasets.filter(d=>["available","partial","stale"].includes(d.status)).map(d=>d.id))
 return {version:"vt-audience-intelligence-v1",generatedAt:new Date().toISOString(),sourceSnapshotId:evidence.snapshotId,channelId:evidence.channelId,selectedWindow:evidence.selectedWindow,confidence:confidenceFor(statistics,signals.length),signals,evidenceBoundary:["Signals describe aggregate channel audience evidence, not individual viewers.","Do not infer sensitive traits or motivations not directly represented in canonical evidence.","Search terms and comments can support vocabulary observations but do not prove demographics or private attributes.","Missing, stale, or partial datasets remain explicit rather than being treated as zero."],missingEvidence:required.filter(id=>!available.has(id))}
}
