import type {
 CsvCapabilitySource,
 CsvDetectedCategory,
 CsvFreshnessClass,
 CsvMajorFamily,
 CsvMergeKeyStrategy,
 CsvMergeTargetDataset,
 CsvSubtableId,
 CsvTag,
 CsvUploadType,
} from "../types"

export type CsvFamilyDefinition = {
 category: CsvDetectedCategory
 label: string
 shortLabel: string
 majorFamily: CsvMajorFamily
 mergeTargetDataset: CsvMergeTargetDataset
 mergeKeyStrategy: CsvMergeKeyStrategy
 uploadHint: CsvUploadType
 defaultTag: CsvTag
 subtableId: CsvSubtableId
 capabilitySources: CsvCapabilitySource[]
 freshnessClass: CsvFreshnessClass
}

export const CSV_MAJOR_FAMILY_STYLES: Record<
 CsvMajorFamily,
 { label: string; menuClass: string; pillClass: string }
> = {
 unknown: {
  label: "Unknown",
  menuClass: "bg-white text-black",
  pillClass: "bg-[#F4F1EB] text-black",
 },
 video_data: {
  label: "Video Data",
  menuClass: "bg-[#FF83EA] text-black",
  pillClass: "bg-[#FF83EA] text-black",
 },
 daily_metrics: {
  label: "Daily Metrics",
  menuClass: "bg-[#FFFF61] text-black",
  pillClass: "bg-[#FFFF61] text-black",
 },
 search_intelligence: {
  label: "Search Intelligence",
  menuClass: "bg-[#FF83EA] text-black",
  pillClass: "bg-[#FF83EA] text-black",
 },
 traffic: {
  label: "Traffic",
  menuClass: "bg-[#4FFF5B] text-black",
  pillClass: "bg-[#4FFF5B] text-black",
 },
 geography: {
  label: "Geography",
  menuClass: "bg-[#579AFF] text-white",
  pillClass: "bg-[#579AFF] text-white",
 },
 audience: {
  label: "Audience",
  menuClass: "bg-[#FFB570] text-black",
  pillClass: "bg-[#FFB570] text-black",
 },
 surfaces_discovery: {
  label: "Surfaces & Discovery",
  menuClass: "bg-[#40C6E9] text-black",
  pillClass: "bg-[#40C6E9] text-black",
 },
 revenue_monetization: {
  label: "Revenue & Monetization",
  menuClass: "bg-[#B14AED] text-white",
  pillClass: "bg-[#B14AED] text-white",
 },
}

export const CSV_UPLOAD_TYPE_OPTIONS: Array<{
 value: CsvUploadType
 label: string
 menuClass: string
}> = [
 { value: "auto", label: "Auto Detect", menuClass: "bg-[#24D3FF] text-black" },
 { value: "video_data", label: "Video Data", menuClass: CSV_MAJOR_FAMILY_STYLES.video_data.menuClass },
 { value: "daily_metrics", label: "Daily Metrics", menuClass: CSV_MAJOR_FAMILY_STYLES.daily_metrics.menuClass },
 { value: "traffic", label: "Traffic", menuClass: CSV_MAJOR_FAMILY_STYLES.traffic.menuClass },
 { value: "geography", label: "Geography", menuClass: CSV_MAJOR_FAMILY_STYLES.geography.menuClass },
 { value: "audience", label: "Audience", menuClass: CSV_MAJOR_FAMILY_STYLES.audience.menuClass },
 { value: "surfaces_discovery", label: "Surfaces & Discovery", menuClass: CSV_MAJOR_FAMILY_STYLES.surfaces_discovery.menuClass },
 {
  value: "revenue_monetization",
  label: "Revenue & Monetization",
  menuClass: CSV_MAJOR_FAMILY_STYLES.revenue_monetization.menuClass,
 },
]

export const CSV_FAMILY_DEFINITIONS: Record<CsvDetectedCategory, CsvFamilyDefinition> = {
 unknown: {
  category: "unknown",
  label: "Unknown Upload",
  shortLabel: "Unknown",
  majorFamily: "unknown",
  mergeTargetDataset: "ignore",
  mergeKeyStrategy: "none",
  uploadHint: "auto",
  defaultTag: "unknown",
  subtableId: "unknown",
  capabilitySources: ["csv_only"],
  freshnessClass: "manual_only",
 },
 video_statistics: {
  category: "video_statistics", label: "Video Statistics", shortLabel: "Video Stats",
  majorFamily: "video_data", mergeTargetDataset: "video_master", mergeKeyStrategy: "video_identity",
  uploadHint: "video_data", defaultTag: "mixed", subtableId: "video_statistics",
  capabilitySources: ["analytics_api", "data_api", "csv_only"], freshnessClass: "stable",
 },
 top_videos_by_subscriber_status: {
  category: "top_videos_by_subscriber_status", label: "Top Videos by Subscriber Status", shortLabel: "Subscriber Status",
  majorFamily: "video_data", mergeTargetDataset: "video_content_breakdown", mergeKeyStrategy: "video_identity",
  uploadHint: "video_data", defaultTag: "mixed", subtableId: "video_statistics",
  capabilitySources: ["analytics_api", "csv_only"], freshnessClass: "ninety_day_limited",
 },
 weekly_statistics: {
  category: "weekly_statistics", label: "Weekly Statistics", shortLabel: "Weekly",
  majorFamily: "daily_metrics", mergeTargetDataset: "daily_metrics", mergeKeyStrategy: "date",
  uploadHint: "daily_metrics", defaultTag: "daily", subtableId: "weekly_statistics",
  capabilitySources: ["analytics_api", "csv_only"], freshnessClass: "stable",
 },
 monthly_statistics: {
  category: "monthly_statistics", label: "Monthly Statistics", shortLabel: "Monthly",
  majorFamily: "daily_metrics", mergeTargetDataset: "daily_metrics", mergeKeyStrategy: "date",
  uploadHint: "daily_metrics", defaultTag: "daily", subtableId: "monthly_statistics",
  capabilitySources: ["analytics_api", "csv_only"], freshnessClass: "stable",
 },
 window_statistics: {
  category: "window_statistics", label: "Window Statistics", shortLabel: "Window Stats",
  majorFamily: "daily_metrics", mergeTargetDataset: "daily_metrics", mergeKeyStrategy: "date",
  uploadHint: "daily_metrics", defaultTag: "daily", subtableId: "window_statistics",
  capabilitySources: ["analytics_api", "csv_only"], freshnessClass: "stable",
 },
 audience_operating_system: {
  category: "audience_operating_system", label: "Audience Operating System", shortLabel: "Operating System",
  majorFamily: "audience", mergeTargetDataset: "audience_devices", mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "audience", defaultTag: "audience", subtableId: "operating_system",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"], freshnessClass: "stable",
 },
 audience_device_operating_system: {
  category: "audience_device_operating_system", label: "Device and Operating System", shortLabel: "Device x OS",
  majorFamily: "audience", mergeTargetDataset: "audience_devices", mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "audience", defaultTag: "audience", subtableId: "device_operating_system",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"], freshnessClass: "stable",
 },
 monetization_daily_ad_type: {
  category: "monetization_daily_ad_type", label: "Daily Ad Type", shortLabel: "Daily Ads",
  majorFamily: "revenue_monetization", mergeTargetDataset: "monetization", mergeKeyStrategy: "monetization_dimension_member",
  uploadHint: "revenue_monetization", defaultTag: "other", subtableId: "ad_type",
  capabilitySources: ["analytics_api", "csv_only"], freshnessClass: "stable",
 },
 content_performance: {
  category: "content_performance",
  label: "Content Performance",
  shortLabel: "Content Perf",
  majorFamily: "video_data",
  mergeTargetDataset: "video_master",
  mergeKeyStrategy: "video_identity",
  uploadHint: "video_data",
  defaultTag: "mixed",
  subtableId: "all_videos",
  capabilitySources: ["analytics_api", "data_api"],
  freshnessClass: "stable",
 },
 content_channel_all: {
  category: "content_channel_all",
  label: "Content Channel All",
  shortLabel: "Channel All",
  majorFamily: "video_data",
  mergeTargetDataset: "video_master",
  mergeKeyStrategy: "video_identity",
  uploadHint: "video_data",
  defaultTag: "mixed",
  subtableId: "all_videos",
  capabilitySources: ["analytics_api", "data_api", "csv_only"],
  freshnessClass: "stable",
 },
 video_content_all: {
  category: "video_content_all",
  label: "Video Content All",
  shortLabel: "All Videos",
  majorFamily: "video_data",
  mergeTargetDataset: "video_master",
  mergeKeyStrategy: "video_identity",
  uploadHint: "video_data",
  defaultTag: "mixed",
  subtableId: "all_videos",
  capabilitySources: ["analytics_api", "data_api", "csv_only"],
  freshnessClass: "stable",
 },
 content_shorts: {
  category: "content_shorts",
  label: "Content Shorts",
  shortLabel: "Shorts",
  majorFamily: "video_data",
  mergeTargetDataset: "video_master",
  mergeKeyStrategy: "video_identity",
  uploadHint: "video_data",
  defaultTag: "shorts",
  subtableId: "shorts",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 video_content_shorts: {
  category: "video_content_shorts",
  label: "Video Content Shorts",
  shortLabel: "Shorts",
  majorFamily: "video_data",
  mergeTargetDataset: "video_master",
  mergeKeyStrategy: "video_identity",
  uploadHint: "video_data",
  defaultTag: "shorts",
  subtableId: "shorts",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 content_longform: {
  category: "content_longform",
  label: "Content Long-form",
  shortLabel: "Long-form",
  majorFamily: "video_data",
  mergeTargetDataset: "video_master",
  mergeKeyStrategy: "video_identity",
  uploadHint: "video_data",
  defaultTag: "long",
  subtableId: "long_form",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 video_content_longform: {
  category: "video_content_longform",
  label: "Video Content Long-form",
  shortLabel: "Long-form",
  majorFamily: "video_data",
  mergeTargetDataset: "video_master",
  mergeKeyStrategy: "video_identity",
  uploadHint: "video_data",
  defaultTag: "long",
  subtableId: "long_form",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 video_content_type: {
  category: "video_content_type",
  label: "Video Content Type",
  shortLabel: "Content Type",
  majorFamily: "video_data",
  mergeTargetDataset: "video_content_breakdown",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "video_data",
  defaultTag: "mixed",
  subtableId: "content_type",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 daily_metrics: {
  category: "daily_metrics",
  label: "Daily Metrics",
  shortLabel: "Daily",
  majorFamily: "daily_metrics",
  mergeTargetDataset: "daily_metrics",
  mergeKeyStrategy: "daily_date",
  uploadHint: "daily_metrics",
  defaultTag: "daily",
  subtableId: "daily_channel_metrics",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 daily_channel_metrics: {
  category: "daily_channel_metrics",
  label: "Daily Channel Metrics",
  shortLabel: "Daily",
  majorFamily: "daily_metrics",
  mergeTargetDataset: "daily_metrics",
  mergeKeyStrategy: "daily_date",
  uploadHint: "daily_metrics",
  defaultTag: "daily",
  subtableId: "daily_channel_metrics",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 traffic_report: {
  category: "traffic_report",
  label: "Traffic Report",
  shortLabel: "Traffic",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_summary",
  mergeKeyStrategy: "traffic_summary_source",
  uploadHint: "traffic",
  defaultTag: "traffic",
  subtableId: "all_traffic_sources",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 traffic_overview: {
  category: "traffic_overview",
  label: "Traffic Overview",
  shortLabel: "Overview",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_summary",
  mergeKeyStrategy: "traffic_summary_source",
  uploadHint: "traffic",
  defaultTag: "traffic",
  subtableId: "all_traffic_sources",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 traffic_youtube_search: {
  category: "traffic_youtube_search",
  label: "Traffic YouTube Search",
  shortLabel: "Search",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "search",
  subtableId: "youtube_search_terms",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 youtube_search_terms: {
  category: "youtube_search_terms",
  label: "YouTube Search Terms",
  shortLabel: "Search",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "search",
  subtableId: "youtube_search_terms",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 traffic_external: {
  category: "traffic_external",
  label: "Traffic External",
  shortLabel: "External",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "external",
  subtableId: "external_sources",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 external_sources: {
  category: "external_sources",
  label: "External Sources",
  shortLabel: "External",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "external",
  subtableId: "external_sources",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 traffic_youtube_features: {
  category: "traffic_youtube_features",
  label: "Traffic YouTube Features",
  shortLabel: "YT Features",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "traffic",
  subtableId: "youtube_features",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 traffic_suggested_videos: {
  category: "traffic_suggested_videos",
  label: "Traffic Suggested Videos",
  shortLabel: "Suggested",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "traffic",
  subtableId: "suggested_videos",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 suggested_videos_related: {
  category: "suggested_videos_related",
  label: "Suggested Videos Related",
  shortLabel: "Suggested",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "traffic",
  subtableId: "suggested_videos",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 traffic_shorts_feed: {
  category: "traffic_shorts_feed",
  label: "Traffic Shorts Feed",
  shortLabel: "Shorts Feed",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "traffic",
  subtableId: "shorts_feed_links",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 shorts_content_links: {
  category: "shorts_content_links",
  label: "Shorts Content Links",
  shortLabel: "Shorts Feed",
  majorFamily: "traffic",
  mergeTargetDataset: "traffic_detail",
  mergeKeyStrategy: "traffic_detail_source_title",
  uploadHint: "traffic",
  defaultTag: "traffic",
  subtableId: "shorts_feed_links",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 geography: {
  category: "geography",
  label: "Geography",
  shortLabel: "Country",
  majorFamily: "geography",
  mergeTargetDataset: "geography_country",
  mergeKeyStrategy: "country_name",
  uploadHint: "geography",
  defaultTag: "geo",
  subtableId: "countries",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 geography_country: {
  category: "geography_country",
  label: "Geography Country",
  shortLabel: "Country",
  majorFamily: "geography",
  mergeTargetDataset: "geography_country",
  mergeKeyStrategy: "country_name",
  uploadHint: "geography",
  defaultTag: "geo",
  subtableId: "countries",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 geography_city: {
  category: "geography_city",
  label: "Geography City",
  shortLabel: "City",
  majorFamily: "geography",
  mergeTargetDataset: "geography_city",
  mergeKeyStrategy: "city_name_plus_country_if_present",
  uploadHint: "geography",
  defaultTag: "geo",
  subtableId: "cities",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 audience_demographics: {
  category: "audience_demographics",
  label: "Audience Demographics",
  shortLabel: "Demographics",
  majorFamily: "audience",
  mergeTargetDataset: "audience_demographics",
  mergeKeyStrategy: "age_gender_pair",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "age_gender",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 audience_age: {
  category: "audience_age",
  label: "Audience Age",
  shortLabel: "Age",
  majorFamily: "audience",
  mergeTargetDataset: "audience_demographics",
  mergeKeyStrategy: "age_band",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "age",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 audience_gender: {
  category: "audience_gender",
  label: "Audience Gender",
  shortLabel: "Gender",
  majorFamily: "audience",
  mergeTargetDataset: "audience_demographics",
  mergeKeyStrategy: "gender",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "gender",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 audience_age_gender: {
  category: "audience_age_gender",
  label: "Audience Age and Gender",
  shortLabel: "Age x Gender",
  majorFamily: "audience",
  mergeTargetDataset: "audience_demographics",
  mergeKeyStrategy: "age_gender_pair",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "age_gender",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 audience_growth: {
  category: "audience_growth",
  label: "Audience Growth",
  shortLabel: "Growth",
  majorFamily: "audience",
  mergeTargetDataset: "audience_growth",
  mergeKeyStrategy: "daily_date",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "size_growth",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "ninety_day_limited",
 },
 audience_size_growth: {
  category: "audience_size_growth",
  label: "Audience Size and Growth",
  shortLabel: "Size & Growth",
  majorFamily: "audience",
  mergeTargetDataset: "audience_growth",
  mergeKeyStrategy: "daily_date",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "size_growth",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "ninety_day_limited",
 },
 audience_new_returning: {
  category: "audience_new_returning",
  label: "Audience New and Returning",
  shortLabel: "New & Returning",
  majorFamily: "audience",
  mergeTargetDataset: "audience_behavior",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "new_returning",
  capabilitySources: ["csv_only"],
  freshnessClass: "ninety_day_limited",
 },
 audience_watch_behavior: {
  category: "audience_watch_behavior",
  label: "Audience Watch Behavior",
  shortLabel: "Watch Behavior",
  majorFamily: "audience",
  mergeTargetDataset: "audience_behavior",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "watch_behavior",
  capabilitySources: ["csv_only"],
  freshnessClass: "ninety_day_limited",
 },
 audience_devices: {
  category: "audience_devices",
  label: "Audience Devices",
  shortLabel: "Devices",
  majorFamily: "audience",
  mergeTargetDataset: "audience_devices",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "devices",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 audience_retention_single_video: {
  category: "audience_retention_single_video",
  label: "Audience Retention Single Video",
  shortLabel: "Retention",
  majorFamily: "audience",
  mergeTargetDataset: "audience_retention",
  mergeKeyStrategy: "retention_position",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "retention",
  capabilitySources: ["csv_only"],
  freshnessClass: "single_video",
 },
 audience_retention_segment: {
  category: "audience_retention_segment",
  label: "Audience Retention Segment",
  shortLabel: "Retention Activity",
  majorFamily: "audience",
  mergeTargetDataset: "audience_retention",
  mergeKeyStrategy: "retention_position",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "retention",
  capabilitySources: ["csv_only"],
  freshnessClass: "single_video",
 },
 audience_retention_curve: {
  category: "audience_retention_curve",
  label: "Audience Retention Curve",
  shortLabel: "Retention",
  majorFamily: "audience",
  mergeTargetDataset: "audience_retention",
  mergeKeyStrategy: "retention_position",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "retention",
  capabilitySources: ["csv_only"],
  freshnessClass: "single_video",
 },
 audience_retention_activity: {
  category: "audience_retention_activity",
  label: "Audience Retention Activity",
  shortLabel: "Retention Activity",
  majorFamily: "audience",
  mergeTargetDataset: "audience_retention",
  mergeKeyStrategy: "retention_position",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "retention",
  capabilitySources: ["csv_only"],
  freshnessClass: "single_video",
 },
 retention_curve: {
  category: "retention_curve",
  label: "Retention Curve",
  shortLabel: "Retention",
  majorFamily: "audience",
  mergeTargetDataset: "audience_retention",
  mergeKeyStrategy: "retention_position",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "retention",
  capabilitySources: ["csv_only"],
  freshnessClass: "single_video",
 },
 stw_procedure: {
  category: "stw_procedure",
  label: "Stayed to Watch Procedure",
  shortLabel: "Watch Behavior",
  majorFamily: "audience",
  mergeTargetDataset: "audience_behavior",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "watch_behavior",
  capabilitySources: ["csv_only"],
  freshnessClass: "stable",
 },
 reflection_rate_checks: {
  category: "reflection_rate_checks",
  label: "Reflection Rate Checks",
  shortLabel: "Watch Behavior",
  majorFamily: "audience",
  mergeTargetDataset: "audience_behavior",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "audience",
  defaultTag: "audience",
  subtableId: "watch_behavior",
  capabilitySources: ["csv_only"],
  freshnessClass: "stable",
 },
 surface_playback_location: {
  category: "surface_playback_location",
  label: "Playback Location",
  shortLabel: "Playback",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "playback_location",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_subscription_status: {
  category: "surface_subscription_status",
  label: "Subscription Status",
  shortLabel: "Sub Status",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "subscription_status",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_subscription_source: {
  category: "surface_subscription_source",
  label: "Subscription Source",
  shortLabel: "Sub Source",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "subscription_source",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_sharing_service: {
  category: "surface_sharing_service",
  label: "Sharing Service",
  shortLabel: "Sharing",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "sharing_service",
  capabilitySources: ["reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_playlist: {
  category: "surface_playlist",
  label: "Playlist",
  shortLabel: "Playlist",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "playlists",
  capabilitySources: ["analytics_api", "reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_post: {
  category: "surface_post",
  label: "Post",
  shortLabel: "Post",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "posts",
  capabilitySources: ["csv_only"],
  freshnessClass: "stable",
 },
 surface_card: {
  category: "surface_card",
  label: "Card",
  shortLabel: "Card",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "cards",
  capabilitySources: ["reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_card_type: {
  category: "surface_card_type",
  label: "Card Type",
  shortLabel: "Card Type",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "card_types",
  capabilitySources: ["reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_end_screen: {
  category: "surface_end_screen",
  label: "End Screen",
  shortLabel: "End Screen",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "end_screens",
  capabilitySources: ["reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_end_screen_type: {
  category: "surface_end_screen_type",
  label: "End Screen Type",
  shortLabel: "End Screen Type",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "end_screen_types",
  capabilitySources: ["reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_subtitles_cc: {
  category: "surface_subtitles_cc",
  label: "Subtitles and CC",
  shortLabel: "Subtitles",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "subtitles_cc",
  capabilitySources: ["reporting_api", "csv_only"],
  freshnessClass: "stable",
 },
 surface_translation_use: {
  category: "surface_translation_use",
  label: "Translation Use",
  shortLabel: "Translation",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "translation_use",
  capabilitySources: ["csv_only"],
  freshnessClass: "stable",
 },
 surface_video_info_language: {
  category: "surface_video_info_language",
  label: "Video Info Language",
  shortLabel: "Language",
  majorFamily: "surfaces_discovery",
  mergeTargetDataset: "surfaces_discovery",
  mergeKeyStrategy: "surface_dimension_member",
  uploadHint: "surfaces_discovery",
  defaultTag: "other",
  subtableId: "video_info_language",
  capabilitySources: ["csv_only"],
  freshnessClass: "stable",
 },
 monetization_revenue_source: {
  category: "monetization_revenue_source",
  label: "Revenue Source",
  shortLabel: "Revenue Source",
  majorFamily: "revenue_monetization",
  mergeTargetDataset: "monetization",
  mergeKeyStrategy: "monetization_dimension_member",
  uploadHint: "revenue_monetization",
  defaultTag: "other",
  subtableId: "revenue_source",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
 monetization_ad_type: {
  category: "monetization_ad_type",
  label: "Ad Type",
  shortLabel: "Ad Type",
  majorFamily: "revenue_monetization",
  mergeTargetDataset: "monetization",
  mergeKeyStrategy: "monetization_dimension_member",
  uploadHint: "revenue_monetization",
  defaultTag: "other",
  subtableId: "ad_type",
  capabilitySources: ["analytics_api", "csv_only"],
  freshnessClass: "stable",
 },
}

const MANUAL_OVERRIDE_TO_TAG: Record<Exclude<CsvUploadType, "auto">, CsvTag> = {
 shorts: "shorts",
 long: "long",
 combined: "combined",
 mixed: "mixed",
 single_long_video: "single_long_video",
 single_short_video: "single_short_video",
 geo: "geo",
 audience: "audience",
 traffic: "traffic",
 external: "external",
 search: "search",
 daily: "daily",
 other: "other",
 unknown: "unknown",
 video_data: "mixed",
 daily_metrics: "daily",
 search_intelligence: "search",
 geography: "geo",
 surfaces_discovery: "other",
 revenue_monetization: "other",
}

export const getCsvFamilyDefinition = (
 category: CsvDetectedCategory | undefined,
): CsvFamilyDefinition => CSV_FAMILY_DEFINITIONS[category || "unknown"] || CSV_FAMILY_DEFINITIONS.unknown

export const getCsvCategoryLabel = (category: CsvDetectedCategory | undefined): string =>
 getCsvFamilyDefinition(category).label

export const getCsvMajorFamily = (
 category: CsvDetectedCategory | undefined,
): CsvMajorFamily => getCsvFamilyDefinition(category).majorFamily

export const getCsvUploadTypeStyle = (uploadType: CsvUploadType): string => {
 if (uploadType === "auto") return "bg-[#24D3FF] text-black"
 return CSV_MAJOR_FAMILY_STYLES[uploadType as CsvMajorFamily]?.menuClass ||
  CSV_MAJOR_FAMILY_STYLES[getUploadTypeMajorFamily(uploadType)].menuClass
}

export const getUploadTypeMajorFamily = (uploadType: CsvUploadType): CsvMajorFamily => {
 if (uploadType === "auto") return "unknown"
 if (uploadType in CSV_MAJOR_FAMILY_STYLES) return uploadType as CsvMajorFamily
 switch (uploadType) {
  case "traffic":
  case "external":
  case "search":
   return "traffic"
  case "geo":
   return "geography"
  case "audience":
   return "audience"
  case "daily":
   return "daily_metrics"
  case "shorts":
  case "long":
  case "combined":
  case "mixed":
  case "single_long_video":
  case "single_short_video":
   return "video_data"
  case "other":
   return "surfaces_discovery"
  default:
   return "unknown"
 }
}

export const uploadTypeToCsvTag = (uploadType: CsvUploadType): CsvTag | null => {
 if (uploadType === "auto") return null
 return MANUAL_OVERRIDE_TO_TAG[uploadType]
}

export const getCsvDetectedCategoryPillClass = (
 category: CsvDetectedCategory | undefined,
): string => CSV_MAJOR_FAMILY_STYLES[getCsvMajorFamily(category)].pillClass

export const getCsvTagColorClass = (tagOrType: string): string => {
 if ((tagOrType as CsvUploadType) in CSV_MAJOR_FAMILY_STYLES) {
  return CSV_MAJOR_FAMILY_STYLES[tagOrType as CsvMajorFamily].pillClass
 }
 switch (tagOrType) {
  case "shorts":
   return "bg-[#FF7497] text-white"
  case "long":
  case "single_long_video":
   return "bg-[#00CCFF] text-black"
  case "single_short_video":
   return "bg-[#FF7497] text-white"
  case "traffic":
   return CSV_MAJOR_FAMILY_STYLES.traffic.pillClass
  case "audience":
   return CSV_MAJOR_FAMILY_STYLES.audience.pillClass
  case "geo":
   return CSV_MAJOR_FAMILY_STYLES.geography.pillClass
  case "mixed":
  case "combined":
   return CSV_MAJOR_FAMILY_STYLES.video_data.pillClass
  case "external":
   return "bg-[#24D3FF] text-black"
  case "search":
   return "bg-[#FFE357] text-black"
  case "daily":
   return CSV_MAJOR_FAMILY_STYLES.daily_metrics.pillClass
  default:
   return "bg-white text-black"
 }
}
