export const VT_SYNC_COUNTRY_NAMES: Readonly<Record<string, string>> = {
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua and Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azerbaijan",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caribbean Netherlands",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Democratic Republic of the Congo",
  "CF": "Central African Republic",
  "CG": "Republic of the Congo",
  "CH": "Switzerland",
  "CI": "Côte d'Ivoire",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GS": "South Georgia and the South Sandwich Islands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong",
  "HM": "Heard Island and McDonald Islands",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "Saint Kitts and Nevis",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "PN": "Pitcairn Islands",
  "PR": "Puerto Rico",
  "PS": "Palestine",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "Saint Helena, Ascension and Tristan da Cunha",
  "SI": "Slovenia",
  "SJ": "Svalbard and Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "São Tomé and Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "TC": "Turks and Caicos Islands",
  "TD": "Chad",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "Trinidad and Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "United States Minor Outlying Islands",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Vatican City",
  "VC": "Saint Vincent and the Grenadines",
  "VE": "Venezuela",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis and Futuna",
  "WS": "Samoa",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "XK": "Kosovo",
  "ZZ": "Unknown or Direct Origin"
}

export const VT_SYNC_STATE_NAMES: Readonly<Record<string, string>> = {
  "US-AL": "Alabama",
  "US-AK": "Alaska",
  "US-AZ": "Arizona",
  "US-AR": "Arkansas",
  "US-CA": "California",
  "US-CO": "Colorado",
  "US-CT": "Connecticut",
  "US-DE": "Delaware",
  "US-DC": "District of Columbia",
  "US-FL": "Florida",
  "US-GA": "Georgia",
  "US-HI": "Hawaii",
  "US-ID": "Idaho",
  "US-IL": "Illinois",
  "US-IN": "Indiana",
  "US-IA": "Iowa",
  "US-KS": "Kansas",
  "US-KY": "Kentucky",
  "US-LA": "Louisiana",
  "US-ME": "Maine",
  "US-MD": "Maryland",
  "US-MA": "Massachusetts",
  "US-MI": "Michigan",
  "US-MN": "Minnesota",
  "US-MS": "Mississippi",
  "US-MO": "Missouri",
  "US-MT": "Montana",
  "US-NE": "Nebraska",
  "US-NV": "Nevada",
  "US-NH": "New Hampshire",
  "US-NJ": "New Jersey",
  "US-NM": "New Mexico",
  "US-NY": "New York",
  "US-NC": "North Carolina",
  "US-ND": "North Dakota",
  "US-OH": "Ohio",
  "US-OK": "Oklahoma",
  "US-OR": "Oregon",
  "US-PA": "Pennsylvania",
  "US-RI": "Rhode Island",
  "US-SC": "South Carolina",
  "US-SD": "South Dakota",
  "US-TN": "Tennessee",
  "US-TX": "Texas",
  "US-UT": "Utah",
  "US-VT": "Vermont",
  "US-VA": "Virginia",
  "US-WA": "Washington",
  "US-WV": "West Virginia",
  "US-WI": "Wisconsin",
  "US-WY": "Wyoming",
  "US-ZZ": "Unknown U.S. State"
}

export const VT_SYNC_DMA_NAMES: Readonly<Record<string, string>> = {
  "500": "Portland, ME / Auburn, ME",
  "501": "New York, NY",
  "502": "Binghamton, NY",
  "503": "Macon, GA",
  "504": "Philadelphia, PA",
  "505": "Detroit, MI",
  "506": "Boston, MA / Manchester, NH",
  "507": "Savannah, GA",
  "508": "Pittsburgh, PA",
  "509": "Fort Wayne, IN",
  "510": "Cleveland, OH / Akron, OH / Canton, OH",
  "511": "Washington, DC / Hagerstown, MD",
  "512": "Baltimore, MD",
  "513": "Flint, MI / Saginaw, MI / Bay City, MI",
  "514": "Buffalo, NY",
  "515": "Cincinnati, OH",
  "516": "Erie, PA",
  "517": "Charlotte, NC",
  "518": "Greensboro, NC / High Point, NC / Winston-Salem, NC",
  "519": "Charleston, SC",
  "520": "Augusta, GA / Aiken, SC",
  "521": "Providence, RI / New Bedford, MA",
  "522": "Columbus, GA / Opelika, AL",
  "523": "Burlington, VT / Plattsburgh, NY",
  "524": "Atlanta, GA",
  "525": "Albany, GA",
  "526": "Utica, NY",
  "527": "Indianapolis, IN",
  "528": "Miami, FL / Fort Lauderdale, FL",
  "529": "Louisville, KY",
  "530": "Tallahassee, FL / Thomasville, GA",
  "531": "Tri-Cities, TN / VA",
  "532": "Albany, NY / Schenectady, NY / Troy, NY",
  "533": "Hartford, CT / New Haven, CT",
  "534": "Orlando, FL / Daytona Beach, FL / Melbourne, FL",
  "535": "Columbus, OH",
  "536": "Youngstown, OH",
  "537": "Bangor, ME",
  "538": "Rochester, NY",
  "539": "Tampa, FL / St. Petersburg, FL / Sarasota, FL",
  "540": "Traverse City, MI / Cadillac, MI",
  "541": "Lexington, KY",
  "542": "Dayton, OH",
  "543": "Springfield, MA / Holyoke, MA",
  "544": "Norfolk, VA / Portsmouth, VA / Newport News, VA",
  "545": "Greenville, NC / New Bern, NC / Washington, NC",
  "546": "Columbia, SC",
  "547": "Toledo, OH",
  "548": "West Palm Beach, FL / Fort Pierce, FL",
  "549": "Watertown, NY",
  "550": "Wilmington, NC",
  "551": "Lansing, MI",
  "552": "Presque Isle, ME",
  "553": "Marquette, MI",
  "554": "Wheeling, WV / Steubenville, OH",
  "555": "Syracuse, NY",
  "556": "Richmond, VA / Petersburg, VA",
  "557": "Knoxville, TN",
  "558": "Lima, OH",
  "559": "Bluefield, WV / Beckley, WV / Oak Hill, WV",
  "560": "Raleigh, NC / Durham, NC / Fayetteville, NC",
  "561": "Jacksonville, FL",
  "563": "Grand Rapids, MI / Kalamazoo, MI / Battle Creek, MI",
  "564": "Charleston, WV / Huntington, WV",
  "565": "Elmira, NY / Corning, NY",
  "566": "Harrisburg, PA / Lancaster, PA / Lebanon, PA / York, PA",
  "567": "Greenville, SC / Spartanburg, SC / Asheville, NC / Anderson, SC",
  "569": "Harrisonburg, VA",
  "570": "Myrtle Beach, SC / Florence, SC",
  "571": "Fort Myers, FL / Naples, FL",
  "573": "Roanoke, VA / Lynchburg, VA",
  "574": "Johnstown, PA / Altoona, PA / State College, PA",
  "575": "Chattanooga, TN",
  "576": "Salisbury, MD",
  "577": "Wilkes-Barre, PA / Scranton, PA / Hazleton, PA",
  "581": "Terre Haute, IN",
  "582": "Lafayette, IN",
  "583": "Alpena, MI",
  "584": "Charlottesville, VA",
  "588": "South Bend, IN / Elkhart, IN",
  "592": "Gainesville, FL",
  "596": "Zanesville, OH",
  "597": "Parkersburg, WV",
  "598": "Clarksburg, WV / Weston, WV",
  "600": "Corpus Christi, TX",
  "602": "Chicago, IL",
  "603": "Joplin, MO / Pittsburg, KS",
  "604": "Columbia, MO / Jefferson City, MO",
  "605": "Topeka, KS",
  "606": "Dothan, AL",
  "609": "St. Louis, MO",
  "610": "Rockford, IL",
  "611": "Rochester, MN / Mason City, IA / Austin, MN",
  "612": "Shreveport, LA",
  "613": "Minneapolis, MN / St. Paul, MN",
  "616": "Kansas City, MO",
  "617": "Milwaukee, WI",
  "618": "Houston, TX",
  "619": "Springfield, MO",
  "622": "New Orleans, LA",
  "623": "Dallas, TX / Fort Worth, TX",
  "624": "Sioux City, IA",
  "625": "Waco, TX / Temple, TX / Bryan, TX",
  "626": "Victoria, TX",
  "627": "Wichita Falls, TX / Lawton, OK",
  "628": "Monroe, LA / El Dorado, AR",
  "630": "Birmingham, AL / Anniston, AL / Tuscaloosa, AL",
  "631": "Ottumwa, IA / Kirksville, MO",
  "632": "Paducah, KY / Cape Girardeau, MO / Harrisburg, IL",
  "633": "Odessa, TX / Midland, TX",
  "634": "Amarillo, TX",
  "635": "Austin, TX",
  "636": "Harlingen, TX / Weslaco, TX / Brownsville, TX / McAllen, TX",
  "637": "Cedar Rapids, IA / Waterloo, IA / Iowa City, IA / Dubuque, IA",
  "638": "St. Joseph, MO",
  "639": "Jackson, TN",
  "640": "Memphis, TN",
  "641": "San Antonio, TX",
  "642": "Lafayette, LA",
  "643": "Lake Charles, LA",
  "644": "Alexandria, LA",
  "647": "Greenwood, MS / Greenville, MS",
  "648": "Champaign, IL / Springfield, IL / Decatur, IL",
  "649": "Evansville, IN",
  "650": "Oklahoma City, OK",
  "651": "Lubbock, TX",
  "652": "Omaha, NE",
  "656": "Panama City, FL",
  "657": "Sherman, TX / Ada, OK",
  "658": "Green Bay, WI / Appleton, WI",
  "659": "Nashville, TN",
  "661": "San Angelo, TX",
  "662": "Abilene, TX / Sweetwater, TX",
  "669": "Madison, WI",
  "670": "Fort Smith, AR / Fayetteville, AR / Springdale, AR / Rogers, AR",
  "671": "Tulsa, OK",
  "673": "Columbus, MS / Tupelo, MS / West Point, MS / Houston, MS",
  "675": "Peoria, IL / Bloomington, IL",
  "676": "Duluth, MN / Superior, WI",
  "678": "Wichita, KS / Hutchinson, KS",
  "679": "Des Moines, IA / Ames, IA",
  "682": "Davenport, IA / Rock Island, IL / Moline, IL",
  "686": "Mobile, AL / Pensacola, FL / Fort Walton Beach, FL",
  "687": "Minot, ND / Bismarck, ND / Dickinson, ND / Williston, ND",
  "691": "Huntsville, AL / Decatur, AL / Florence, AL",
  "692": "Beaumont, TX / Port Arthur, TX",
  "693": "Little Rock, AR / Pine Bluff, AR",
  "698": "Montgomery, AL / Selma, AL",
  "702": "La Crosse, WI / Eau Claire, WI",
  "705": "Wausau, WI / Rhinelander, WI",
  "709": "Tyler, TX / Longview, TX / Lufkin, TX / Nacogdoches, TX",
  "710": "Hattiesburg, MS / Laurel, MS",
  "711": "Meridian, MS",
  "716": "Baton Rouge, LA",
  "717": "Quincy, IL / Hannibal, MO / Keokuk, IA",
  "718": "Jackson, MS",
  "722": "Lincoln, NE / Hastings, NE / Kearney, NE",
  "724": "Fargo, ND / Valley City, ND",
  "725": "Sioux Falls, SD / Mitchell, SD",
  "734": "Jonesboro, AR",
  "736": "Bowling Green, KY",
  "737": "Mankato, MN",
  "740": "North Platte, NE",
  "743": "Anchorage, AK",
  "744": "Honolulu, HI",
  "745": "Fairbanks, AK",
  "746": "Biloxi, MS / Gulfport, MS",
  "747": "Juneau, AK",
  "749": "Laredo, TX",
  "751": "Denver, CO",
  "752": "Colorado Springs, CO / Pueblo, CO",
  "753": "Phoenix, AZ / Prescott, AZ",
  "754": "Butte, MT / Bozeman, MT",
  "755": "Great Falls, MT",
  "756": "Billings, MT",
  "757": "Boise, ID",
  "758": "Idaho Falls, ID / Pocatello, ID / Jackson, WY",
  "759": "Cheyenne, WY / Scottsbluff, NE",
  "760": "Twin Falls, ID",
  "762": "Missoula, MT",
  "764": "Rapid City, SD",
  "765": "El Paso, TX / Las Cruces, NM",
  "766": "Helena, MT",
  "767": "Casper, WY / Riverton, WY",
  "770": "Salt Lake City, UT",
  "771": "Yuma, AZ / El Centro, CA",
  "773": "Grand Junction, CO / Montrose, CO",
  "789": "Tucson, AZ / Sierra Vista, AZ",
  "790": "Albuquerque, NM / Santa Fe, NM",
  "798": "Glendive, MT",
  "800": "Bakersfield, CA",
  "801": "Eugene, OR",
  "802": "Eureka, CA",
  "803": "Los Angeles, CA",
  "804": "Palm Springs, CA",
  "807": "San Francisco, CA / Oakland, CA / San Jose, CA",
  "810": "Yakima, WA / Pasco, WA / Richland, WA / Kennewick, WA",
  "811": "Reno, NV",
  "813": "Medford, OR / Klamath Falls, OR",
  "819": "Seattle, WA / Tacoma, WA",
  "820": "Portland, OR",
  "821": "Bend, OR",
  "825": "San Diego, CA",
  "828": "Monterey, CA / Salinas, CA",
  "839": "Las Vegas, NV",
  "855": "Santa Barbara, CA / Santa Maria, CA / San Luis Obispo, CA",
  "862": "Sacramento, CA / Stockton, CA / Modesto, CA",
  "866": "Fresno, CA / Visalia, CA",
  "868": "Chico, CA / Redding, CA",
  "881": "Spokane, WA"
}

const normalizedText = (value: unknown): string => String(value ?? "").trim()

export const normalizeVtSyncCountryCode = (value: unknown): string =>
 normalizedText(value).toUpperCase()

export const getVtSyncCountryName = (value: unknown): string => {
 const code = normalizeVtSyncCountryCode(value)
 return VT_SYNC_COUNTRY_NAMES[code] || code || "Unknown"
}

export const getVtSyncCountryFlag = (value: unknown): string => {
 const code = normalizeVtSyncCountryCode(value)
 if (code === "ZZ" || !/^[A-Z]{2}$/.test(code)) return "xx"
 return code.toLowerCase()
}

export const normalizeVtSyncStateCode = (value: unknown): string => {
 const code = normalizedText(value).toUpperCase()
 if (!code) return ""
 return code.startsWith("US-") ? code : `US-${code}`
}

export const getVtSyncStateName = (value: unknown): string => {
 const code = normalizeVtSyncStateCode(value)
 return VT_SYNC_STATE_NAMES[code] || normalizedText(value) || "Unknown State"
}

export const normalizeVtSyncDmaCode = (value: unknown): string =>
 normalizedText(value)

export const getVtSyncDmaName = (value: unknown): string => {
 const code = normalizeVtSyncDmaCode(value)
 return VT_SYNC_DMA_NAMES[code] || "Unmapped DMA"
}
