import type { VideoDirectorCategoryId } from "./categorySchemas"

export type VideoDirectorCategoryGroup =
  | "creative"
  | "camera"
  | "image"
  | "motion"
  | "audio"
  | "graphics"
  | "generation"

export interface VideoDirectorCategoryDefinition {
  id: VideoDirectorCategoryId
  label: string
  shortLabel: string
  group: VideoDirectorCategoryGroup
  purpose: string
  compoundComponent: string
  dependencies: readonly VideoDirectorCategoryId[]
  related: readonly VideoDirectorCategoryId[]
  shotOverride: boolean
  variationSupport: boolean
  recipeSupport: boolean
  order: number
}

const category = (
  definition: VideoDirectorCategoryDefinition,
): VideoDirectorCategoryDefinition => Object.freeze(definition)

export const VIDEO_DIRECTOR_CATEGORY_REGISTRY = Object.freeze([
  category({
    id: "concept-direction",
    label: "Concept & Direction",
    shortLabel: "Concept",
    group: "creative",
    purpose: "Define the creator brief, objective, audience, treatment, CTA, and concept variation strategy.",
    compoundComponent: "Concept treatment cards + comparison deck",
    dependencies: [],
    related: ["visual-style", "emotion-tone", "shot-structure"],
    shotOverride: false,
    variationSupport: true,
    recipeSupport: true,
    order: 0,
  }),
  category({
    id: "visual-style",
    label: "Visual Style",
    shortLabel: "Style",
    group: "creative",
    purpose: "Describe the visual language, medium, period, realism, and reusable style recipes.",
    compoundComponent: "Style recipe browser + visual reference previews",
    dependencies: ["concept-direction"],
    related: ["color-palette", "texture-film", "lighting"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 1,
  }),
  category({
    id: "emotion-tone",
    label: "Emotion & Tone",
    shortLabel: "Emotion",
    group: "creative",
    purpose: "Direct emotional energy, warmth, tension, and tonal intensity.",
    compoundComponent: "2D mood quadrant + intensity mixer",
    dependencies: ["concept-direction"],
    related: ["timing-pacing", "music", "grade-exposure"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 2,
  }),
  category({
    id: "composition",
    label: "Composition",
    shortLabel: "Composition",
    group: "creative",
    purpose: "Control shot scale, framing grammar, subject placement, horizon, and safe zones.",
    compoundComponent: "Interactive framing canvas + platform safe zones",
    dependencies: [],
    related: ["camera-lens", "perspective-capture", "generation-output"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 3,
  }),
  category({
    id: "camera-lens",
    label: "Camera & Lens",
    shortLabel: "Lens",
    group: "camera",
    purpose: "Choose capture family, focal length, aperture, anamorphic behavior, and lens distortion.",
    compoundComponent: "Lens field-of-view simulator",
    dependencies: [],
    related: ["focus-depth", "camera-movement", "perspective-capture"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 4,
  }),
  category({
    id: "camera-movement",
    label: "Camera Movement",
    shortLabel: "Movement",
    group: "camera",
    purpose: "Direct camera trajectory, speed, stabilization, shake, pan, tilt, orbit, and dolly movement.",
    compoundComponent: "Camera path/vector controller",
    dependencies: ["camera-lens"],
    related: ["speed-motion", "focus-depth", "perspective-capture"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 5,
  }),
  category({
    id: "focus-depth",
    label: "Focus & Depth",
    shortLabel: "Focus",
    group: "camera",
    purpose: "Control focal plane, depth strength, bokeh, focus breathing, and rack-focus behavior.",
    compoundComponent: "Aperture/depth-of-field visual guide",
    dependencies: ["camera-lens"],
    related: ["camera-movement", "composition"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 6,
  }),
  category({
    id: "perspective-capture",
    label: "Perspective & Capture Style",
    shortLabel: "Perspective",
    group: "camera",
    purpose: "Select rig viewpoint such as tripod, phone POV, drone, security camera, bodycam, or dashcam.",
    compoundComponent: "Capture-rig perspective selector",
    dependencies: [],
    related: ["camera-lens", "camera-movement", "composition"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 7,
  }),
  category({
    id: "color-palette",
    label: "Color Palette",
    shortLabel: "Palette",
    group: "image",
    purpose: "Define or extract a constrained project palette and lock dominant color relationships.",
    compoundComponent: "Six-color palette lock/extraction board",
    dependencies: [],
    related: ["grade-exposure", "visual-style", "consistency-continuity"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 8,
  }),
  category({
    id: "grade-exposure",
    label: "Grade & Exposure",
    shortLabel: "Grade",
    group: "image",
    purpose: "Control exposure, contrast, tonal range, temperature, tint, saturation, and gamma.",
    compoundComponent: "Compact grading board",
    dependencies: ["color-palette"],
    related: ["texture-film", "lighting"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 9,
  }),
  category({
    id: "texture-film",
    label: "Texture & Film",
    shortLabel: "Texture",
    group: "image",
    purpose: "Layer grain, halation, bloom, scratches, dust, gate weave, and film-stock behavior.",
    compoundComponent: "Ordered film/texture stack",
    dependencies: [],
    related: ["grade-exposure", "visual-effects"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 10,
  }),
  category({
    id: "lighting",
    label: "Lighting",
    shortLabel: "Lighting",
    group: "image",
    purpose: "Direct key-light angle, elevation, color temperature, softness, fill, rim, and volumetric intensity.",
    compoundComponent: "Interactive 3D lighting sphere",
    dependencies: [],
    related: ["grade-exposure", "emotion-tone", "visual-effects"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 11,
  }),
  category({
    id: "timing-pacing",
    label: "Timing & Pacing",
    shortLabel: "Pacing",
    group: "motion",
    purpose: "Control total duration, frame cadence, opening hook, final hold, energy, and tension curves.",
    compoundComponent: "Energy/tension curve canvas",
    dependencies: ["concept-direction"],
    related: ["shot-structure", "music", "speed-motion"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 12,
  }),
  category({
    id: "shot-structure",
    label: "Shot Structure",
    shortLabel: "Shots",
    group: "motion",
    purpose: "Choose single-take, montage, storyboard, narrative, trailer, or explainer structures.",
    compoundComponent: "Shot-list storyboard sequencer",
    dependencies: ["concept-direction", "timing-pacing"],
    related: ["transitions", "consistency-continuity"],
    shotOverride: false,
    variationSupport: true,
    recipeSupport: true,
    order: 13,
  }),
  category({
    id: "transitions",
    label: "Transitions",
    shortLabel: "Transitions",
    group: "motion",
    purpose: "Define shot joins, duration, audio crossfades, motion matching, and transition recipes.",
    compoundComponent: "Transition preview deck",
    dependencies: ["shot-structure"],
    related: ["speed-motion", "ambience-mix"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 14,
  }),
  category({
    id: "speed-motion",
    label: "Speed & Motion",
    shortLabel: "Speed",
    group: "motion",
    purpose: "Control playback rate, interpolation, motion blur, and time-varying speed ramps.",
    compoundComponent: "Velocity curve + motion-vector controls",
    dependencies: [],
    related: ["camera-movement", "timing-pacing"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 15,
  }),
  category({
    id: "voice-dialogue",
    label: "Voice & Dialogue",
    shortLabel: "Voice",
    group: "audio",
    purpose: "Manage scripts, source voices, language, speaking rate, expressiveness, and dialogue gain.",
    compoundComponent: "Script cue editor + voice assignment lane",
    dependencies: ["concept-direction"],
    related: ["ambience-mix", "captions"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 16,
  }),
  category({
    id: "music",
    label: "Music",
    shortLabel: "Music",
    group: "audio",
    purpose: "Generate, upload, or select music and control BPM, key, genre, intensity, and beat synchronization.",
    compoundComponent: "Beat timeline + music brief",
    dependencies: ["timing-pacing"],
    related: ["emotion-tone", "ambience-mix"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 17,
  }),
  category({
    id: "sound-effects",
    label: "Sound Effects",
    shortLabel: "SFX",
    group: "audio",
    purpose: "Place generated, uploaded, or library sound cues against exact timeline events.",
    compoundComponent: "Sound cue lane",
    dependencies: ["timing-pacing"],
    related: ["ambience-mix", "shot-structure"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 18,
  }),
  category({
    id: "ambience-mix",
    label: "Ambience & Mix",
    shortLabel: "Mix",
    group: "audio",
    purpose: "Set ambience, spatial positioning, dialogue ducking, loudness, and final mix constraints.",
    compoundComponent: "2D spatial audio placement matrix",
    dependencies: [],
    related: ["voice-dialogue", "music", "sound-effects"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 19,
  }),
  category({
    id: "captions",
    label: "Captions",
    shortLabel: "Captions",
    group: "graphics",
    purpose: "Create timed captions, choose source text, positioning, animation, and burn-in behavior.",
    compoundComponent: "Caption timing/style preview",
    dependencies: ["voice-dialogue"],
    related: ["text-titles", "generation-output"],
    shotOverride: false,
    variationSupport: true,
    recipeSupport: true,
    order: 20,
  }),
  category({
    id: "text-titles",
    label: "Text & Titles",
    shortLabel: "Titles",
    group: "graphics",
    purpose: "Place opening titles, lower thirds, labels, watermarks, and authored text overlays.",
    compoundComponent: "Safe-zone typography overlay canvas",
    dependencies: ["composition"],
    related: ["captions", "stickers-overlays"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 21,
  }),
  category({
    id: "stickers-overlays",
    label: "Stickers & Overlays",
    shortLabel: "Overlays",
    group: "graphics",
    purpose: "Layer Vault assets, logos, SVGs, images, and reusable graphics over generated footage.",
    compoundComponent: "Mini overlay layer stack",
    dependencies: [],
    related: ["text-titles", "visual-effects"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 22,
  }),
  category({
    id: "visual-effects",
    label: "Visual Effects",
    shortLabel: "FX",
    group: "graphics",
    purpose: "Apply deterministic fog, snow, dust, bloom, flare, grain, masks, stabilization, and related post effects.",
    compoundComponent: "Ordered effects stack with masks",
    dependencies: [],
    related: ["texture-film", "lighting", "stickers-overlays"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 23,
  }),
  category({
    id: "references-seeds",
    label: "References & Seeds",
    shortLabel: "References",
    group: "generation",
    purpose: "Weight image, video, audio, mask, style, and motion references while managing deterministic seeds.",
    compoundComponent: "Weighted reference board + seed lock",
    dependencies: [],
    related: ["consistency-continuity", "generation-output"],
    shotOverride: true,
    variationSupport: true,
    recipeSupport: true,
    order: 24,
  }),
  category({
    id: "consistency-continuity",
    label: "Consistency & Continuity",
    shortLabel: "Continuity",
    group: "generation",
    purpose: "Maintain characters, wardrobe, products, locations, props, palette, and lighting across shots.",
    compoundComponent: "Character & Asset Continuity Ledger",
    dependencies: ["references-seeds"],
    related: ["shot-structure", "color-palette"],
    shotOverride: true,
    variationSupport: false,
    recipeSupport: true,
    order: 25,
  }),
  category({
    id: "negative-constraints",
    label: "Negative Constraints",
    shortLabel: "Exclusions",
    group: "generation",
    purpose: "Explicitly forbid unwanted objects, visual traits, inaccuracies, or model behaviors.",
    compoundComponent: "Interactive exclusion-tag bank",
    dependencies: [],
    related: ["concept-direction", "generation-output"],
    shotOverride: true,
    variationSupport: false,
    recipeSupport: true,
    order: 26,
  }),
  category({
    id: "generation-output",
    label: "Generation & Output",
    shortLabel: "Output",
    group: "generation",
    purpose: "Choose automatic or manual routing, model, quality tier, resolution, aspect ratio, output count, and finishing options.",
    compoundComponent: "Model router + cost/output panel",
    dependencies: ["timing-pacing"],
    related: ["references-seeds", "composition", "negative-constraints"],
    shotOverride: false,
    variationSupport: false,
    recipeSupport: true,
    order: 27,
  }),
] satisfies readonly VideoDirectorCategoryDefinition[])

export const VIDEO_DIRECTOR_CATEGORY_BY_ID = Object.freeze(
  Object.fromEntries(
    VIDEO_DIRECTOR_CATEGORY_REGISTRY.map((definition) => [definition.id, definition]),
  ) as Record<VideoDirectorCategoryId, VideoDirectorCategoryDefinition>,
)

export const VIDEO_DIRECTOR_CATEGORY_IDS = Object.freeze(
  VIDEO_DIRECTOR_CATEGORY_REGISTRY.map((definition) => definition.id),
)

export const VIDEO_DIRECTOR_CATEGORY_GROUPS: readonly VideoDirectorCategoryGroup[] = Object.freeze([
  "creative",
  "camera",
  "image",
  "motion",
  "audio",
  "graphics",
  "generation",
])
