export type VtSyncVisualStyleSpec = {
  iconKey: string
}

export const VT_SYNC_VISUAL_STYLE_REGISTRY: Readonly<Record<string, VtSyncVisualStyleSpec>> = Object.freeze({
  "combo-channel-progress": { iconKey: "center_focus_weak_70dp_1F1F1F_FILL0_wght700_GRAD0_opsz48" },
  "engagement-lines": { iconKey: "AB-TESTING" },
  "top-performers-trio": { iconKey: "video" },
  "format-comparison-donuts": { iconKey: "layers" },
  "shorts-retention-widget": { iconKey: "video" },
  "algorithm-trigger": { iconKey: "zap" },
  "revenue-distribution": { iconKey: "!!!REVENUE" },
  "revenue-efficiency": { iconKey: "!!!REVENUE" },
  "hook-effectiveness": { iconKey: "ideas" },
  "age-gender-audience": { iconKey: "headset" },
  "subscribers-gained": { iconKey: "!!!SUBSCRIBERS" },
  "watch-time-distribution": { iconKey: "volume" },
  "video-value-matrix": { iconKey: "database" },
  "growth-pulse": { iconKey: "cloud" },
  "signal-matrix": { iconKey: "AB-TESTING" },
  "custom-scatter": { iconKey: "!!!POST-IMAGE" },
  "traffic-source-evolution": { iconKey: "!!!TRAFIC" },
  "keyword-treemap": { iconKey: "!!!TEXT" },
  "keyword-venn": { iconKey: "!!!COLLECTION" },
  "upload-time-heatmap": { iconKey: "calendar" },
  "conversion-funnel": { iconKey: "target" },
  "performance-gauges": { iconKey: "center_focus_weak_70dp_1F1F1F_FILL0_wght700_GRAD0_opsz48" },
  "lissajous-web": { iconKey: "mic" },
  orbital: { iconKey: "cloud" },

  "vt2-weekly-sparklines": { iconKey: "volume" },
  "vt2-revenue-mosaic": { iconKey: "!!!REVENUE" },
  "vt2-search-term-gravity": { iconKey: "!!!YOUTUBE" },
  "vt2-video-fingerprint": { iconKey: "database" },
  "vt2-channel-big-bang": { iconKey: "cloud" },
  "vt2-trajectory-forecaster": { iconKey: "zap" },
  "vt2-multi-metric-timeline": { iconKey: "AB-TESTING" },

  "tube-explorer-clock-radial-burst": { iconKey: "calendar" },
  "tube-explorer-barcode-fingerprint": { iconKey: "database" },
  "tube-explorer-views-subs-growth-quadrant": { iconKey: "target" },
  "tube-explorer-subscriber-waterfall": { iconKey: "!!!SUBSCRIBERS" },
  "tube-explorer-shorts-vs-longs": { iconKey: "video" },
  "tube-explorer-content-treemap": { iconKey: "layers" },
  "tube-explorer-engagement-radar": { iconKey: "headset" },
  "tube-explorer-traffic-day-river-delta": { iconKey: "!!!TRAFIC" },
  "tube-explorer-revenue-efficiency-map": { iconKey: "!!!REVENUE" },
  "tube-explorer-like-rate-waveform": { iconKey: "mic" },
  "tube-explorer-seasonality-radar": { iconKey: "headset" },
  "tube-explorer-bubble-universe": { iconKey: "image" },
  "tube-explorer-retention-curve-atlas": { iconKey: "volume" },
  "tube-explorer-publish-optimal-clock": { iconKey: "calendar" },
  "tube-explorer-sankey-river-delta": { iconKey: "!!!TRAFIC" },
  "tube-explorer-title-word-network": { iconKey: "!!!TEXT" },
  "tube-explorer-channel-vital-signs": { iconKey: "AB-TESTING" },
  "tube-explorer-thermal-imaging": { iconKey: "!!!PALETTE" },
  "tube-explorer-keyword-treemap": { iconKey: "!!!TEXT" },
  "tube-explorer-channel-health-radar": { iconKey: "headset" },
  "tube-explorer-revenue-forecast": { iconKey: "!!!REVENUE" },
  "tube-explorer-traffic-evolution": { iconKey: "!!!TRAFIC" },
  "tube-explorer-video-value-matrix": { iconKey: "database" },
  "tube-explorer-sub-net-flow": { iconKey: "!!!SUBSCRIBERS" },
  "tube-explorer-content-donut": { iconKey: "!!!COLLECTION" },
  "tube-explorer-performance-gauges": { iconKey: "center_focus_weak_70dp_1F1F1F_FILL0_wght700_GRAD0_opsz48" },
  "tube-explorer-revenue-waterfall": { iconKey: "!!!REVENUE" },
  "tube-explorer-conversion-funnel": { iconKey: "database" },
  "tube-explorer-upload-heatmap": { iconKey: "!!!COLLECTION" },
  "tube-explorer-ecg-vitals-monitor": { iconKey: "volume" },
  "tube-explorer-chrono-spiral": { iconKey: "cloud" },
  "tube-explorer-content-dna-gel": { iconKey: "mic" },
  "tube-explorer-performance-waveform": { iconKey: "center_focus_weak_70dp_1F1F1F_FILL0_wght700_GRAD0_opsz48" },
  "tube-explorer-orbital-system": { iconKey: "cloud" },
  "tube-explorer-lissajous-web": { iconKey: "mic" },
  "tube-explorer-keyword-venn-chart": { iconKey: "!!!COLLECTION" },
  "tube-explorer-thermal-heatmap-grid": { iconKey: "!!!PALETTE" },
  "tube-explorer-emission-spectrum": { iconKey: "!!!GEOGRAPHY" },
  "tube-explorer-stalactite-drip": { iconKey: "volume" },
  "tube-explorer-contour-density-map": { iconKey: "!!!POST-IMAGE" },
  "tube-explorer-retention-mosaic": { iconKey: "volume" },
  "tube-explorer-perfection-quadrant": { iconKey: "target" },
  "tube-explorer-duration-retention-scatter": { iconKey: "!!!POST-IMAGE" },
  "tube-explorer-beeswarm-like-rate": { iconKey: "mic" },
  "tube-explorer-calendar-heat-signature": { iconKey: "calendar" },
  "tube-explorer-us-state-dot-map": { iconKey: "!!!GEOGRAPHY" },
})

const STYLE_BY_TITLE: Readonly<Record<string, string>> = Object.freeze({
  "BARCODE FINGERPRINT": "tube-explorer-barcode-fingerprint",
  "SHORTS VS LONGS": "tube-explorer-shorts-vs-longs",
  "CONTENT TREEMAP": "tube-explorer-content-treemap",
  "RIVER DELTA": "tube-explorer-traffic-day-river-delta",
  "PUBLISH OPTIMAL CLOCK": "tube-explorer-publish-optimal-clock",
  "TITLE WORD NETWORK": "tube-explorer-title-word-network",
  "CHANNEL VITAL SIGNS": "tube-explorer-channel-vital-signs",
  "HEAT MATRIX": "tube-explorer-thermal-imaging",
  "TOKEN FOREST": "tube-explorer-keyword-treemap",
  "SIGNAL DIAL": "tube-explorer-channel-health-radar",
  "METRIC WATERFALL": "tube-explorer-subscriber-waterfall",
  "ENGAGEMENT RADAR": "tube-explorer-engagement-radar",
  "REVENUE EFFICIENCY MAP": "tube-explorer-revenue-efficiency-map",
  "LIKE RATE WAVEFORM": "tube-explorer-like-rate-waveform",
  "SEASONALITY RADAR": "tube-explorer-seasonality-radar",
  "BUBBLE UNIVERSE": "tube-explorer-bubble-universe",
  "RETENTION CURVE ATLAS": "tube-explorer-retention-curve-atlas",
  "MONTH HEAT": "tube-explorer-thermal-heatmap-grid",
  "GEO SPECTRUM": "tube-explorer-emission-spectrum",
  "WATCH DRIPS": "tube-explorer-stalactite-drip",
})

export const getVtSyncVisualStyle = (id: string): VtSyncVisualStyleSpec => (
  VT_SYNC_VISUAL_STYLE_REGISTRY[id] ?? { iconKey: "analytics" }
)

export const resolveVtSyncVisualStyle = (idOrTitle: string): VtSyncVisualStyleSpec => {
  const direct = VT_SYNC_VISUAL_STYLE_REGISTRY[idOrTitle]
  if (direct) return direct
  return getVtSyncVisualStyle(STYLE_BY_TITLE[idOrTitle.trim().toUpperCase()] ?? idOrTitle)
}
