import React, { Suspense, useCallback, useEffect, useMemo, useRef, useState } from "react"
import { closestCenter,DndContext,KeyboardSensor,PointerSensor,useSensor,useSensors } from "@dnd-kit/core"
import type { DragEndEvent,DragOverEvent,DragStartEvent } from "@dnd-kit/core"
import { SortableContext,sortableKeyboardCoordinates,rectSortingStrategy,useSortable,arrayMove } from "@dnd-kit/sortable"
import { CSS } from "@dnd-kit/utilities"
import { DashboardBarrier } from "./DashboardBarrier"
import { useDashboard } from "../../context/DashboardContext"
import { DASHBOARD_WIDGET_REGISTRY,DASHBOARD_WIDGET_BY_ID } from "./WidgetRegistry"
import { WidgetPickerPanel } from "./WidgetPickerPanel"
import { exportDashboardLayout,importDashboardLayout,loadDashboardLayout,nextHeightBucket,prevHeightBucket,nextSizeBucket,prevSizeBucket,resetDashboardLayout,revealAllReadyDashboardWidgets,saveDashboardLayout,sizeBucketClassName,heightBucketClassName } from "./storage"
import type { DashboardLayoutState } from "./types"
import type { DashboardData } from "./useDashboardData"
import { WidgetRenderer } from "./WidgetRenderer"
import { WidgetErrorBoundary } from "./WidgetErrorBoundary"
import { resolveDashboardPresetVisibleIds, type DashboardPresetId } from "./dashboardPresetModel"
import { resolveVisibleWidgetSpectrum } from "./spectrum"
import { WidgetDragHandleProvider } from "./WidgetShell"

interface DashboardCanvasProps { data:DashboardData; onNavigate:(to:string)=>void }
const DeferredDashboardWidget:React.FC<{eager:boolean;children:React.ReactNode}>=({eager,children})=>{const hostRef=useRef<HTMLDivElement|null>(null);const[isVisible,setIsVisible]=useState(eager);useEffect(()=>{if(eager||isVisible)return;const host=hostRef.current;if(!host||typeof IntersectionObserver==="undefined"){setIsVisible(true);return}const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;setIsVisible(true);observer.disconnect()},{rootMargin:"700px 0px"});observer.observe(host);return()=>observer.disconnect()},[eager,isVisible]);return <div ref={hostRef} className="h-full">{isVisible?children:null}</div>}
const SortableWidgetItem:React.FC<{id:string;disabled:boolean;className:string;children:React.ReactNode}>=({id,disabled,className,children})=>{const{attributes,listeners,setNodeRef,setActivatorNodeRef,transform,isDragging}=useSortable({id,disabled});const style:React.CSSProperties={transform:CSS.Transform.toString(transform),zIndex:isDragging?20:undefined,position:"relative"};return <div ref={setNodeRef} style={style} className={`dashboard-widget-slot ${className} ${isDragging?'opacity-60':'opacity-100'}`} data-widget-id={id} inert={isDragging}><WidgetDragHandleProvider attributes={attributes as unknown as React.ButtonHTMLAttributes<HTMLButtonElement>} listeners={listeners as unknown as React.DOMAttributes<HTMLButtonElement>} setActivatorNodeRef={setActivatorNodeRef as(node:HTMLButtonElement|null)=>void} disabled={disabled}>{children}</WidgetDragHandleProvider></div>}

export const DashboardCanvas:React.FC<DashboardCanvasProps>=({data,onNavigate})=>{const{editMode,setEditMode,setIsLocked,pickerOpen,setPickerOpen,registerActions}=useDashboard();const[layout,setLayout]=useState<DashboardLayoutState>(()=>loadDashboardLayout());const[dragPreviewOrder,setDragPreviewOrder]=useState<string[]|null>(null);const[recentlyRemovedId,setRecentlyRemovedId]=useState<string|null>(null);const[showWelcomeBanner,setShowWelcomeBanner]=useState<boolean>(()=>new URLSearchParams(window.location.search).get("onboarding")==="welcome");const fileInputRef=useRef<HTMLInputElement|null>(null);const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:8}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));const hiddenSet=useMemo(()=>new Set(layout.hidden),[layout.hidden]);const visibleWidgetIds=useMemo(()=>layout.order.filter(id=>DASHBOARD_WIDGET_BY_ID[id]&&!hiddenSet.has(id)),[layout.order,hiddenSet]);const displayedWidgetIds=dragPreviewOrder||visibleWidgetIds;const spectrumByWidgetId=useMemo(()=>resolveVisibleWidgetSpectrum(displayedWidgetIds,hiddenSet),[displayedWidgetIds,hiddenSet]);useEffect(()=>saveDashboardLayout(layout),[layout]);const canDragReorder=editMode&&!layout.locked;const canResize=editMode;const canHide=editMode;const canStepReorder=editMode;
 const handleDragStart=(event:DragStartEvent)=>{if(canDragReorder){const activeId=String(event.active.id);if(visibleWidgetIds.includes(activeId))setDragPreviewOrder(visibleWidgetIds)}};const handleDragOver=(event:DragOverEvent)=>{if(!canDragReorder||!event.over)return;setDragPreviewOrder(current=>{const order=current||visibleWidgetIds;const oldIndex=order.indexOf(String(event.active.id));const newIndex=order.indexOf(String(event.over?.id));return oldIndex<0||newIndex<0||oldIndex===newIndex?order:arrayMove(order,oldIndex,newIndex)})};const handleDragCancel=()=>setDragPreviewOrder(null);const handleDragEnd=(event:DragEndEvent)=>{if(!canDragReorder)return;const{active,over}=event;const proposedOrder=dragPreviewOrder;setDragPreviewOrder(null);if(!over||active.id===over.id||!proposedOrder)return;setLayout(prev=>({...prev,order:[...proposedOrder,...prev.order.filter(id=>prev.hidden.includes(id))]}))};
 const applyDashboardPreset=useCallback((preset:DashboardPresetId)=>{setLayout(prev=>{const visibleIds=new Set(resolveDashboardPresetVisibleIds(DASHBOARD_WIDGET_REGISTRY,preset));return{...prev,hidden:DASHBOARD_WIDGET_REGISTRY.map(widget=>widget.id).filter(id=>!visibleIds.has(id))}})},[]);
  const toggleWidgetVisibility=(widgetId:string)=>setLayout(prev=>{if(!canStepReorder)return prev;const hidden=new Set(prev.hidden);if(hidden.has(widgetId)){hidden.delete(widgetId);return{...prev,order:[...prev.order.filter(id=>id!==widgetId),widgetId],hidden:[...hidden]}}hidden.add(widgetId);return{...prev,hidden:[...hidden]}});
 const moveWidgetByStep=useCallback((widgetId:string,direction:-1|1)=>{const selector=`[data-widget-id="${widgetId}"]`;const before=document.querySelector<HTMLElement>(selector)?.getBoundingClientRect().top??null;setLayout(prev=>{const hidden=new Set(prev.hidden);const visible=prev.order.filter(id=>DASHBOARD_WIDGET_BY_ID[id]&&!hidden.has(id));const index=visible.indexOf(widgetId);const target=visible[index+direction];if(index<0||!target)return prev;const order=[...prev.order];const from=order.indexOf(widgetId);const to=order.indexOf(target);if(from<0||to<0)return prev;[order[from],order[to]]=[order[to],order[from]];return{...prev,order}});if(before!==null){requestAnimationFrame(()=>requestAnimationFrame(()=>{const after=document.querySelector<HTMLElement>(selector)?.getBoundingClientRect().top;if(typeof after==="number"){window.scrollBy({top:after-before,left:0,behavior:"auto"})}}))}},[]);
 const updateInstance=(widgetId:string,patch:(current:DashboardLayoutState["instances"][string])=>Partial<DashboardLayoutState["instances"][string]>)=>setLayout(prev=>{const current=prev.instances[widgetId];if(!current)return prev;return{...prev,instances:{...prev.instances,[widgetId]:{...current,...patch(current)}}}});
 const onToggleCollapse=(id:string)=>updateInstance(id,c=>({collapsed:!c.collapsed}));const onCycleSize=(id:string)=>{if(canResize)updateInstance(id,c=>({size:nextSizeBucket(id,c.size)}))};const onDecSize=(id:string)=>{if(canResize)updateInstance(id,c=>({size:prevSizeBucket(id,c.size)}))};const onCycleHeight=(id:string)=>{if(canResize)updateInstance(id,c=>({height:nextHeightBucket(id,c.height)}))};const onDecHeight=(id:string)=>{if(canResize)updateInstance(id,c=>({height:prevHeightBucket(id,c.height)}))};const onRemoveWidget=(id:string)=>{if(!canHide)return;setLayout(prev=>({...prev,hidden:prev.hidden.includes(id)?prev.hidden:[...prev.hidden,id]}));setRecentlyRemovedId(id)};
 const handleExport=useCallback(()=>{const blob=new Blob([exportDashboardLayout(layout)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="viewtube-dashboard-layout.json";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)},[layout]);const handleImportClick=useCallback(()=>fileInputRef.current?.click(),[]);const handleImportFile=(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=importDashboardLayout(String(reader.result||""));setLayout(imported);setIsLocked(imported.locked)}catch{window.alert("Invalid dashboard layout JSON. Keeping current layout.")}};reader.readAsText(file);event.target.value=""};const handleToggleLock=useCallback(()=>{const nextLocked=!layout.locked;setLayout(current=>({...current,locked:nextLocked}));setIsLocked(nextLocked)},[layout.locked,setIsLocked]);const handleReset=useCallback(()=>{const reset=resetDashboardLayout();setLayout(reset);setIsLocked(reset.locked)},[setIsLocked]);const handleShowAllWidgets=useCallback(()=>setLayout(current=>revealAllReadyDashboardWidgets(current)),[]);useEffect(()=>registerActions({exportLayout:handleExport,importLayout:handleImportClick,resetLayout:handleReset,toggleLock:handleToggleLock}),[handleExport,handleImportClick,handleReset,handleToggleLock,registerActions]);
 return <DashboardBarrier><div className="dashboard-canvas-inner w-full pb-24 px-1 sm:px-4 md:px-5 xl:px-6"><input ref={fileInputRef} type="file" accept="application/json" onChange={handleImportFile} className="hidden"/>{showWelcomeBanner&&<div className="mb-4 border-[3px] border-black rounded-2xl bg-[#3FEE56] px-4 py-3 shadow-[4px_4px_0_0_#000] flex flex-wrap items-center justify-between gap-2"><p className="text-sm md:text-base font-black uppercase">You’re set. Next: Connect channel.</p><button onClick={()=>setShowWelcomeBanner(false)} className="border-[2px] border-black rounded-lg bg-white px-3 py-1 text-[10px] font-black uppercase">Dismiss</button></div>}
 <DndContext sensors={sensors} collisionDetection={closestCenter} onDragStart={handleDragStart} onDragOver={handleDragOver} onDragCancel={handleDragCancel} onDragEnd={handleDragEnd}><SortableContext items={visibleWidgetIds} strategy={rectSortingStrategy}><div className="grid grid-cols-[repeat(24,minmax(0,1fr))] gap-1 sm:gap-2 md:gap-3">{visibleWidgetIds.map(widgetId=>{const widget=DASHBOARD_WIDGET_BY_ID[widgetId];const instance=layout.instances[widgetId];if(!widget||!instance)return null;const spectrum=spectrumByWidgetId[widgetId];const themedWidget=spectrum?{...widget,headerColor:spectrum.headerColor,iconRailColor:spectrum.iconRailColor}:widget;return <SortableWidgetItem key={widgetId} id={widgetId} disabled={!canDragReorder} className={`vt-dash-cell ${instance.collapsed?"is-collapsed":""} ${sizeBucketClassName(instance.size)} ${heightBucketClassName(instance.height)}`}><DeferredDashboardWidget eager={editMode}><WidgetErrorBoundary widgetId={widgetId}><Suspense fallback={null}><WidgetRenderer widget={themedWidget} instance={instance} editMode={editMode} canEdit={editMode} data={data} onNavigate={onNavigate} onToggleCollapse={onToggleCollapse} onCycleSize={onCycleSize} onDecSize={onDecSize} onCycleHeight={onCycleHeight} onDecHeight={onDecHeight} onRemoveWidget={onRemoveWidget} onMoveWidgetUp={(id)=>moveWidgetByStep(id,-1)} onMoveWidgetDown={(id)=>moveWidgetByStep(id,1)} dashboardControls={{editMode,setEditMode,locked:layout.locked,toggleLock:handleToggleLock,openPicker:()=>setPickerOpen(true),resetLayout:handleReset,showAllWidgets:handleShowAllWidgets,applyPreset:applyDashboardPreset,hiddenWidgetCount:layout.hidden.length,totalWidgetCount:DASHBOARD_WIDGET_REGISTRY.length,handleExport,handleImportClick}}/></Suspense></WidgetErrorBoundary></DeferredDashboardWidget></SortableWidgetItem>})}</div></SortableContext></DndContext>
 <WidgetPickerPanel open={pickerOpen} widgets={DASHBOARD_WIDGET_REGISTRY} layout={layout} onClose={()=>setPickerOpen(false)} onToggleWidget={toggleWidgetVisibility}/>{recentlyRemovedId&&<div className="widget-removal-toast" role="status" aria-live="polite"><span>{DASHBOARD_WIDGET_BY_ID[recentlyRemovedId]?.title||"Widget"} removed.</span><button type="button" onClick={()=>{setLayout(prev=>({...prev,hidden:prev.hidden.filter(id=>id!==recentlyRemovedId)}));setRecentlyRemovedId(null)}}>Undo</button><button type="button" aria-label="Dismiss removal message" onClick={()=>setRecentlyRemovedId(null)}>×</button></div>}</div></DashboardBarrier>
}
