import { getDashboardWidgetPaletteColors } from "../../styles/toolboxPalette"
import { assertUniqueIds } from "../../services/registryAssertions"
import { HEIGHT_BUCKET_ORDER, SIZE_BUCKET_ORDER } from "./tokens"
import type {
 DashboardHeightBucket,
 DashboardSizeBucket,
 WidgetDefinition,
 WidgetDefinitionBase,
} from "./types"

type DefaultDashboardSlot = Readonly<{
 id: string
 size: DashboardSizeBucket
 height: DashboardHeightBucket
}>

export const DEFAULT_DASHBOARD_ROWS = [
 // Top row — About VIEWTUBE is deliberately first so a new visitor meets the
 // product through its visual language and creator loop before seeing channel
 // metrics. Channel Overview follows beside it for returning creators.
 [
  { id: "app-verification-explainer", size: "half", height: "medium" },
  { id: "kpi-cluster", size: "half", height: "medium" },
 ],
 [
  { id: "community-post", size: "half", height: "tall" },
  { id: "comment-replier", size: "half", height: "tall" },
 ],
 [
  { id: "consistency-heatmap", size: "quarter", height: "medium" },
  { id: "realtime-performance", size: "quarter", height: "medium" },
  { id: "goals-tracker", size: "quarter", height: "medium" },
  { id: "keyword-engine", size: "quarter", height: "medium" },
 ],
 [
  { id: "daily-oracle", size: "third", height: "xtall" },
  { id: "ask-me", size: "third", height: "xtall" },
  { id: "ai-journal", size: "third", height: "xtall" },
 ],
 [
  { id: "brain-hub", size: "full", height: "xtall" },
 ],
 [
  { id: "next-best-action", size: "full", height: "tall" },
 ],
 [
  { id: "anomaly-radar", size: "half", height: "tall" },
  { id: "opportunity-radar", size: "half", height: "tall" },
 ],
 [
  { id: "content-pipeline", size: "half", height: "tall" },
  { id: "audience-requests", size: "half", height: "tall" },
 ],
 [
  { id: "video-asset-engine", size: "half", height: "tall" },
  { id: "flight-check", size: "half", height: "tall" },
 ],
 [
  { id: "channel-progress", size: "full", height: "medium" },
 ],
 [
  { id: "video-director", size: "full", height: "massive" },
 ],
 [
  { id: "shorts-multiplier", size: "full", height: "massive" },
 ],
 [
  { id: "image-generator", size: "half", height: "xtall" },
  { id: "video-uploader", size: "half", height: "xtall" },
 ],
 [
  { id: "data-edit", size: "half", height: "xtall" },
  { id: "traffic-sources", size: "half", height: "xtall" },
 ],
 [
  { id: "shorts-vs-long", size: "third", height: "medium" },
  { id: "publish-momentum", size: "third", height: "medium" },
  { id: "audience-matrix", size: "third", height: "medium" },
 ],
 [
  { id: "system-micro-stack", size: "quarter", height: "tall" },
  { id: "keyword-overlap-intelligence", size: "half", height: "tall" },
  { id: "retention-sim", size: "quarter", height: "tall" },
 ],
 [
  { id: "upload-scheduler", size: "full", height: "xtall" },
 ],
 [
  { id: "thumb-ai", size: "half", height: "medium" },
  { id: "quick-actions", size: "quarter", height: "medium" },
  { id: "ai-prompt-box", size: "quarter", height: "medium" },
 ],
 [
  { id: "revenue-momentum", size: "third", height: "medium" },
  { id: "title-rewriter", size: "third", height: "medium" },
  { id: "description-editor", size: "third", height: "medium" },
 ],
 [{ id: "hashtag-analyzer", size: "full", height: "medium" }],
] as const satisfies readonly (readonly DefaultDashboardSlot[])[]

const defaultDashboardSlotById = new Map<string, DefaultDashboardSlot>(
 DEFAULT_DASHBOARD_ROWS.flat().map((slot) => [slot.id, slot]),
)

const DASHBOARD_WIDGET_BASE_REGISTRY: WidgetDefinitionBase[] = [
 {
  id: "app-verification-explainer",
  title: "About VIEWTUBE",
  subtitle: "Connected creator system + trust map",
  category: "system",
  defaultSize: "full",
  minSize: "half",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "tall",
  ...getDashboardWidgetPaletteColors(7),
  dependency: ["none"],
  status: "ready",
 },
  {
  id: "kpi-cluster",
  title: "Channel Overview",
  subtitle: "Subscribers, views, hours, revenue, CTR, AVD",
  category: "core",
  defaultSize: "half",
  minSize: "third",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(0),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "channel-overview",
  title: "Social Channels",
  subtitle: "Cross-platform follower counts",
  category: "core",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(1),
  dependency: ["youtube_data_v3"],
  status: "ready",
 },
 {
  id: "mini-calendar",
  title: "Mini Calendar",
  subtitle: "2-week calendar heat",
  category: "core",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(2),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "task-stack",
  title: "Task Stack",
  subtitle: "Today queue",
  category: "core",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(3),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "quick-actions",
  title: "Quick Actions",
  subtitle: "Primary navigation launchers",
  category: "core",
  defaultSize: "full",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(4),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "recent-uploads",
  title: "Recent Uploads",
  subtitle: "Latest 3 videos",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(5),
  dependency: ["youtube_data_v3", "youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "top-performer",
  title: "Top Performer",
  subtitle: "Best view leader",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(6),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "alerts-feed",
  title: "Alerts Feed",
  subtitle: "Operational highlights",
  category: "system",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(7),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "ai-prompt-box",
  title: "AI Prompt Box",
  subtitle: "Fast strategy asks",
  category: "ai",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(8),
  dependency: ["none"],
  status: "prototype",
 },
 {
  id: "revenue-momentum",
  title: "Revenue Momentum",
  subtitle: "4-week pulse",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(9),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "superfan-card",
  title: "Superfan Card",
  subtitle: "Community spotlight",
  category: "community",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(10),
  dependency: ["none"],
  status: "prototype",
 },
 {
  id: "system-micro-stack",
  title: "Settings",
  subtitle: "System, sync & mode controls",
  category: "system",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(11),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "consistency-heatmap",
  title: "Upload Cadence",
  subtitle: "30-day activity heat",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(12),
  dependency: ["youtube_data_v3"],
  status: "ready",
 },
 {
  id: "goals-tracker",
  title: "Goals Tracker",
  subtitle: "Milestones and targets",
  category: "core",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(13),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "alerts-ticker",
  title: "News Ticker",
  subtitle: "Real-time system updates",
  category: "system",
  defaultSize: "full",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(14),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "tag-generator",
  title: "Tag Generator",
  subtitle: "AI SEO tag generator",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(15),
  dependency: ["youtube_data_v3", "gemini_api"],
  status: "ready",
 },
 {
  id: "revenue-chart",
  title: "Revenue Tracker",
  subtitle: "Weekly grouped ad revenue",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(16),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "community-post",
  title: "Community Post",
  subtitle: "Draft and create posts",
  category: "creation",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(17),
  dependency: ["youtube_data_v3", "gemini_api"],
  status: "ready",
 },
 {
  id: "thumb-ai",
  title: "Thumb AI",
  subtitle: "Generate and analyze thumbnails",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(18),
  dependency: ["gemini_api"],
  status: "ready",
 },
 {
  id: "description-editor",
  title: "Description Editor",
  subtitle: "Write and template video descriptions",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(19),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "realtime-performance",
  title: "Realtime",
  subtitle: "Stats from last 48hr and 60m",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(20),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "keyword-engine",
  title: "Keyword Engine",
  subtitle: "Top keywords by view yield",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(21),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "keyword-overlap-intelligence",
  title: "Keyword Overlap",
  subtitle: "Venn map of title keyword value",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(22),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "publish-momentum",
  title: "Published Momentum",
  subtitle: "2D Heatmap of publish times",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(23),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "traffic-sources",
  title: "Traffic Sources",
  subtitle: "Origin of viewership",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(24),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "audience-retention",
  title: "Retention Dip",
  subtitle: "Audience hold graph",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(25),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "shorts-vs-long",
  title: "Long vs Short",
  subtitle: "Shorts vs Long comparative",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(26),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "comment-replier",
  title: "Comment Responder",
  subtitle: "View, reply & provoke engagement",
  category: "community",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(27),
  dependency: ["youtube_data_v3", "gemini_api"],
  status: "ready",
 },
 {
  id: "reach-funnel",
  title: "Reach Funnel",
  subtitle: "Impressions to CTR conversion",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(28),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "relative-retention-benchmark",
  title: "Algo Benchmark",
  subtitle: "Relative performance vs Platform",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(29),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "ad-stack-intelligence",
  title: "The Ad Stack",
  subtitle: "Gross Rev, Monetized Playbacks, CPM",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(30),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "audience-matrix",
  title: "Audience Matrix",
  subtitle: "Geo, Devices, Traffic, & Sharing",
  category: "community",
  defaultSize: "full",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(31),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "bridge-efficiency",
  title: "Bridge Efficiency",
  subtitle: "Impression to Interaction Funnel",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(32),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "ask-me",
  title: "Ask Me",
  subtitle: "AI Q&A Chat",
  category: "ai",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(33),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "daily-oracle",
  title: "Daily Oracle",
  subtitle: "Evidence-ranked next action",
  category: "ai",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(34),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "flight-check",
  title: "Publishing Command",
  subtitle: "Canonical preflight, readiness and launch control",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(35),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "image-generator",
  title: "Image Generator",
  subtitle: "Thumbnail + end screen image generation",
  category: "creation",
  defaultSize: "half",
  minSize: "third",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "medium",
  maxHeight: "massive",
  ...getDashboardWidgetPaletteColors(36),
  dependency: ["gemini_api"],
  status: "ready",
 },
 {
  id: "video-uploader",
  title: "Video Uploader",
  subtitle: "Upload and publish a new video",
  category: "creation",
  defaultSize: "half",
  minSize: "third",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "medium",
  maxHeight: "massive",
  ...getDashboardWidgetPaletteColors(37),
  dependency: ["youtube_data_v3"],
  status: "ready",
 },
 {
  id: "data-edit",
  title: "Video Manager",
  subtitle: "Edit published video metadata",
  category: "creation",
  defaultSize: "half",
  minSize: "third",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "medium",
  maxHeight: "massive",
  ...getDashboardWidgetPaletteColors(37),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "title-rewriter",
  title: "Title Rewriter",
  subtitle: "AI title alternatives",
  category: "creation",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(38),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "retention-sim",
  title: "Retention Simulator",
  subtitle: "Analyze danger zones",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(39),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "upload-scheduler",
  title: "Upload Scheduler",
  subtitle: "7-day content planner",
  category: "creation",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(40),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "hashtag-analyzer",
  title: "Hashtag Analyzer",
  subtitle: "Tag reach and competition",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(41),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "burnout-monitor",
  title: "Burnout Monitor",
  subtitle: "Health and pacing tracker",
  category: "system",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(42),
  dependency: ["none"],
  status: "ready",
 },
  {
   id: "collab-matchmaker",
   title: "Collab Matchmaker",
   subtitle: "Find peers and generate pitches",
   category: "community",
   defaultSize: "half",
   minSize: "quarter",
   maxSize: "full",
   defaultHeight: "medium",
   minHeight: "short",
   maxHeight: "xtall",
   ...getDashboardWidgetPaletteColors(43),
   dependency: ["gemini_api", "youtube_data_v3"],
   status: "ready",
  },
  {
    id: "ai-journal",
    title: "AI Journal",
    subtitle: "Creator vision & the pulse",
    category: "ai",
    defaultSize: "third",
    minSize: "quarter",
    maxSize: "full",
    defaultHeight: "xtall",
    minHeight: "short",
    maxHeight: "xtall",
    ...getDashboardWidgetPaletteColors(44),
    dependency: ["gemini_api"],
    status: "ready",
  },
  {
    id: "brain-hub",
    title: "Brain Hub",
    subtitle: "AI Memory & OODA Directive",
    category: "ai",
    defaultSize: "half",
    minSize: "quarter",
    maxSize: "full",
    defaultHeight: "xtall",
    minHeight: "short",
    maxHeight: "xtall",
    ...getDashboardWidgetPaletteColors(45),
    dependency: ["none"],
    status: "ready",
  },
  {
   id: "ui-reference-library",
   title: "UI Reference Library",
   subtitle: "Component library and scrollbar styles",
   category: "system",
   defaultSize: "half",
   minSize: "quarter",
   maxSize: "full",
   defaultHeight: "massive",
   minHeight: "medium",
   maxHeight: "massive",
   ...getDashboardWidgetPaletteColors(7),
   dependency: ["none"],
   status: "ready",
  },
  {
    id: "video-autopsy",
    title: "Video Autopsy",
    subtitle: "Deep performance diagnosis",
    category: "analytics",
    defaultSize: "half",
    minSize: "third",
    maxSize: "full",
    defaultHeight: "xtall",
    minHeight: "medium",
    maxHeight: "massive",
    headerColor: "#FF1744",
    iconRailColor: "#C9F830",
    dependency: ["youtube_analytics_v2", "gemini_api"],
    status: "ready",
  },
 {
  id: "ab-thumbnail",
  title: "A/B Thumbnail Test",
  subtitle: "AI-favored thumbnail variant comparison",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(46),
  dependency: ["youtube_data_v3", "gemini_api"],
  status: "ready",
 },
 {
  id: "algo-benchmark",
  title: "Algorithm Benchmark",
  subtitle: "Channel pace against the algorithm curve",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "half",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "tall",
  ...getDashboardWidgetPaletteColors(47),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "cpm-geo",
  title: "CPM by Geography",
  subtitle: "Top-earning territories by CPM",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "half",
  defaultHeight: "short",
  minHeight: "short",
  maxHeight: "medium",
  ...getDashboardWidgetPaletteColors(48),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "device-matrix",
  title: "Device Matrix",
  subtitle: "Mobile versus desktop viewing split",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "half",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "tall",
  ...getDashboardWidgetPaletteColors(49),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "guest-ratio",
  title: "Guest Ratio",
  subtitle: "Subscriber-to-guest viewer ratio",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "half",
  defaultHeight: "short",
  minHeight: "short",
  maxHeight: "medium",
  ...getDashboardWidgetPaletteColors(50),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "playback-origins",
  title: "Playback Origins",
  subtitle: "Search, browse and suggested traffic origins",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "tall",
  ...getDashboardWidgetPaletteColors(51),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "premium-pulse",
  title: "Premium Pulse",
  subtitle: "YouTube Premium engagement and member signal",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "half",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "tall",
  ...getDashboardWidgetPaletteColors(52),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "sharing-dna",
  title: "Sharing DNA",
  subtitle: "Where viewers share your videos",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "half",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "tall",
  ...getDashboardWidgetPaletteColors(53),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "video-comment-operator",
  title: "Video Comment Operator",
  subtitle: "Per-video comment operations console",
  category: "community",
  defaultSize: "half",
  minSize: "third",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "medium",
  maxHeight: "massive",
  ...getDashboardWidgetPaletteColors(54),
  dependency: ["youtube_data_v3"],
  status: "ready",
 },
]

export const SUPPORTED_DASHBOARD_WIDGET_IDS = DEFAULT_DASHBOARD_ROWS
 .flat()
 .map((slot) => slot.id)

const supportedOrder = new Map<string, number>(
 SUPPORTED_DASHBOARD_WIDGET_IDS.map((widgetId, index) => [widgetId, index]),
)

const inclusiveBucketRange = <T extends string>(
 order: readonly T[],
 minimum: T,
 maximum: T,
): readonly T[] => {
 const minIndex = Math.max(0, order.indexOf(minimum))
 const maxIndex = Math.max(minIndex, order.indexOf(maximum))
 return order.slice(minIndex, maxIndex + 1)
}

export const DASHBOARD_WIDGET_REGISTRY: WidgetDefinition[] = DASHBOARD_WIDGET_BASE_REGISTRY.map(
 (widget, index) => {
  const defaultSlot = defaultDashboardSlotById.get(widget.id)
  const supportedSizes = inclusiveBucketRange<DashboardSizeBucket>(
   SIZE_BUCKET_ORDER,
   widget.minSize,
   widget.maxSize,
  )
  const supportedHeights = inclusiveBucketRange<DashboardHeightBucket>(
   HEIGHT_BUCKET_ORDER,
   widget.minHeight,
   widget.maxHeight,
  )
  return {
   ...widget,
   defaultSize: defaultSlot?.size ?? widget.defaultSize,
   defaultHeight: defaultSlot?.height ?? widget.defaultHeight,
   rendererKey: widget.id,
   releaseTier: supportedOrder.has(widget.id) ? "supported" : "preview",
   defaultVisible: supportedOrder.has(widget.id),
   defaultOrder: supportedOrder.get(widget.id) ?? SUPPORTED_DASHBOARD_WIDGET_IDS.length + index,
   supportedSizes,
   supportedHeights,
   supportedDimensions: supportedSizes.flatMap((size) =>
    supportedHeights.map((height) => ({ size, height })),
   ),
   responsiveMode: supportedOrder.has(widget.id) ? "container" : "legacy",
  }
 },
)

if (import.meta.env.DEV) {
 assertUniqueIds(DASHBOARD_WIDGET_REGISTRY, (widget) => widget.id, "Dashboard widget registry")
}

export const DEFAULT_DASHBOARD_WIDGET_ORDER = [...DASHBOARD_WIDGET_REGISTRY]
 .sort((left, right) => left.defaultOrder - right.defaultOrder)
 .map((widget) => widget.id)

export const DASHBOARD_WIDGET_BY_ID = Object.fromEntries(
 DASHBOARD_WIDGET_REGISTRY.map((widget) => [widget.id, widget]),
)

export const WIDGET_DESCRIPTIONS: Record<string, { short: string, detailed: string }> = {
  "app-verification-explainer": {
   short: "MEET VIEWTUBE THROUGH ITS COLOR, CREATOR LOOP, TOOLS, AND TRUST MODEL.",
   detailed: "The first-visit system map showcases the ViewTube spectrum and creator loop while opening Sync, Brain, Studio, and Projects directly; Trust exposes connection, account, privacy, and data controls."
  },
  "kpi-cluster": {
   short: "REAL-TIME CHANNEL VITALS AND CORE GROWTH METRICS.",
   detailed: "Monitor subscribers, views, and revenue in a dense, at-a-glance cluster. Best used for high-level health checks."
  },
  "channel-overview": {
   short: "HIGH-LEVEL SUMMARY OF YOUR CHANNEL'S 28-DAY PERFORMANCE.",
   detailed: "A holistic view of your channel's reach and engagement. Use this to identify long-term trends and seasonality."
  },
  "realtime-performance": {
   short: "MONITOR LIVE CONCURRENT VIEWERS AND TRAFFIC VELOCITY.",
   detailed: "See exactly who is watching and where they come from in real time. Perfect for monitoring the first 48 hours of a launch."
  },
  "alerts-feed": {
   short: "INSTANT NOTIFICATIONS FOR MILESTONES AND CRITICAL EVENTS.",
   detailed: "Stay updated on major subscriber jumps, revenue spikes, or policy alerts. Check daily to catch urgent channel changes."
  },
  "system-micro-stack": {
   short: "DASHBOARD CONTROL SWITCHBOARD FOR LAYOUT, DATA, AI AND ACCOUNT STATE.",
   detailed: "Page through compact Dashboard, Data, AI and Account controls, inspect readiness, apply layout presets, manage widget visibility, sync channel data, and open deeper settings without leaving the dashboard."
  },
  "recent-uploads": {
   short: "PERFORMANCE AUDIT OF YOUR MOST RECENT VIDEO RELEASES.",
   detailed: "Compare your latest videos side-by-side. Use this to spot which topics or thumbnails are currently resonating."
  },
  "consistency-heatmap": {
   short: "VISUALIZE YOUR POSTING FREQUENCY AND CONSISTENCY.",
   detailed: "A calendar-style heat map of your uploads. Use it to ensure you aren't leaving gaps that hurt algorithmic reach."
  },
  "task-stack": {
   short: "TODO LIST FOR PRODUCTION MILESTONES AND CREATIVE GOALS.",
   detailed: "Manage your production pipeline from ideation to publish. Best used to keep track of multiple edits simultaneously."
  },
  "community-post": {
   short: "AI-POWERED GENERATOR FOR ENGAGING COMMUNITY UPDATES.",
   detailed: "Draft polls, images, and text posts optimized for reach. Best used to prime the algorithm between major video uploads."
  },
  "description-editor": {
   short: "STANDARDIZE AND REFINE YOUR VIDEO METADATA AT SCALE.",
   detailed: "Bulk edit or template your descriptions with SEO-ready blocks. Use snippets to keep your links and socials consistent."
  },
  "tag-generator": {
   short: "AI-EXTRACTED KEYWORD CLUSTERS FOR MAXIMUM SEO REACH.",
   detailed: "Generate high-ranking tags based on your video content. Best used to discover niche keywords you might have missed."
  },
  "thumb-ai": {
   short: "AI-DRIVEN THUMBNAIL ANALYSIS AND VARIATION GENERATOR.",
   detailed: "Evaluate thumbnail CTR potential and generate variations. Use it to test different emotional hooks before you publish."
  },
  "top-performer": {
   short: "DEEP DIVE INTO THE VIDEOS DRIVING YOUR CHANNEL GROWTH.",
   detailed: "Analyze your #1 videos to find the 'secret sauce' of their success. Replicate these patterns in your future content."
  },
  "revenue-momentum": {
   short: "ANALYZE EARNING VELOCITY AND FUTURE REVENUE PROJECTIONS.",
   detailed: "Track how fast you're making money and where it peaks. Use this to plan high-budget productions around revenue spikes."
  },
  "revenue-chart": {
   short: "DETAILED DAILY BREAKDOWN OF YOUR CHANNEL'S EARNINGS.",
   detailed: "A granular chart of your RPM, CPM, and total revenue. Best used to track the impact of ad-friendly content shifts."
  },
  "keyword-engine": {
   short: "SEARCH VOLUME AND COMPETITION ANALYSIS FOR NEW TOPICS.",
   detailed: "Find what viewers are searching for before you hit record. Use it to pick high-demand, low-competition video ideas."
  },
  "traffic-sources": {
   short: "MAP WHERE YOUR VIEWERS ARE DISCOVERING YOUR CONTENT.",
   detailed: "Identify if your views come from Search, Suggested, or External. Use this to tailor your titles for specific surfaces."
  },
  "audience-retention": {
   short: "DIAGNOSE EXACTLY WHERE VIEWERS STOP WATCHING VIDEOS.",
   detailed: "View second-by-second drop-off points. Use these insights to fix pacing issues and improve your video hooks."
  },
  "shorts-vs-long": {
   short: "COMPARE PERFORMANCE ACROSS DIFFERENT VIDEO FORMATS.",
   detailed: "Analyze which format drives more subs vs more revenue. Use this to balance your content strategy for maximum growth."
  },
  "superfan-card": {
   short: "IDENTIFY AND REWARD YOUR MOST LOYAL COMMUNITY MEMBERS.",
   detailed: "Track your top 10% of commenters and subscribers. Use this to engage directly with your most valuable 'inner circle.'"
  },
  "comment-replier": {
   short: "AI-ASSISTED REPLIES TO BOOST ENGAGEMENT AND RETENTION.",
   detailed: "Craft provocative, algorithm-priming replies to comments. Use it to spark longer conversations in your comment section."
  },
  "ai-prompt-box": {
   short: "DIRECT COMMAND LINE FOR CHANNEL-WIDE AI OPERATIONS.",
   detailed: "Execute complex data queries or content tasks via text. Best used for advanced batch-processing or deep data analysis."
  },
  "ask-me": {
   short: "NATURAL LANGUAGE CHAT FOR INSTANT CHANNEL INSIGHTS.",
   detailed: "Ask anything about your data and get an immediate answer. Best used for 'Why?' questions that charts can't explain."
  },
  "daily-oracle": {
   short: "RANK TODAY'S HIGHEST-LEVERAGE MOVE, COMPLETE IT, AND BUILD A DAILY STREAK.",
   detailed: "The Oracle combines Brain context, goals, evidence, cadence, effort, and a selected growth lens into one primary move plus quick wins. Complete the large daily task control to reveal the monthly completion calendar, current streak, best streak, and total completed days."
  },
  "ai-journal": {
   short: "CREATIVE LOG FOR TRACKING EXPERIMENTS AND STRATEGIES.",
   detailed: "Document what works and what doesn't in your content journey. Best used to build a personalized 'Creator Playbook.'"
  },
  "mini-calendar": {
   short: "PRODUCTION SCHEDULE AND UPCOMING MILESTONE TRACKER.",
   detailed: "A compact view of your upcoming tasks and deadlines. Use it to plan your week and avoid production bottlenecks."
  },
  "quick-actions": {
   short: "PRIMARY NAVIGATION LAUNCHERS FOR CORE TOOLS.",
   detailed: "Quickly jump to the most common dashboard surfaces. Use this as your home base for navigating the ViewTube ecosystem."
  },
  "goals-tracker": {
   short: "TRACK PROGRESS TOWARDS YOUR CHANNEL MILESTONES.",
   detailed: "Set and monitor goals for subscribers, views, or revenue. Use it to stay motivated and hit your growth targets."
  },
  "alerts-ticker": {
   short: "REAL-TIME TICKER OF CRITICAL CHANNEL EVENTS.",
   detailed: "A scrolling feed of live alerts and performance spikes. Keep an eye on this for immediate algorithmic signals."
  },
  "publish-momentum": {
   short: "HEATMAP ANALYSIS OF OPTIMAL PUBLISH TIMES.",
   detailed: "Visualize when your audience is most active. Use this to time your uploads for maximum initial velocity."
  },
  "reach-funnel": {
   short: "VISUALIZE YOUR CTR CONVERSION AND REACH EFFICIENCY.",
   detailed: "Track how impressions turn into views and watch time. Use this to identify if your titles or thumbnails are leaking traffic."
  },
  "relative-retention-benchmark": {
   short: "BENCHMARK YOUR PERFORMANCE AGAINST PLATFORM AVERAGES.",
   detailed: "See how your video retention compares to similar channels. Use this to understand if you are beating the algorithm's expectations."
  },
  "ad-stack-intelligence": {
   short: "ADVANCED MONETIZATION AND CPM ANALYSIS.",
   detailed: "Deep dive into your ad performance and monetized playbacks. Use this to optimize your content for higher-paying demographics."
  },
  "audience-matrix": {
   short: "MULTI-DIMENSIONAL VIEW OF YOUR VIEWERSHIP.",
   detailed: "Analyze geo, device, and sharing data in a unified matrix. Use this to identify new international or mobile-first growth opportunities."
  },
  "bridge-efficiency": {
   short: "MEASURE THE IMPACT OF CROSS-VIDEO PROMOTION.",
   detailed: "Track how well your end screens and cards convert viewers. Use this to build a 'bridge' that keeps viewers on your channel."
  },
  "flight-check": {
   short: "CANONICAL PREFLIGHT, READINESS AND LAUNCH CONTROL.",
   detailed: "Ensure every video has optimal SEO, links, and settings before going live. Use this as a final safety net for every release."
  },
  "data-edit": {
   short: "EDIT PUBLISHED VIDEO METADATA AND MONETIZATION SETTINGS.",
   detailed: "Select a published video, review its thumbnail, then update its title, description, tags, metadata, and ad suitability settings."
  },
  "video-uploader": {
   short: "UPLOAD AND PUBLISH A NEW VIDEO.",
   detailed: "Choose a source video and thumbnail, prepare metadata and publishing options, complete ad suitability, then publish."
  },
  "image-generator": {
   short: "GENERATE THUMBNAIL + END SCREEN IMAGES WITH AI.",
   detailed: "Create images with style controls and send outputs directly to Community Post, Comment Responder, Thumb AI, and Video Manager."
  },
  "title-rewriter": {
   short: "AI-POWERED TITLE VARIATIONS AND CTR OPTIMIZATION.",
   detailed: "Generate dozens of title alternatives based on your video's core hook. Use this to test different angles before settling on a winner."
  },
  "retention-sim": {
   short: "SIMULATE VIEWERSHIP BEHAVIOR AND PREDICT DROPOFF.",
   detailed: "Analyze potential 'danger zones' in your video's pacing. Use this during the edit to cut out boring segments before you publish."
  },
  "upload-scheduler": {
   short: "7-DAY CONTENT PLANNER AND UPLOAD QUEUE.",
   detailed: "Map out your next week of content and schedule your drops. Use this to maintain a consistent rhythm without the stress."
  },
  "hashtag-analyzer": {
   short: "DEEP ANALYSIS OF HASHTAG REACH AND COMPETITION.",
   detailed: "See which hashtags are trending and which are oversaturated. Use this to pick the perfect set of 3 tags for every video."
  },
  "burnout-monitor": {
   short: "PACING TRACKER TO ENSURE CREATIVE LONGEVITY.",
   detailed: "Monitor your output vs your recovery time. Use this to avoid 'creator burnout' by identifying when you need a break."
  },
  "collab-matchmaker": {
   short: "FIND PEERS AND GENERATE COLLAB PITCHES.",
   detailed: "Discover creators with similar audiences and get AI-drafted reach-out scripts. Use this to grow your community through partnership."
  },
  "brain-hub": {
   short: "YOUR AI BRAIN'S MEMORY, DIRECTIVES, AND STRATEGIC ADVICE.",
   detailed: "View the Brain's evolved understanding of your channel identity, content DNA, performance, and goals. Trigger reflection cycles to update the Brain's strategic OODA directive."
  },
 };
