import React from "react"
import { FileText, MessageSquareText, MessagesSquare, Radar, ScanSearch, Users } from "lucide-react"
import InternalSuperToolWorkbench, {
 type InternalToolProps,
 type InternalWorkbenchConfig,
} from "./supertools/InternalSuperToolWorkbench"

const config: InternalWorkbenchConfig = {
 toolId: "audience-loop-studio",
 toolNumber: "02",
 title: "Audience Loop Studio",
 subtitle:
  "Convert comments, requests, objections, and community signals into reply systems, content demand maps, and Brain learning.",
 railTitle: "Audience Feedback Layer",
 railSubtitle: "Comment response, sentiment grouping, community prompts, request mining",
 railNote:
  "This tool owns creator-audience feedback operations. Analytics informs it, but it should not become a generic analytics dashboard.",
 accentClassName: "bg-[#FFEA5A]",
 heroShadowClassName: "shadow-[12px_12px_0px_0px_#FFEA5A]",
 modeLabel: "Audience mode",
 sourceLabel: "Audience source",
 sourcePlaceholder: "Comment thread, recurring request, poll result, or community topic",
 objectiveLabel: "Response objective",
 objectivePlaceholder: "Increase replies, mine requests, calm confusion, or seed the next video",
 notesLabel: "Tone and moderation notes",
 notesPlaceholder: "Tone, response guardrails, repeat objections, and which asks should become content prompts",
 modules: [
  {
   id: "comment-stream",
   title: "Comment Stream",
   body: "Captures direct audience language, repeated questions, sentiment clusters, and unresolved friction points.",
   purpose: "Capture direct audience language, repeated questions, sentiment clues, and unresolved friction points.",
   controls: ["source thread", "sample size", "language", "moderation filter"],
   outputKind: "comment evidence packet",
   integrations: ["YouTube comments", "Brain context", "Vault notes"],
   selfImprovementSignal: "records unavailable comments and language coverage gaps",
   tone: "bg-[#FFEA5A]",
   icon: MessageSquareText,
  },
  {
   id: "sentiment-clusterer",
   title: "Sentiment Clusterer",
   body: "Groups praise, confusion, objections, and requests into evidence-ranked audience patterns.",
   purpose: "Group praise, confusion, objections, and requests into evidence-ranked audience patterns.",
   controls: ["cluster type", "confidence", "examples", "outlier flag"],
   outputKind: "sentiment cluster map",
   integrations: ["Brain memory", "Performance Hub", "Creator Canvas"],
   selfImprovementSignal: "tracks whether clusters become useful content or reply actions",
   tone: "bg-[#CCFF00]",
   icon: Radar,
  },
  {
   id: "reply-drafting",
   title: "Reply Drafting",
   body: "Builds creator-voiced response approaches instead of bland one-off AI answers.",
   purpose: "Build creator-voiced response approaches with moderation boundaries and escalation labels.",
   controls: ["tone", "reply goal", "risk level", "creator voice"],
   outputKind: "reply draft set",
   integrations: ["Brain style", "Comment Stream", "Workflow Chain"],
   selfImprovementSignal: "learns which reply tone was accepted or edited",
   tone: "bg-[#00F0FF]",
   icon: MessagesSquare,
  },
  {
   id: "community-post-studio",
   title: "Community Post Studio",
   body: "Turns audience heat into polls, teaser posts, and conversation loops that feed the Brain back with better intent data.",
   purpose: "Turn audience heat into polls, teaser posts, and conversation loops that produce better intent data.",
   controls: ["post type", "question style", "CTA", "publish window"],
   outputKind: "community post packet",
   integrations: ["Publishing Schedule", "Brain signals", "Project Command"],
   selfImprovementSignal: "records which post prompts should be tested against response quality",
   tone: "bg-[#FF4FD8] text-white",
   icon: Users,
  },
  {
   id: "request-miner",
   title: "Request Miner",
   body: "Finds sequel opportunities, clarifications, and repeat content demand hiding inside audience chatter.",
   purpose: "Find sequel opportunities, clarifications, and repeat content demand hiding inside audience chatter.",
   controls: ["minimum repeats", "request category", "sequel fit", "urgency"],
   outputKind: "audience request backlog",
   integrations: ["Creator Canvas", "Series Generator", "Project Command"],
   selfImprovementSignal: "compares mined requests with creator-selected next work",
   tone: "bg-[#CCFF00]",
   icon: ScanSearch,
  },
 {
  id: "feedback-provenance",
   title: "Feedback Provenance",
   body: "Keeps audience-derived recommendations tied to comment samples, confidence, skipped scopes, and next-agent notes.",
   purpose: "Keep audience-derived recommendations tied to comment samples, confidence, skipped scopes, and next-agent notes.",
   controls: ["sample source", "confidence", "skipped comments", "next agent note"],
   outputKind: "feedback provenance strip",
   integrations: ["GenerationRecord", "Brain signal", "Vault artifact"],
   selfImprovementSignal: "prevents audience claims without visible comment evidence",
   tone: "bg-[#FFEA5A]",
  icon: FileText,
  },
 ],
 prototype: {
  toolId: "audience-loop-studio",
  title: "Audience Loop Prototype",
  description: "Early operator layout for comment review, sentiment grouping, replies, requests, and community drafts.",
  lanes: [
   { id: "comment-stream", title: "Comment Stream", description: "Direct audience language", tone: "bg-[#FFEA5A]" },
   { id: "sentiment-clusters", title: "Sentiment Clusters", description: "Praise, confusion, objections, requests", tone: "bg-[#CCFF00]" },
   { id: "reply-queue", title: "Reply Draft Queue", description: "Creator-voice responses", tone: "bg-[#00F0FF]" },
   { id: "request-miner", title: "Request Miner", description: "Next-video demand signals", tone: "bg-[#FF4FD8] text-white" },
   { id: "community-drafts", title: "Community Post Drafts", description: "Polls, prompts, and follow-ups", tone: "bg-[#FFEA5A]" },
  ],
  cards: [
   {
    id: "comment-repeat-question",
    laneId: "comment-stream",
    title: "Repeated workflow question",
    summary: "Sample thread suggests viewers want a clearer follow-up tutorial.",
    owner: "Audience",
    status: "queued",
    priority: "high",
    chips: ["english comments", "repeat ask"],
    controls: ["sample size", "language"],
    output: "comment evidence packet",
    integrations: ["YouTube comments", "Brain context"],
    handoffTarget: "Request Miner",
   },
   {
    id: "cluster-confusion",
    laneId: "sentiment-clusters",
    title: "Setup confusion cluster",
    summary: "Multiple viewers ask where the setup step starts and what file is required.",
    status: "active",
    priority: "medium",
    chips: ["confusion", "documentation gap"],
    controls: ["confidence", "examples"],
    output: "sentiment cluster map",
    integrations: ["Brain memory", "Creator Canvas"],
    handoffTarget: "Reply Drafting",
   },
   {
    id: "reply-creator-voice",
    laneId: "reply-queue",
    title: "Creator-voice clarification",
    summary: "Draft a warm, specific reply that answers the repeated setup confusion.",
    status: "active",
    priority: "medium",
    chips: ["reply draft", "tone guardrail"],
    controls: ["tone", "risk level"],
    output: "reply draft set",
    integrations: ["Workflow Chain"],
    handoffTarget: "Community Post Studio",
   },
   {
    id: "request-sequel",
    laneId: "request-miner",
    title: "Sequel demand",
    summary: "Convert repeated setup questions into a candidate follow-up video.",
    status: "ready",
    priority: "high",
    chips: ["sequel", "audience demand"],
    controls: ["minimum repeats", "urgency"],
    output: "audience request backlog",
    integrations: ["Creator Canvas", "Project Command"],
    handoffTarget: "Creator Canvas",
   },
   {
    id: "community-poll",
    laneId: "community-drafts",
    title: "Poll the next tutorial",
    summary: "Ask the audience which setup blocker should be solved first.",
    status: "queued",
    priority: "medium",
    chips: ["poll", "follow-up"],
    controls: ["post type", "publish window"],
    output: "community post packet",
    integrations: ["Publishing Schedule", "Brain signals"],
    handoffTarget: "Publishing Schedule",
   },
  ],
  controls: ["select comment signal", "cluster sentiment", "draft reply", "promote request"],
  evidence: ["comment sample", "reply history", "language coverage", "skipped scopes visible"],
  handoffTargets: ["Creator Canvas", "Project Command", "Brain Command"],
 },
 modes: [
  { id: "reply", label: "Reply Queue", description: "Focus on creator-facing responses and high-leverage conversation cleanup." },
  { id: "mining", label: "Request Mining", description: "Extract the next ideas, objections, and sequel opportunities from comments." },
  { id: "community", label: "Community Prompting", description: "Use the audience loop to build new posts, polls, and follow-up asks." },
 ],
 metrics: [
  { label: "Owns", value: "Comments, replies, requests", icon: MessageSquareText, tone: "bg-[#FFEA5A]" },
  { label: "Feeds", value: "Creator Canvas + Brain", icon: ScanSearch, tone: "bg-[#CCFF00]" },
  { label: "Protects", value: "Tone and moderation lane", icon: Users, tone: "bg-[#00F0FF]" },
  { label: "Boundary", value: "Not a second chat app", icon: MessagesSquare, tone: "bg-[#FF4FD8] text-white" },
 ],
 sisterToolIds: [
  "audience-loop-studio",
  "creator-canvas-os",
  "brain-command-center",
  "project-command-kanban",
  "retention-autopsy-experiment-engine",
 ],
 outputLanes: [
  { label: "Input", value: "Comments, requests, polls, confusion, praise, objections" },
  { label: "Output", value: "Reply drafts, mined requests, community post prompts, audience themes" },
  { label: "Handoff", value: "Idea generation, workflow follow-up, Brain memory updates" },
 ],
 buildPacket: ({ source, objective, notes, mode, brainContext, workflowCount }) => ({
  title: source || "Audience Loop Packet",
  summary: `Built ${mode.label.toLowerCase()} packet for ${source || "audience feedback"} and prepared reply, request-mining, and Brain handoff outputs.`,
  packet: {
   ownership: "comment intelligence, reply direction, audience request mining, community prompts",
   mode: mode.label,
   source: source || "General audience feedback",
   objective: objective || "Clarify audience demand and creator response strategy",
   creatorNotes: notes || "No extra moderation notes provided.",
   audienceLoop: {
    askToCapture: "What is the audience repeatedly asking for or misunderstanding?",
    replyGuardrail: "Respond in creator voice and preserve brand tone.",
    nextContentHook: "Promote only the strongest repeat request into a next-video input.",
   },
   brainSignals: {
    strategicAdvice: brainContext?.strategicAdvice || null,
    audienceMemoryHint: brainContext?.toolContextPack?.summary || null,
   },
   deliverables: [
    "reply stance",
    "repeat request list",
    "community post angle",
    "Brain-ready audience signal summary",
   ],
   workflowCount,
  },
  workflowTitle: `${source || "Audience"} feedback chain`,
  workflowGoal: "Turn audience feedback into response actions, future content inputs, and explicit Brain learning.",
  workflowSteps: [
   {
    title: "Draft response lane",
    surface: "studio",
    toolId: "audience-loop-studio",
    details: "Define the creator reply strategy and moderation stance.",
   },
   {
    title: "Promote content request",
    surface: "studio",
    toolId: "creator-canvas-os",
    details: "Convert the strongest repeated ask into a concept or sequel seed.",
   },
   {
    title: "Queue follow-up",
    surface: "projects",
    toolId: "project-command-kanban",
    details: "Assign the next audience-facing post or content action.",
   },
   {
    title: "Record audience lesson",
    surface: "brain",
    toolId: "brain-command-center",
    details: "Store what the audience wants, rejects, or keeps repeating.",
   },
  ],
 }),
}

const AudienceLoopStudio: React.FC<InternalToolProps> = (props) => (
 <InternalSuperToolWorkbench config={config} {...props} />
)

export default AudienceLoopStudio
