import React from "react"
import { AlertTriangle, Clapperboard, Film, Gauge, LineChart, Presentation, SplitSquareVertical } from "lucide-react"
import InternalSuperToolWorkbench, {
 type InternalToolProps,
 type InternalWorkbenchConfig,
} from "./supertools/InternalSuperToolWorkbench"

const config: InternalWorkbenchConfig = {
 toolId: "cinematic-analytics-lab",
 toolNumber: "12",
 title: "Cinematic Analytics Lab",
 subtitle:
  "Turn canonical channel metrics into comparative stories, visual contrasts, and explainable creator decision frames.",
 railTitle: "Analytics Storytelling Layer",
 railSubtitle: "Comparative charts, visual narratives, canonical metrics, monetization and audience contrasts",
 railNote:
  "This tool owns analytics storytelling and comparison views. It should not invent new metrics outside the canonical analytics stack.",
 accentClassName: "bg-[#00F0FF]",
 heroShadowClassName: "shadow-[12px_12px_0px_0px_#00F0FF]",
 modeLabel: "Analytics mode",
 sourceLabel: "Comparison target",
 sourcePlaceholder: "Format lane, time window, audience segment, or performance question",
 objectiveLabel: "Insight objective",
 objectivePlaceholder: "Compare formats, surface outliers, explain monetization shifts, or find audience patterns",
 notesLabel: "Analysis notes",
 notesPlaceholder: "Metric focus, segments to compare, confidence caveats, and what action this insight should unlock",
 modules: [
  {
   id: "metric-selector",
   title: "Metric Selector",
   body: "Chooses canonical YouTube metrics, dimensions, and derived formulas without inventing a second analytics truth layer.",
   purpose: "Choose canonical YouTube metrics, dimensions, and derived formulas without inventing a second analytics truth layer.",
   controls: ["metric", "dimension", "date range", "formula"],
   outputKind: "metric request packet",
   integrations: ["Performance Hub", "YouTube Analytics cache", "Brain context"],
   selfImprovementSignal: "records missing or aliased metrics before analysis is trusted",
   tone: "bg-[#00F0FF]",
   icon: Gauge,
  },
  {
   id: "comparison-stage",
   title: "Comparison Stage",
   body: "Frames one metric against format, time, segment, or content-family sets so creators see contrast, not isolated numbers.",
   purpose: "Frame one metric against format, time, segment, or content-family sets so creators see contrast, not isolated numbers.",
   controls: ["comparison set", "baseline", "segment", "outlier rule"],
   outputKind: "comparison view plan",
   integrations: ["Graphs Page", "Retention Autopsy", "Project Command"],
   selfImprovementSignal: "records which comparison produced an actionable decision",
   tone: "bg-[#CCFF00]",
   icon: SplitSquareVertical,
  },
  {
   id: "insight-artifact-builder",
   title: "Insight Artifact Builder",
   body: "Turns the strongest analytical contrast into a reusable insight packet for projects, Brain, and retention follow-up.",
   purpose: "Turn the strongest analytical contrast into a reusable insight packet for projects, Brain, and retention follow-up.",
   controls: ["claim", "evidence", "confidence", "recommended action"],
   outputKind: "insight artifact",
   integrations: ["GenerationRecord", "Vault artifact", "Brain signal"],
   selfImprovementSignal: "checks whether every insight names evidence and confidence",
   tone: "bg-[#FFEA5A]",
   icon: LineChart,
  },
  {
   id: "anomaly-lens",
   title: "Anomaly Lens",
   body: "Flags outliers, missing data, traffic-source shifts, revenue spikes, and format mismatches that need deeper review.",
   purpose: "Flag outliers, missing data, traffic-source shifts, revenue spikes, and format mismatches that need deeper review.",
   controls: ["anomaly type", "threshold", "confidence", "next check"],
   outputKind: "anomaly review packet",
   integrations: ["Performance Hub", "Retention Autopsy", "Brain Command"],
   selfImprovementSignal: "records skipped checks and anomalies that require tomorrow review",
   tone: "bg-[#FF4FD8] text-white",
   icon: AlertTriangle,
  },
 {
  id: "presentation-mode",
   title: "Presentation Mode",
   body: "Formats the insight into creator-readable slides, chart modules, or executive summaries without hiding metric provenance.",
   purpose: "Format the insight into creator-readable slides, chart modules, or executive summaries without hiding metric provenance.",
   controls: ["audience", "chart style", "summary length", "source strip"],
   outputKind: "presentation-ready insight",
   integrations: ["Graphs Page", "Vault", "Brain Command"],
   selfImprovementSignal: "tracks which presentations need clearer source labels",
   tone: "bg-[#00F0FF]",
  icon: Presentation,
  },
 ],
 prototype: {
  toolId: "cinematic-analytics-lab",
  title: "Cinematic Analytics Prototype",
  description: "Early workspace for metric selection, comparisons, anomaly review, insight packets, and presentation output.",
  lanes: [
   { id: "metric-selector", title: "Metric Selector", description: "Canonical metric and dimension choice", tone: "bg-[#00F0FF]" },
   { id: "comparison-stage", title: "Comparison Stage", description: "Format, segment, and baseline contrast", tone: "bg-[#CCFF00]" },
   { id: "anomaly-cards", title: "Anomaly Cards", description: "Traffic, revenue, retention, missing data", tone: "bg-[#FF4FD8] text-white" },
   { id: "insight-preview", title: "Insight Artifact Preview", description: "Claim, evidence, confidence, action", tone: "bg-[#FFEA5A]" },
   { id: "presentation-mode", title: "Presentation Mode", description: "Chart-ready creator summary", tone: "bg-[#00F0FF]" },
  ],
  cards: [
   {
    id: "metric-traffic-source",
    laneId: "metric-selector",
    title: "Traffic source share",
    summary: "Select trafficSourceType and views to explain where discovery is coming from.",
    status: "active",
    priority: "high",
    chips: ["canonical metric", "traffic"],
    controls: ["metric", "dimension"],
    output: "metric request packet",
    integrations: ["Performance Hub", "YouTube Analytics cache"],
    handoffTarget: "Comparison Stage",
   },
   {
    id: "compare-shorts-longform",
    laneId: "comparison-stage",
    title: "Shorts vs long-form",
    summary: "Compare discovery behavior by format before recommending a publishing move.",
    status: "queued",
    priority: "medium",
    chips: ["format", "baseline"],
    controls: ["comparison set", "segment"],
    output: "comparison view plan",
    integrations: ["Graphs Page"],
    handoffTarget: "Insight Artifact",
   },
   {
    id: "anomaly-search-drop",
    laneId: "anomaly-cards",
    title: "Search dependency shift",
    summary: "Flag sudden search traffic drop or missing search term rows for follow-up.",
    status: "blocked",
    priority: "urgent",
    blocker: "Search term enrichment unavailable",
    chips: ["YT_SEARCH", "missing data"],
    controls: ["threshold", "next check"],
    output: "anomaly review packet",
    integrations: ["Brain Command"],
    handoffTarget: "Daily Brief",
   },
   {
    id: "insight-retention-action",
    laneId: "insight-preview",
    title: "Retention-backed insight",
    summary: "Turn one contrast into a clear claim with confidence and recommended action.",
    status: "ready",
    priority: "high",
    chips: ["claim", "confidence"],
    controls: ["evidence", "recommended action"],
    output: "insight artifact",
    integrations: ["Vault artifact", "Brain signal"],
    handoffTarget: "Retention Autopsy",
   },
   {
    id: "presentation-chart",
    laneId: "presentation-mode",
    title: "Creator chart packet",
    summary: "Format the insight as a chart module with visible metric provenance.",
    status: "queued",
    priority: "medium",
    chips: ["source strip", "chart style"],
    controls: ["audience", "summary length"],
    output: "presentation-ready insight",
    integrations: ["Graphs Page", "Vault"],
    handoffTarget: "Project Command",
   },
  ],
  controls: ["select metric", "compare segment", "flag anomaly", "mark ready"],
  evidence: ["canonical metric", "source cache", "comparison set", "confidence"],
  handoffTargets: ["Retention Autopsy", "Project Command", "Brain Command"],
 },
 modes: [
  { id: "format", label: "Format Compare", description: "Contrast formats, lengths, and content families using canonical metrics." },
  { id: "monetization", label: "Monetization Story", description: "Frame revenue and monetization patterns as channel decisions, not raw tables." },
  { id: "audience", label: "Audience Contrast", description: "Compare viewer behavior, loyalty, and segment differences for planning use." },
 ],
 metrics: [
  { label: "Owns", value: "Comparative insight views", icon: SplitSquareVertical, tone: "bg-[#00F0FF]" },
  { label: "Feeds", value: "Retention + Brain + projects", icon: Clapperboard, tone: "bg-[#FF4FD8] text-white" },
  { label: "Uses", value: "Canonical analytics only", icon: LineChart, tone: "bg-[#FFEA5A]" },
  { label: "Boundary", value: "Not a fake metric generator", icon: Film, tone: "bg-[#CCFF00]" },
 ],
 sisterToolIds: [
  "cinematic-analytics-lab",
  "retention-autopsy-experiment-engine",
  "brain-command-center",
  "project-command-kanban",
  "packaging-lab-pro",
 ],
 outputLanes: [
  { label: "Input", value: "Canonical performance data, segments, time windows, format groups" },
  { label: "Output", value: "Comparative views, insight packets, outlier stories, action notes" },
  { label: "Handoff", value: "Retention autopsy, packaging tests, Brain and project actions" },
 ],
 buildPacket: ({ source, objective, notes, mode, brainContext, workflowCount }) => ({
  title: source || "Cinematic Analytics Packet",
  summary: `Built ${mode.label.toLowerCase()} analytics packet for ${source || "a comparison target"} and persisted the resulting insight chain.`,
  packet: {
   ownership: "comparative analytics storytelling, visual insight framing, action-ready contrast views",
   mode: mode.label,
   source: source || "Untitled analytics comparison",
   objective: objective || "Turn canonical metrics into an actionable strategic contrast",
   creatorNotes: notes || "No extra analytics notes provided.",
   analyticsRules: [
    "reuse canonical metrics only",
    "explain contrast before recommending action",
    "promote only durable insights into workflow or Brain memory",
   ],
   brainSignals: {
    strategicAdvice: brainContext?.strategicAdvice || null,
    contextBlock: brainContext?.toolContextPack?.summary || null,
   },
   deliverables: [
    "comparison frame",
    "insight reel",
    "outlier explanation",
    "next action handoff",
   ],
   workflowCount,
  },
  workflowTitle: `${source || "Analytics"} insight chain`,
  workflowGoal: "Turn a canonical analytics question into an explainable insight with clear next actions.",
  workflowSteps: [
   {
    title: "Frame the comparison",
    surface: "analytics",
    toolId: "cinematic-analytics-lab",
    details: "Choose the metric, segment, and comparison set that matters.",
   },
   {
    title: "Escalate retention issue",
    surface: "analytics",
    toolId: "retention-autopsy-experiment-engine",
    details: "Route the insight to retention diagnosis if viewer drop-off or mismatch appears.",
   },
   {
    title: "Convert insight into action",
    surface: "projects",
    toolId: "project-command-kanban",
    details: "Create a task, test, or project move from the strongest finding.",
   },
   {
    title: "Record strategic lesson",
    surface: "brain",
    toolId: "brain-command-center",
    details: "Save the durable learning and confidence boundary in the Brain.",
   },
  ],
 }),
}

const CinematicAnalyticsLab: React.FC<InternalToolProps> = (props) => (
 <InternalSuperToolWorkbench config={config} {...props} />
)

export default CinematicAnalyticsLab
