import React from "react"
import { BadgeCheck, Gauge, Images, ScanSearch, TestTube2, Type } from "lucide-react"
import InternalSuperToolWorkbench, {
 type InternalToolProps,
 type InternalWorkbenchConfig,
} from "./supertools/InternalSuperToolWorkbench"

const config: InternalWorkbenchConfig = {
 toolId: "packaging-lab-pro",
 toolNumber: "03",
 title: "Packaging Lab Pro",
 subtitle:
  "Shape title, thumbnail, description, and packaging experiments with ranking logic and explicit provenance.",
 railTitle: "Packaging Optimization Layer",
 railSubtitle: "Title systems, thumbnail direction, description framing, experiment scoring",
 railNote:
  "This tool owns packaging choices and packaging tests. It should inform analytics and workflow systems, not absorb them.",
 accentClassName: "bg-[#FF4FD8]",
 heroShadowClassName: "shadow-[12px_12px_0px_0px_#FF4FD8]",
 modeLabel: "Packaging mode",
 sourceLabel: "Content target",
 sourcePlaceholder: "Video concept, publish candidate, or underperforming upload",
 objectiveLabel: "Packaging objective",
 objectivePlaceholder: "Raise CTR, clarify promise, improve title specificity, or prep a test",
 notesLabel: "Packaging notes",
 notesPlaceholder: "Core promise, emotional tone, thumbnail subject, proof hook, and constraints",
 modules: [
  {
   id: "title-systems",
   title: "Title Systems",
   body: "Produces high-clarity, high-curiosity title lanes without losing specificity or trust.",
   purpose: "Produce high-clarity, high-curiosity title lanes without losing specificity, trust, or audience fit.",
   controls: ["title pattern", "curiosity level", "specificity", "risk filter"],
   outputKind: "ranked title system",
   integrations: ["Creator Canvas", "Retention Autopsy", "Brain context"],
   selfImprovementSignal: "records which title patterns deserve later CTR validation",
   tone: "bg-[#FF4FD8] text-white",
   icon: Type,
  },
  {
   id: "thumbnail-direction",
   title: "Thumbnail Direction",
   body: "Builds visual direction, subject focus, contrast intent, and emotion framing for the thumbnail layer.",
   purpose: "Build visual direction, subject focus, contrast intent, and emotion framing for the thumbnail layer.",
   controls: ["subject", "emotion", "contrast", "composition"],
   outputKind: "thumbnail direction brief",
   integrations: ["Vault assets", "AI thumbnail generation", "VT_E1"],
   selfImprovementSignal: "tracks visual directions that need asset or performance follow-up",
   tone: "bg-[#FFEA5A]",
   icon: Images,
  },
  {
   id: "description-framing",
   title: "Description Framing",
   body: "Keeps opening description copy, chapters, CTA order, and metadata framing aligned to the chosen promise.",
   purpose: "Keep opening description copy, chapters, CTA order, and metadata framing aligned to the chosen promise.",
   controls: ["first lines", "CTA order", "chapters", "keyword fit"],
   outputKind: "description opener and metadata frame",
   integrations: ["YouTube upload metadata", "Vault notes", "Brain context"],
   selfImprovementSignal: "records missing keywords and description assumptions",
   tone: "bg-[#00F0FF]",
   icon: ScanSearch,
  },
  {
   id: "experiment-batch",
   title: "Experiment Batch",
   body: "Turns packaging alternatives into explicit tests so retention and publish outcomes can be compared later.",
   purpose: "Turn packaging alternatives into explicit tests so retention and publish outcomes can be compared later.",
   controls: ["variant count", "success metric", "test window", "audience segment"],
   outputKind: "packaging experiment batch",
   integrations: ["Project Command", "Retention Autopsy", "Workflow Chain"],
   selfImprovementSignal: "stores hypothesis and metric before the experiment runs",
   tone: "bg-[#CCFF00]",
   icon: TestTube2,
  },
 {
  id: "packaging-scorecard",
   title: "Packaging Scorecard",
   body: "Ranks variants by promise clarity, visual contrast, audience fit, trust risk, and evidence strength.",
   purpose: "Rank variants by promise clarity, visual contrast, audience fit, trust risk, and evidence strength.",
   controls: ["clarity", "contrast", "fit", "risk"],
   outputKind: "evidence-ranked scorecard",
   integrations: ["Cinematic Analytics", "Brain signal", "GenerationRecord"],
   selfImprovementSignal: "compares scorecard confidence with later analytics outcomes",
   tone: "bg-[#FFEA5A]",
  icon: BadgeCheck,
  },
 ],
 prototype: {
  toolId: "packaging-lab-pro",
  title: "Packaging Lab Prototype",
  description: "Early workspace for title variants, thumbnail direction, description openers, experiments, and scorecards.",
  lanes: [
   { id: "title-variants", title: "Title Variant Table", description: "Promise, curiosity, specificity", tone: "bg-[#FF4FD8] text-white" },
   { id: "thumbnail-board", title: "Thumbnail Direction Board", description: "Subject, contrast, emotion", tone: "bg-[#FFEA5A]" },
   { id: "description-editor", title: "Description Opener Editor", description: "First lines, CTA, metadata", tone: "bg-[#00F0FF]" },
   { id: "experiment-batch", title: "Experiment Batch", description: "Variants and success metrics", tone: "bg-[#CCFF00]" },
   { id: "scorecard", title: "Packaging Scorecard", description: "Evidence-ranked final choice", tone: "bg-[#FFEA5A]" },
  ],
  cards: [
   {
    id: "title-specific-promise",
    laneId: "title-variants",
    title: "Specific promise title",
    summary: "Test a title that says the exact outcome instead of broad hype.",
    status: "active",
    priority: "high",
    chips: ["clarity", "trust"],
    controls: ["curiosity level", "specificity"],
    output: "ranked title variant",
    integrations: ["Creator Canvas", "Brain"],
    handoffTarget: "Scorecard",
   },
   {
    id: "thumb-subject-focus",
    laneId: "thumbnail-board",
    title: "Subject-forward thumb",
    summary: "Show the key object and one visual proof cue with high contrast.",
    status: "queued",
    priority: "high",
    chips: ["subject", "contrast"],
    controls: ["composition", "emotion"],
    output: "thumbnail direction brief",
    integrations: ["Vault assets", "AI thumbnail generation"],
    handoffTarget: "Experiment Batch",
   },
   {
    id: "description-opener",
    laneId: "description-editor",
    title: "First three lines",
    summary: "Open with the same promise as the title and thumbnail.",
    status: "queued",
    priority: "medium",
    chips: ["first lines", "keyword fit"],
    controls: ["CTA order", "chapters"],
    output: "description opener",
    integrations: ["Upload metadata"],
    handoffTarget: "Project Command",
   },
   {
    id: "packaging-test",
    laneId: "experiment-batch",
    title: "CTR rescue test",
    summary: "Package two variants against the same retention-backed video.",
    status: "active",
    priority: "urgent",
    chips: ["CTR", "test window"],
    controls: ["variant count", "metric"],
    output: "experiment batch",
    integrations: ["Retention Engine", "Workflow Chain"],
    handoffTarget: "Retention Autopsy",
   },
   {
    id: "scorecard-final",
    laneId: "scorecard",
    title: "Evidence-ranked pick",
    summary: "Rank final packaging by clarity, contrast, fit, risk, and source evidence.",
    status: "ready",
    priority: "high",
    chips: ["confidence", "risk"],
    controls: ["clarity", "contrast", "fit"],
    output: "packaging scorecard",
    integrations: ["GenerationRecord", "Brain signal"],
    handoffTarget: "Publishing Schedule",
   },
  ],
  controls: ["select variant", "move to test", "mark blocked", "mark launch ready"],
  evidence: ["video promise", "thumbnail asset", "CTR clue", "retention clue"],
  handoffTargets: ["Retention Autopsy", "Project Command", "Publishing Schedule"],
 },
 modes: [
  { id: "launch", label: "Launch Packaging", description: "Package a new upload before release with first-click clarity and contrast." },
  { id: "rescue", label: "Underperformer Rescue", description: "Repackage a video that has stronger potential than its current CTR suggests." },
  { id: "test", label: "Experiment Batch", description: "Generate multiple packaging lanes for measured comparison and follow-up." },
 ],
 metrics: [
  { label: "Owns", value: "Titles, thumbs, descriptions", icon: Type, tone: "bg-[#FF4FD8] text-white" },
  { label: "Feeds", value: "Retention + workflow tests", icon: Gauge, tone: "bg-[#CCFF00]" },
  { label: "Input", value: "Idea promise and audience fit", icon: Images, tone: "bg-[#FFEA5A]" },
  { label: "Boundary", value: "Not a generic design board", icon: ScanSearch, tone: "bg-[#00F0FF]" },
 ],
 sisterToolIds: [
  "packaging-lab-pro",
  "creator-canvas-os",
  "retention-autopsy-experiment-engine",
  "project-command-kanban",
  "brain-command-center",
 ],
 outputLanes: [
  { label: "Input", value: "Video promise, thumbnail direction, audience fit, performance clues" },
  { label: "Output", value: "Title sets, thumbnail lanes, description framing, test packets" },
  { label: "Handoff", value: "Experiment scheduling, retention review, publish readiness" },
 ],
 buildPacket: ({ source, objective, notes, mode, brainContext, workflowCount }) => ({
  title: source || "Packaging Packet",
  summary: `Built ${mode.label.toLowerCase()} packet for ${source || "a content candidate"} with persisted ranking and experiment handoff data.`,
  packet: {
   ownership: "titles, thumbnails, descriptions, packaging experiments",
   mode: mode.label,
   source: source || "Untitled publish candidate",
   objective: objective || "Clarify promise and improve first-click conversion",
   creatorNotes: notes || "No extra packaging notes provided.",
   packagingRules: [
    "protect specificity before hype",
    "make thumbnail and title promise the same video",
    "save every experiment as measurable variant work",
   ],
   brainSignals: {
    strategicAdvice: brainContext?.strategicAdvice || null,
    contextBlock: brainContext?.toolContextPack?.summary || null,
   },
   deliverables: [
    "title set",
    "thumbnail lane",
    "description opener",
    "experiment candidate list",
   ],
   workflowCount,
  },
  workflowTitle: `${source || "Packaging"} optimization chain`,
  workflowGoal: "Turn packaging direction into publish-ready variants and measurable tests.",
  workflowSteps: [
   {
    title: "Lock promise",
    surface: "studio",
    toolId: "creator-canvas-os",
    details: "Confirm the actual video promise before packaging variants split.",
   },
   {
    title: "Build packaging variants",
    surface: "studio",
    toolId: "packaging-lab-pro",
    details: "Create title, thumbnail, and description alternatives.",
   },
   {
    title: "Schedule experiment",
    surface: "projects",
    toolId: "project-command-kanban",
    details: "Assign timing, owner, and success criteria for the packaging test.",
   },
   {
    title: "Review retention outcome",
    surface: "analytics",
    toolId: "retention-autopsy-experiment-engine",
    details: "Check whether packaging fixed discovery or exposed deeper content friction.",
   },
  ],
 }),
}

const PackagingLabPro: React.FC<InternalToolProps> = (props) => (
 <InternalSuperToolWorkbench config={config} {...props} />
)

export default PackagingLabPro
