import React from "react"
import { AlertTriangle, Boxes, CalendarClock, CheckSquare, Milestone, Route } from "lucide-react"
import InternalSuperToolWorkbench, {
 type InternalToolProps,
 type InternalWorkbenchConfig,
} from "./supertools/InternalSuperToolWorkbench"

const config: InternalWorkbenchConfig = {
 toolId: "project-command-kanban",
 toolNumber: "04",
 title: "Project Command Kanban",
 subtitle:
  "Own creator project execution with milestones, dependencies, launch state, blockers, and Brain-aware production routing.",
 railTitle: "Projects Command Layer",
 railSubtitle: "Milestones, blockers, ownership, dependencies, launch-state routing",
 railNote:
  "This is the canonical project shell. Scheduling and workflow UI can merge into it, but task ownership should stay here.",
 accentClassName: "bg-[#00F0FF]",
 heroShadowClassName: "shadow-[12px_12px_0px_0px_#00F0FF]",
 modeLabel: "Command mode",
 sourceLabel: "Project or launch target",
 sourcePlaceholder: "Series launch, sponsor video, content sprint, or one-off upload",
 objectiveLabel: "Project objective",
 objectivePlaceholder: "Ship on time, reduce blockers, align assets, or prep a launch stack",
 notesLabel: "Milestones and blockers",
 notesPlaceholder: "Scope, deadlines, collaborator needs, dependencies, and known risks",
 modules: [
  {
   id: "project-board",
   title: "Project Board",
   body: "Tracks the active project state, owners, current lane, and next action before work spreads across tools.",
   purpose: "Track active project state, owners, current lane, and next action before work spreads across tools.",
   controls: ["owner", "status", "priority", "next action"],
   outputKind: "project state card",
   integrations: ["Workflow Chain", "Brain Command", "Vault"],
   selfImprovementSignal: "records ownership gaps and stale next actions",
   tone: "bg-[#00F0FF]",
   icon: Boxes,
  },
  {
   id: "milestones",
   title: "Milestones",
   body: "Defines the production phases that matter: research, script, design, edit, approval, publish, and follow-up.",
   purpose: "Define the production phases that matter: research, script, design, edit, approval, publish, and follow-up.",
   controls: ["phase", "deadline", "owner", "completion signal"],
   outputKind: "milestone map",
   integrations: ["Publishing Schedule", "Workflow Chain", "Creator Canvas"],
   selfImprovementSignal: "tracks which phases repeatedly become blockers",
   tone: "bg-[#00F0FF]",
   icon: Milestone,
  },
  {
   id: "dependencies",
   title: "Dependencies",
   body: "Shows which tasks unlock packaging, VT_E1 work, scheduling, or audience follow-up so projects do not stall invisibly.",
   purpose: "Show which tasks unlock packaging, VT_E1 work, scheduling, or audience follow-up so projects do not stall invisibly.",
   controls: ["blocked by", "unlocks", "required asset", "handoff owner"],
   outputKind: "dependency graph",
   integrations: ["VT_E1", "Packaging Lab", "Vault"],
   selfImprovementSignal: "records hidden dependencies before they become missed handoffs",
   tone: "bg-[#CCFF00]",
   icon: Route,
  },
  {
   id: "blockers",
   title: "Blockers",
   body: "Escalates missing files, decisions, approvals, data, and owner confusion into visible recovery actions.",
   purpose: "Escalate missing files, decisions, approvals, data, and owner confusion into visible recovery actions.",
   controls: ["blocker type", "severity", "owner", "recovery action"],
   outputKind: "blocker recovery packet",
   integrations: ["Brain Command", "Workflow Chain", "Vault"],
   selfImprovementSignal: "records why work stopped and what must change next",
   tone: "bg-[#FF4FD8] text-white",
   icon: AlertTriangle,
  },
  {
   id: "launch-readiness",
   title: "Launch Readiness",
   body: "Keeps publish readiness tied to time, assets, approvals, packaging, and follow-up checks.",
   purpose: "Keep publish readiness tied to time, assets, approvals, packaging, and follow-up checks.",
   controls: ["publish window", "asset status", "packaging status", "follow-up"],
   outputKind: "launch readiness checklist",
   integrations: ["Publishing Schedule", "Packaging Lab", "Analytics"],
   selfImprovementSignal: "learns which readiness checks were skipped or rushed",
   tone: "bg-[#FFEA5A]",
   icon: CalendarClock,
  },
 {
  id: "workflow-handoff",
   title: "Workflow Handoff",
   body: "Converts the board into executable steps with owners, provenance, artifacts, and Brain-visible notes.",
   purpose: "Convert the board into executable steps with owners, provenance, artifacts, and Brain-visible notes.",
   controls: ["target tool", "artifact id", "handoff note", "status"],
   outputKind: "workflow chain seed",
   integrations: ["Workflow Chain Builder", "Brain signal", "GenerationRecord"],
   selfImprovementSignal: "checks whether every project action has a receiving tool",
   tone: "bg-[#CCFF00]",
  icon: CheckSquare,
  },
 ],
 prototype: {
  toolId: "project-command-kanban",
  title: "Project Command Prototype",
  description: "Project board preview for active launches, blockers, dependencies, readiness, and handoff state.",
  lanes: [
   { id: "idea-backlog", title: "Idea Backlog", description: "Planned work not started", tone: "bg-[#00F0FF]" },
   { id: "in-progress", title: "In Progress", description: "Owned work currently moving", tone: "bg-[#CCFF00]" },
   { id: "blocked", title: "Blocked", description: "Needs recovery action", tone: "bg-[#FF4FD8] text-white" },
   { id: "launch-ready", title: "Launch Ready", description: "Ready for publish checks", tone: "bg-[#FFEA5A]" },
   { id: "published", title: "Published", description: "Live and ready for review", tone: "bg-[#111] text-white" },
  ],
  cards: [
   {
    id: "sponsor-launch-sprint",
    laneId: "idea-backlog",
    title: "Sponsor launch sprint",
    summary: "Plan script, packaging, editor handoff, sponsor review, and publish checklist.",
    owner: "CW",
    deadline: "Friday",
    dependency: "Sponsor talking points and approved CTA",
    status: "queued",
    priority: "urgent",
    chips: ["sponsor", "launch checklist", "owner needed"],
    controls: ["owner", "priority", "next action"],
    output: "project state card",
    integrations: ["Workflow Chain", "Vault"],
    handoffTarget: "Launch steps",
   },
   {
    id: "analytics-map-module",
    laneId: "in-progress",
    title: "Geographic map visual",
    summary: "Add the map visualization task into data visuals with canonical metric coverage.",
    owner: "Analytics",
    deadline: "Next pass",
    dependency: "Traffic and geography sync fields",
    status: "active",
    priority: "high",
    chips: ["analytics", "data visuals"],
    controls: ["dependency", "handoff owner"],
    output: "milestone map",
    integrations: ["Cinematic Analytics", "Performance Hub"],
    handoffTarget: "Cinematic Analytics Lab",
   },
   {
    id: "vault-render-blocker",
    laneId: "blocked",
    title: "Vault render save path",
    summary: "Video editor must save SVG, MP4, JSON files and projects before promotion.",
    owner: "Editor",
    deadline: "Blocked",
    dependency: "VT_E1 export bridge",
    blocker: "Save contract and render proof not fully verified",
    status: "blocked",
    priority: "urgent",
    chips: ["VT_E1", "Vault", "export"],
    controls: ["blocker type", "recovery action"],
    output: "blocker recovery packet",
    integrations: ["Brain Command", "Workflow Chain"],
    handoffTarget: "VT_E1",
   },
   {
    id: "brain-welcome",
    laneId: "launch-ready",
    title: "Brain onboarding welcome",
    summary: "First-run Brain questions need evidence, confidence chips, and missing-data notices.",
    owner: "Brain",
    deadline: "Launch candidate",
    dependency: "Baseline sync evidence packet",
    status: "ready",
    priority: "high",
    chips: ["confidence", "first-run"],
    controls: ["readiness", "evidence"],
    output: "launch readiness checklist",
    integrations: ["Brain Command", "YouTube sync"],
    handoffTarget: "Dashboard welcome",
   },
   {
    id: "phase-one-html-pack",
    laneId: "published",
    title: "Phase 1 HTML pack",
    summary: "Standalone super-tool artifact pack is generated and available for review.",
    owner: "Docs",
    deadline: "Done",
    status: "complete",
    priority: "medium",
    chips: ["artifact", "documentation"],
    controls: ["provenance", "review"],
    output: "published artifact",
    integrations: ["Docs hub"],
    handoffTarget: "QA checklist",
   },
  ],
  controls: ["select card", "move left", "move right", "mark blocked", "mark launch ready"],
  evidence: ["owner", "deadline", "dependency", "blocker", "launch readiness"],
  handoffTargets: ["Launch steps", "Brain Command", "Publishing Schedule"],
 },
 modes: [
  { id: "single", label: "Single Launch", description: "Coordinate one high-priority upload or campaign through the finish line." },
  { id: "series", label: "Series Arc", description: "Manage a repeatable multi-episode run with recurring dependencies and deadlines." },
  { id: "recovery", label: "Blocker Recovery", description: "Use the board to clear blockers, ownership confusion, and missing deliverables." },
 ],
 metrics: [
  { label: "Owns", value: "Milestones, blockers, launch state", icon: Milestone, tone: "bg-[#00F0FF]" },
  { label: "Absorbs", value: "Scheduling + workflow shell", icon: Route, tone: "bg-[#CCFF00]" },
  { label: "Connects", value: "Studio, editor, vault, analytics", icon: CalendarClock, tone: "bg-[#FFEA5A]" },
  { label: "Boundary", value: "Not a second idea generator", icon: Boxes, tone: "bg-[#FF4FD8] text-white" },
 ],
 sisterToolIds: [
  "project-command-kanban",
  "series-and-theme-generator",
  "publishing-schedule-architect",
  "workflow-chain-builder",
  "brain-command-center",
 ],
 outputLanes: [
  { label: "Input", value: "Projects, launch goals, blockers, dependencies, deadlines" },
  { label: "Output", value: "Milestone chain, board state, launch sequence, task routing" },
  { label: "Handoff", value: "Workflow chain, publishing timing, analytics review" },
 ],
 buildPacket: ({ source, objective, notes, mode, brainContext, workflowCount }) => ({
  title: source || "Project Command Packet",
  summary: `Built ${mode.label.toLowerCase()} project command packet for ${source || "a creator project"} and converted it into a persisted launch workflow.`,
  packet: {
   ownership: "project milestones, blockers, dependencies, launch state",
   mode: mode.label,
   source: source || "Untitled project",
   objective: objective || "Ship the project with clear ownership and next actions",
   creatorNotes: notes || "No extra project notes provided.",
   boardRules: [
    "every blocker needs an owner",
    "launch readiness must be visible before publish day",
    "dependencies should be explicit before the project reaches edit",
   ],
   brainSignals: {
    strategicAdvice: brainContext?.strategicAdvice || null,
    contextBlock: brainContext?.toolContextPack?.summary || null,
   },
   deliverables: [
    "milestone board",
    "dependency queue",
    "launch window",
    "next action list",
   ],
   workflowCount,
  },
  workflowTitle: `${source || "Project"} command chain`,
  workflowGoal: "Own the project from planned work through launch readiness without losing blockers or dependencies.",
  workflowSteps: [
   {
    title: "Define milestone map",
    surface: "projects",
    toolId: "project-command-kanban",
    details: "Set the production phases and who owns them.",
   },
   {
    title: "Attach series logic",
    surface: "projects",
    toolId: "series-and-theme-generator",
    details: "Fold repeatable arc logic in if the project belongs to a series.",
   },
   {
    title: "Lock schedule",
    surface: "projects",
    toolId: "publishing-schedule-architect",
    details: "Place the launch against cadence and backlog constraints.",
   },
   {
    title: "Escalate blocked work",
    surface: "brain",
    toolId: "brain-command-center",
    details: "Emit the blocker state so the Brain can route a next-best action.",
   },
  ],
 }),
}

const ProjectCommandKanban: React.FC<InternalToolProps> = (props) => (
 <InternalSuperToolWorkbench config={config} {...props} />
)

export default ProjectCommandKanban
