import React from "react"
import { CalendarDays, GitBranchPlus, Map, Radar, Repeat2, Shapes } from "lucide-react"
import InternalSuperToolWorkbench, {
 type InternalToolProps,
 type InternalWorkbenchConfig,
} from "./supertools/InternalSuperToolWorkbench"

const config: InternalWorkbenchConfig = {
 toolId: "series-and-theme-generator",
 toolNumber: "05",
 title: "Series and Theme Generator",
 subtitle:
  "Design repeatable content arcs, sequel trees, and theme clusters that keep the channel coherent over time.",
 railTitle: "Series Planning Layer",
 railSubtitle: "Theme clustering, sequel branches, recurring formats, long-horizon channel arcs",
 railNote:
  "This family is likely embedded into Creator Canvas and Project Command at v1, but it still needs real internal logic now.",
 accentClassName: "bg-[#CCFF00]",
 heroShadowClassName: "shadow-[12px_12px_0px_0px_#CCFF00]",
 modeLabel: "Series mode",
 sourceLabel: "Theme seed",
 sourcePlaceholder: "Topic lane, franchise idea, recurring format, or niche expansion",
 objectiveLabel: "Series objective",
 objectivePlaceholder: "Increase recurrence, build binge loops, create sequel trees, or reduce idea drift",
 notesLabel: "Theme notes",
 notesPlaceholder: "Topic boundaries, audience appetite, cadence, visual motif, and sponsorship fit",
 modules: [
  {
   id: "theme-clusters",
   title: "Theme Clusters",
   body: "Groups related topics into stronger recurring lanes instead of isolated one-off uploads.",
   purpose: "Group related topics into stronger recurring lanes instead of isolated one-off uploads.",
   controls: ["topic lane", "audience need", "cluster size", "boundary"],
   outputKind: "theme cluster map",
   integrations: ["Creator Canvas", "Brain memory", "Audience Loop"],
   selfImprovementSignal: "records which clusters become repeatable series lanes",
   tone: "bg-[#CCFF00]",
   icon: Shapes,
  },
  {
   id: "series-arcs",
   title: "Series Arcs",
   body: "Defines episode order, recurring promise, audience payoff, and what changes each installment.",
   purpose: "Define episode order, recurring promise, audience payoff, and what changes each installment.",
   controls: ["arc length", "episode promise", "payoff", "format rule"],
   outputKind: "series arc brief",
   integrations: ["Project Command", "Publishing Schedule", "Brain context"],
   selfImprovementSignal: "tracks whether arc promises stay coherent across episodes",
   tone: "bg-[#FFEA5A]",
   icon: Repeat2,
  },
  {
   id: "sequel-trees",
   title: "Sequel Trees",
   body: "Builds the follow-up paths that serious creators need after a video proves demand.",
   purpose: "Build follow-up paths after a video proves demand, including deeper, broader, and contrarian branches.",
   controls: ["branch type", "demand signal", "depth", "priority"],
   outputKind: "sequel branch map",
   integrations: ["Audience Loop", "Cinematic Analytics", "Creator Canvas"],
   selfImprovementSignal: "records which sequel branch was selected and why",
   tone: "bg-[#00F0FF]",
   icon: GitBranchPlus,
  },
  {
   id: "cadence-fit",
   title: "Cadence Fit",
   body: "Checks whether the series fits the creator's capacity, backlog, publish rhythm, and audience expectation.",
   purpose: "Check whether the series fits creator capacity, backlog, publish rhythm, and audience expectation.",
   controls: ["publish rhythm", "production load", "backlog", "risk"],
   outputKind: "cadence fit score",
   integrations: ["Publishing Schedule", "Project Command", "Brain priorities"],
   selfImprovementSignal: "flags arcs that are strategically good but operationally too heavy",
   tone: "bg-[#FFEA5A]",
   icon: CalendarDays,
  },
 {
  id: "franchise-map",
   title: "Franchise Map",
   body: "Maps repeatable formats, visual motifs, sequel branches, and cross-tool handoffs into a durable channel franchise.",
   purpose: "Map repeatable formats, visual motifs, sequel branches, and cross-tool handoffs into a durable channel franchise.",
   controls: ["format family", "visual motif", "handoff tool", "success signal"],
   outputKind: "franchise operating map",
   integrations: ["Vault", "Packaging Lab", "Workflow Chain"],
   selfImprovementSignal: "stores what should remain consistent when the franchise evolves",
   tone: "bg-[#FF4FD8] text-white",
  icon: Map,
  },
 ],
 prototype: {
  toolId: "series-and-theme-generator",
  title: "Series Generator Prototype",
  description: "Early workspace for theme clusters, sequel branches, cadence fit, and franchise mapping.",
  lanes: [
   { id: "theme-clusters", title: "Theme Cluster Map", description: "Related topic lanes", tone: "bg-[#CCFF00]" },
   { id: "sequel-tree", title: "Sequel Tree", description: "Deeper, broader, contrarian branches", tone: "bg-[#00F0FF]" },
   { id: "cadence-fit", title: "Cadence Fit Panel", description: "Capacity and rhythm check", tone: "bg-[#FFEA5A]" },
   { id: "franchise-map", title: "Franchise Map", description: "Durable format system", tone: "bg-[#FF4FD8] text-white" },
  ],
  cards: [
   {
    id: "cluster-ai-tools",
    laneId: "theme-clusters",
    title: "AI tool workflow lane",
    summary: "Group tutorials around creator productivity and repeatable operating systems.",
    status: "active",
    priority: "high",
    chips: ["topic lane", "audience need"],
    controls: ["cluster size", "boundary"],
    output: "theme cluster map",
    integrations: ["Creator Canvas", "Brain memory"],
    handoffTarget: "Sequel Tree",
   },
   {
    id: "sequel-beginner-to-pro",
    laneId: "sequel-tree",
    title: "Beginner-to-pro branch",
    summary: "Sequence setup, first use, advanced workflow, and case-study episodes.",
    status: "queued",
    priority: "medium",
    chips: ["branch depth", "episode order"],
    controls: ["branch type", "priority"],
    output: "sequel branch map",
    integrations: ["Audience Loop", "Creator Canvas"],
    handoffTarget: "Project Command",
   },
   {
    id: "cadence-weekly",
    laneId: "cadence-fit",
    title: "Weekly capacity check",
    summary: "Validate whether recurring series production can survive editing and research load.",
    status: "blocked",
    priority: "high",
    blocker: "Production load estimate missing",
    chips: ["capacity", "risk"],
    controls: ["publish rhythm", "production load"],
    output: "cadence fit score",
    integrations: ["Publishing Schedule"],
    handoffTarget: "Publishing Schedule",
   },
   {
    id: "franchise-operating-map",
    laneId: "franchise-map",
    title: "Repeatable format map",
    summary: "Lock recurring promise, visual motif, packaging rules, and handoff targets.",
    status: "ready",
    priority: "high",
    chips: ["motif", "format family"],
    controls: ["success signal", "handoff tool"],
    output: "franchise operating map",
    integrations: ["Vault", "Workflow Chain"],
    handoffTarget: "Project Command",
   },
  ],
  controls: ["select theme", "branch sequel", "mark cadence risk", "mark launch ready"],
  evidence: ["audience request", "format pattern", "capacity assumption", "series boundary"],
  handoffTargets: ["Creator Canvas", "Project Command", "Publishing Schedule"],
 },
 modes: [
  { id: "weekly", label: "Weekly Arc", description: "Turn a channel lane into a durable weekly output rhythm." },
  { id: "monthly", label: "Monthly Theme", description: "Plan broader monthly clusters and sequel timing." },
  { id: "franchise", label: "Franchise Tree", description: "Expand one proven idea into a branded repeatable content branch." },
 ],
 metrics: [
  { label: "Owns", value: "Theme clusters + sequel trees", icon: Shapes, tone: "bg-[#CCFF00]" },
  { label: "Feeds", value: "Creator Canvas + Projects", icon: Repeat2, tone: "bg-[#00F0FF]" },
  { label: "Tests", value: "Audience appetite and arc depth", icon: Radar, tone: "bg-[#FF4FD8] text-white" },
  { label: "Boundary", value: "Likely embedded at v1", icon: GitBranchPlus, tone: "bg-[#FFEA5A]" },
 ],
 sisterToolIds: [
  "series-and-theme-generator",
  "creator-canvas-os",
  "project-command-kanban",
  "audience-loop-studio",
  "brain-command-center",
 ],
 outputLanes: [
  { label: "Input", value: "Topic lanes, follow-up demand, niche positioning, cadence" },
  { label: "Output", value: "Series arcs, sequel branches, recurring format rules" },
  { label: "Handoff", value: "Ideation, project sequencing, publishing rhythm" },
 ],
 buildPacket: ({ source, objective, notes, mode, brainContext, workflowCount }) => ({
  title: source || "Series Theme Packet",
  summary: `Built ${mode.label.toLowerCase()} series packet for ${source || "a theme seed"} and prepared sequel and scheduling handoffs.`,
  packet: {
   ownership: "theme clustering, sequel trees, recurring series rules",
   mode: mode.label,
   source: source || "Untitled theme seed",
   objective: objective || "Create a repeatable series system with clear viewer expectations",
   creatorNotes: notes || "No extra theme notes provided.",
   seriesRules: [
    "give each series a repeatable promise",
    "sequel branches should deepen, not merely repeat",
    "theme arcs should reduce idea drift across the channel",
   ],
   brainSignals: {
    strategicAdvice: brainContext?.strategicAdvice || null,
    contextBlock: brainContext?.toolContextPack?.summary || null,
   },
   deliverables: [
    "theme cluster",
    "sequel tree",
    "recurring format lane",
    "audience fit note",
   ],
   workflowCount,
  },
  workflowTitle: `${source || "Series"} arc chain`,
  workflowGoal: "Turn a theme seed into a repeatable creator series with explicit project and ideation follow-through.",
  workflowSteps: [
   {
    title: "Shape the core series promise",
    surface: "studio",
    toolId: "creator-canvas-os",
    details: "Define what the viewer should repeatedly expect from the series.",
   },
   {
    title: "Map the sequel tree",
    surface: "projects",
    toolId: "series-and-theme-generator",
    details: "Sequence the series arc and branch logic.",
   },
   {
    title: "Attach to project board",
    surface: "projects",
    toolId: "project-command-kanban",
    details: "Promote the series into milestones, deadlines, and asset planning.",
   },
   {
    title: "Check audience signal",
    surface: "studio",
    toolId: "audience-loop-studio",
    details: "Verify the recurring format matches what the audience keeps asking for.",
   },
  ],
 }),
}

const SeriesThemeGenerator: React.FC<InternalToolProps> = (props) => (
 <InternalSuperToolWorkbench config={config} {...props} />
)

export default SeriesThemeGenerator
