import React from "react"
import {
  Activity,
  BarChart3,
  Binary,
  CalendarDays,
  CircleDollarSign,
  Cloud,
  Database,
  FileImage,
  FileText,
  Film,
  Fingerprint,
  FlaskConical,
  Gauge,
  Globe2,
  Image,
  Layers3,
  Lightbulb,
  Magnet,
  Map,
  Mic,
  Network,
  Orbit,
  Palette,
  Podcast,
  Radar,
  Search,
  Share2,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Video,
  Volume2,
  WandSparkles,
  Youtube,
  Zap,
  type LucideIcon,
} from "lucide-react"

const VISUAL_ICON_MAP: Readonly<Record<string, LucideIcon>> = Object.freeze({
  analytics: BarChart3,
  database: Database,
  video: Video,
  image: Image,
  layers: Layers3,
  search: Search,
  target: Target,
  zap: Zap,
  cloud: Cloud,
  ideas: Lightbulb,
  headset: Podcast,
  volume: Volume2,
  mic: Mic,
  calendar: CalendarDays,
  sparkles: Sparkles,
  magnet: Magnet,
  network: Network,
  radar: Radar,
  orbit: Orbit,
  gauge: Gauge,
  activity: Activity,
  trend: TrendingUp,
  "file-text": FileText,
  "file-image": FileImage,
  film: Film,
  map: Map,
  globe: Globe2,
  palette: Palette,
  binary: Binary,
  flask: FlaskConical,
  fingerprint: Fingerprint,
  share: Share2,
  users: Users,
  youtube: Youtube,
  revenue: CircleDollarSign,
  "a-b-testing": Binary,
  collection: Layers3,
  text: FileText,
  geography: Globe2,
  traffic: Share2,
  "post-image": FileImage,
  "post-video": Film,
  "center-focus": Target,
  wand: WandSparkles,
  "!!!REVENUE": CircleDollarSign,
  "AB-TESTING": Binary,
  "!!!SUBSCRIBERS": Users,
  "!!!TRAFIC": Share2,
  "!!!TEXT": FileText,
  "!!!COLLECTION": Layers3,
  "!!!GEOGRAPHY": Globe2,
  "!!!PALETTE": Palette,
  "!!!YOUTUBE": Youtube,
  "!!!POST-IMAGE": FileImage,
  "!!!POST-VIDEO": Film,
  "center_focus_weak_70dp_1F1F1F_FILL0_wght700_GRAD0_opsz48": Target,
})

export const resolveAnalyticsVisualIcon = (iconKey: string | undefined): LucideIcon => {
  if (!iconKey) return BarChart3
  return VISUAL_ICON_MAP[iconKey] ?? BarChart3
}

export const AnalyticsVisualIcon: React.FC<{
  iconKey?: string
  size?: number
  strokeWidth?: number
  className?: string
}> = ({ iconKey, size = 58, strokeWidth = 3, className }) => {
  const Icon = resolveAnalyticsVisualIcon(iconKey)
  return <Icon size={size} strokeWidth={strokeWidth} className={className} />
}
