export interface GuideVisualEncodingDefinition {
 visualId: string
 encodings: readonly string[]
 datasetSearchTerms: readonly string[]
 provenance: string
}

export const GUIDE_VISUAL_ENCODINGS: readonly GuideVisualEncodingDefinition[] = Object.freeze([
 { visualId:"video-value-matrix", encodings:["Cell/position = relative video value across selected dimensions","Color/intensity = stronger relative performance where the module encodes it"], datasetSearchTerms:["videos","revenue"], provenance:"Built from canonical video-level performance rows; use the linked metric definitions to interpret value dimensions." },
 { visualId:"revenue-distribution", encodings:["Segment/area = share of revenue","Order = descending contribution when ranked"], datasetSearchTerms:["revenue","videos"], provenance:"Requires monetization-capable canonical analytics data; availability depends on channel permissions and revenue reporting support." },
 { visualId:"age-gender-audience", encodings:["Position/category = age and gender segment","Length/area = selected audience metric share"], datasetSearchTerms:["demographic","age","gender"], provenance:"Uses YouTube Analytics demographic dimensions where available." },
 { visualId:"watch-time-distribution", encodings:["Length/area = watch-time contribution","Order = ranked contribution"], datasetSearchTerms:["videos","watch time"], provenance:"Derived from canonical video-level watch-time rows." },
 { visualId:"subscribers-gained", encodings:["Length/position = subscriber gain","Comparison context = reach/attention of the same content or period"], datasetSearchTerms:["subscribers","videos","day"], provenance:"Uses subscriber-change metrics from canonical analytics datasets." },
 { visualId:"top-performers-trio", encodings:["Rank position = top-three ordering for selected performance criteria","Displayed KPI = reason each video ranks"], datasetSearchTerms:["videos"], provenance:"Uses canonical video rows and the active ranking criterion." },
 { visualId:"shorts-retention", encodings:["X/Y position = duration and AVP% relationship according to current module axes","Bubble area = relative reach/selected size signal","Color = selected performance encoding","Draw order = larger bubbles first so small points remain visible"], datasetSearchTerms:["videos","retention"], provenance:"Uses canonical video metrics plus duration/format metadata; the Best mode ranks by Views and Most Recent ranks by upload time." },
 { visualId:"algorithm-trigger", encodings:["Multiple indicators = selected viewer-response/discovery signals","Relative prominence = signal strength within the module"], datasetSearchTerms:["videos","traffic","retention"], provenance:"A derived diagnostic over canonical metrics; it is not a YouTube-provided 'algorithm score'." },
 { visualId:"engagement-lines", encodings:["X axis = time/order","Y axis = engagement metric value","Line identity = likes/comments/shares or selected series"], datasetSearchTerms:["day","videos"], provenance:"Uses canonical engagement metrics at the active grain." },
 { visualId:"packaging", encodings:["Exposure = impressions","Response = CTR","Outcome context = views/watch quality"], datasetSearchTerms:["impressions","videos"], provenance:"Uses impression/CTR-capable analytics reports where supported." },
 { visualId:"engagement-map", encodings:["X/Y position = selected engagement dimensions","Point = video","Distance = similarity/difference in engagement profile"], datasetSearchTerms:["videos"], provenance:"Derived from canonical video engagement metrics." },
 { visualId:"performance-trend", encodings:["X axis = date/time","Y axis = selected metric","Line/bar direction = change through time"], datasetSearchTerms:["day","channel"], provenance:"Uses canonical daily time-series datasets." },
 { visualId:"duration-sweet-spot", encodings:["X axis/group = video duration","Y/size/color = selected performance or retention outcome"], datasetSearchTerms:["videos","retention"], provenance:"Derived from canonical video metrics plus duration metadata." },
 { visualId:"audience-growth", encodings:["X axis = time","Y axis = subscriber growth/change"], datasetSearchTerms:["subscribers","day"], provenance:"Uses canonical subscriber time-series data." },
 { visualId:"golden-ratio-radar", encodings:["Angle/spoke = metric dimension","Radius = normalized strength on that dimension","Shape = multi-metric profile"], datasetSearchTerms:["videos"], provenance:"A derived normalized profile; spoke lengths are not raw units." },
 { visualId:"hook-effectiveness", encodings:["X axis = elapsed video time/early-video region","Y axis = retention ratio","Slope/drop = viewer loss through the hook"], datasetSearchTerms:["retention"], provenance:"Uses audience-retention data where elapsed-video retention reports are available." },
 { visualId:"growth-pulse", encodings:["Pulse height/position = growth metric strength","Time/order = recent progression"], datasetSearchTerms:["day","subscribers","views"], provenance:"Derived from canonical growth time series." },
 { visualId:"stacked-engagement-pulse", encodings:["X axis = time/order","Stack height = total engagement","Stack segment = likes/comments/shares contribution"], datasetSearchTerms:["day","videos"], provenance:"Derived from canonical engagement metrics." },
 { visualId:"format-comparison-donuts", encodings:["Donut arc = metric share by format","Whole circle = 100% of selected metric across compared formats"], datasetSearchTerms:["videos","format"], provenance:"Derived from canonical video rows grouped by Shorts vs long-form format." },
 { visualId:"revenue-efficiency", encodings:["Position/rank = revenue efficiency","Supporting value = total revenue/reach context"], datasetSearchTerms:["revenue","videos"], provenance:"Derived from canonical monetization and audience metrics." },
 { visualId:"channel-progress", encodings:["Bar height = period total","Line position = cumulative/overall total","Delta state = change versus comparison period when enabled","X axis = period sequence"], datasetSearchTerms:["day","channel"], provenance:"Uses canonical channel time series aggregated into the visual's active period." },
 { visualId:"traffic-source-evolution", encodings:["X axis = day/time","Band/line size = contribution from each traffic source","Color = traffic-source identity"], datasetSearchTerms:["traffic","day"], provenance:"Uses traffic-source × day analytics datasets." },
 { visualId:"keyword-treemap", encodings:["Tile area = selected aggregate metric for keyword","Tile label = recurring title keyword","Color = category/rank encoding used by module"], datasetSearchTerms:["videos"], provenance:"Keywords are derived from video titles, then aggregated over canonical video metrics." },
 { visualId:"keyword-venn", encodings:["Circle/group = ranked keyword set","Overlap = keywords shared between sets","Rank list = strongest items under selected criterion"], datasetSearchTerms:["videos"], provenance:"Derived from title keywords and ranked canonical video metrics." },
 { visualId:"upload-time-heatmap", encodings:["X/Y grid = weekday × publish-hour bucket","Cell intensity = selected historical performance metric"], datasetSearchTerms:["videos","day"], provenance:"Derived from publish timestamps joined to canonical video outcomes." },
 { visualId:"conversion-funnel", encodings:["Stage width = remaining volume at each funnel stage","Stage order = impressions → views → attention → subscriber outcome where available","Drop between stages = conversion loss"], datasetSearchTerms:["impressions","videos","subscribers"], provenance:"Combines canonical exposure, viewing, and subscriber metrics; some stages depend on report availability." },
 { visualId:"performance-gauges", encodings:["Dial/radius = normalized performance against configured scale","Gauge identity = metric dimension"], datasetSearchTerms:["videos","channel"], provenance:"A derived normalized display over canonical metrics; gauge position is not an upstream YouTube field." },
 { visualId:"lissajous-web", encodings:["Curve geometry = relationship among selected normalized metrics","Shape repetition = similarity across observations"], datasetSearchTerms:["videos"], provenance:"Experimental derived geometry over canonical metrics; validate patterns in conventional charts." },
 { visualId:"orbital", encodings:["Orbit distance = selected normalized metric","Object size = selected magnitude","Color = additional category/metric encoding"], datasetSearchTerms:["videos"], provenance:"Experimental derived spatial encoding over canonical metrics." },
 { visualId:"custom-scatter", encodings:["X position = selected X metric","Y position = selected Y metric","Bubble area = selected Size metric","Color gradient = selected Color metric","Point = video"], datasetSearchTerms:["videos"], provenance:"Uses canonical video-level rows. All four visual channels are user-configurable." },
 { visualId:"signal-matrix", encodings:["Row = recurring title keyword","Column = metric","Cell value = average metric across videos containing keyword","Cell intensity = value normalized within that metric column"], datasetSearchTerms:["videos"], provenance:"Title keywords are derived locally; metric values come from canonical video rows." },
 { visualId:"trajectory-forecaster", encodings:["Historical line = observed values","Projected line/region = forecast","X axis = time","Y axis = forecasted metric"], datasetSearchTerms:["day","videos"], provenance:"Forecasts are derived from canonical historical series and are not upstream YouTube predictions." },
 { visualId:"multi-metric-timeline", encodings:["X axis = date","Line/series = one metric","Y position = metric value or normalized scale according to module"], datasetSearchTerms:["day","channel"], provenance:"Uses canonical daily time-series datasets." },
 { visualId:"weekly-sparklines", encodings:["X axis = recent week sequence","Line height = metric value","Small multiple = metric/series"], datasetSearchTerms:["day","channel"], provenance:"Uses canonical time-series data summarized into compact weekly trends." },
 { visualId:"revenue-mosaic", encodings:["Tile area = revenue contribution","Tile = video/content unit","Color = module-specific rank/category signal"], datasetSearchTerms:["revenue","videos"], provenance:"Uses canonical video-level monetization data where available." },
 { visualId:"search-term-gravity", encodings:["Node size/gravity = search-term contribution","Node label = search query","Relative position = module-specific relationship layout"], datasetSearchTerms:["search","traffic"], provenance:"Uses YouTube Search traffic-source detail where available." },
 { visualId:"channel-big-bang-timeline", encodings:["X axis = channel history","Event marker = upload/inflection point","Y/size = selected performance magnitude"], datasetSearchTerms:["day","videos","channel"], provenance:"Combines canonical historical time series with video publish events." },
 { visualId:"video-performance-fingerprint", encodings:["Dimension = performance metric","Extent/radius = normalized strength","Overall shape = video profile"], datasetSearchTerms:["videos"], provenance:"A derived normalized profile over canonical video metrics." },
])

export const guideVisualEncodingById = (visualId: string) =>
 GUIDE_VISUAL_ENCODINGS.find((entry) => entry.visualId === visualId) ?? null
