export type GuideVisualStatus = "live" | "advanced" | "experimental"

export interface GuideAnalyticsVisualDefinition {
 id: string
 exportName: string
 title: string
 family: string
 status: GuideVisualStatus
 metricIds: readonly string[]
 dataConcepts: readonly string[]
 controls: readonly string[]
 read: string
 patterns: readonly string[]
 compareWith: readonly string[]
}

export const GUIDE_ANALYTICS_VISUALS: readonly GuideAnalyticsVisualDefinition[] = Object.freeze([
 { id:"video-value-matrix", exportName:"VideoValueMatrix", title:"Video Value Matrix", family:"video-ranking", status:"live", metricIds:["views","watchTime","revenue"], dataConcepts:["video-level canonical rows"], controls:["ranking/selection controls exposed by module"], read:"Use the matrix to compare the relative value of individual videos across more than one outcome instead of ranking by a single KPI.", patterns:["Look for videos that remain strong across multiple value dimensions.","Outliers that rank high on only one dimension deserve a deeper video-level check."], compareWith:["top-performers-trio","revenue-efficiency"] },
 { id:"revenue-distribution", exportName:"RevenueDistribution", title:"Revenue Distribution", family:"monetization", status:"live", metricIds:["revenue","adRevenue","redRevenue"], dataConcepts:["video/channel monetization"], controls:["scope and module controls"], read:"Read the distribution as concentration: identify whether earnings are broadly spread or dependent on a small set of content.", patterns:["Heavy concentration increases dependence on a few videos.","A broader earning base can indicate a healthier catalog."], compareWith:["revenue-efficiency","revenue-mosaic"] },
 { id:"age-gender-audience", exportName:"AgeGenderAudienceModule", title:"Age + Gender Audience", family:"audience", status:"live", metricIds:["views","watchTime"], dataConcepts:["demographic dimensions","age group","gender"], controls:["demographic display controls"], read:"Compare audience segments by share rather than treating demographic labels as performance scores.", patterns:["Large differences between viewer and watch-time share can reveal depth differences by segment."], compareWith:["format-comparison-donuts"] },
 { id:"watch-time-distribution", exportName:"WatchTimeDistribution", title:"Watch Time Distribution", family:"attention", status:"live", metricIds:["watchTime","views"], dataConcepts:["video-level watch time"], controls:["ranking/selection controls"], read:"Use this view to see where total channel attention is concentrated.", patterns:["A small number of videos carrying most watch time signals catalog concentration.","High views without proportional watch time can indicate shallow consumption."], compareWith:["shorts-retention","duration-sweet-spot"] },
 { id:"subscribers-gained", exportName:"SubscribersGained", title:"Subscribers Gained", family:"audience-growth", status:"live", metricIds:["subscribers","views","watchTime"], dataConcepts:["subscriber change by content/time"], controls:["scope controls"], read:"Read subscriber gains relative to the reach and attention that produced them.", patterns:["Videos with modest reach but strong subscriber gain can reveal unusually strong audience fit."], compareWith:["audience-growth","conversion-funnel"] },
 { id:"top-performers-trio", exportName:"TopPerformersTrio", title:"Top Performers Trio", family:"video-ranking", status:"live", metricIds:["views","watchTime","revenue"], dataConcepts:["top-ranked videos"], controls:["ranking controls"], read:"Use the three leaders as comparison anchors, then inspect why each wins rather than assuming one universal definition of best.", patterns:["The same video leading multiple metrics is a stronger all-around signal than a single-metric win."], compareWith:["video-value-matrix"] },
 { id:"shorts-retention", exportName:"ShortsRetention", title:"Shorts Retention", family:"retention", status:"live", metricIds:["views","averagePercentageViewed"], dataConcepts:["video duration","format","upload recency"], controls:["Best / Most Recent","Top N","All / Shorts / Long"], read:"Bubble position and size let you compare retention, duration, reach, and the selected visual encoding at once. Read larger bubbles first, then compare AVP% among videos of similar duration.", patterns:["High-view/high-AVP videos are strong pattern candidates.","Longer videos holding comparable AVP% are especially notable.","Recent outliers should be separated from established performers."], compareWith:["hook-effectiveness","duration-sweet-spot","custom-scatter"] },
 { id:"algorithm-trigger", exportName:"AlgorithmTriggerModule", title:"Algorithm Trigger", family:"discovery", status:"advanced", metricIds:["views","ctr","averagePercentageViewed"], dataConcepts:["performance signals"], controls:["module-specific signal controls"], read:"Treat this as a multi-signal diagnostic, not proof of an undocumented YouTube algorithm rule.", patterns:["Several strong viewer-response signals moving together are more useful than one isolated metric."], compareWith:["packaging","performance-trend"] },
 { id:"engagement-lines", exportName:"EngagementLinesModule", title:"Engagement Lines", family:"engagement", status:"live", metricIds:["likes","comments","shares","views"], dataConcepts:["engagement over time/content"], controls:["series controls"], read:"Compare engagement series together and normalize mentally for changes in reach.", patterns:["Diverging engagement lines can show a change in the type of viewer response."], compareWith:["stacked-engagement-pulse","engagement-map"] },
 { id:"packaging", exportName:"Packaging", title:"Packaging", family:"discovery", status:"live", metricIds:["impressions","ctr","views"], dataConcepts:["thumbnail/title exposure and response"], controls:["comparison controls"], read:"Read exposure first, click response second, and downstream viewing quality third.", patterns:["High CTR on low impressions is different from strong CTR sustained while impressions expand."], compareWith:["algorithm-trigger","performance-trend"] },
 { id:"engagement-map", exportName:"EngagementMap", title:"Engagement Map", family:"engagement", status:"advanced", metricIds:["likes","comments","shares","views"], dataConcepts:["video-level engagement"], controls:["map/selection controls"], read:"Use position and clustering to find videos with similar engagement behavior.", patterns:["Isolated points are candidates for closer creative or audience analysis."], compareWith:["engagement-lines","custom-scatter"] },
 { id:"performance-trend", exportName:"PerformanceTrend", title:"Performance Trend", family:"time-series", status:"live", metricIds:["views","watchTime","subscribers","revenue"], dataConcepts:["daily/channel time series"], controls:["metric/time-window controls"], read:"Read direction, duration, and magnitude of movement before attributing a trend to one upload.", patterns:["Sustained multi-day changes matter more than isolated daily noise."], compareWith:["growth-pulse","multi-metric-timeline"] },
 { id:"duration-sweet-spot", exportName:"DurationSweetSpot", title:"Duration Sweet Spot", family:"retention", status:"advanced", metricIds:["views","averageViewDuration","averagePercentageViewed","watchTime"], dataConcepts:["video duration"], controls:["format/selection controls"], read:"Compare duration with both consumption percentage and total attention to avoid assuming shorter or longer is automatically better.", patterns:["Look for duration bands that repeatedly produce strong reach and depth."], compareWith:["shorts-retention","hook-effectiveness"] },
 { id:"audience-growth", exportName:"AudienceGrowth", title:"Audience Growth", family:"audience-growth", status:"live", metricIds:["subscribers","views"], dataConcepts:["subscriber time series"], controls:["time-window controls"], read:"Read growth rate and persistence, then compare with publishing and reach changes.", patterns:["Step changes after specific releases can identify audience-building content."], compareWith:["subscribers-gained","growth-pulse"] },
 { id:"golden-ratio-radar", exportName:"GoldenRatioRadar", title:"Golden Ratio Radar", family:"multi-metric", status:"advanced", metricIds:["views","watchTime","averagePercentageViewed","subscribers","revenue"], dataConcepts:["normalized performance dimensions"], controls:["video/selection controls"], read:"Radar shape is for profile comparison, not raw magnitude. Compare dimensions only after understanding their normalization.", patterns:["Balanced shapes suggest broad strength; sharp spikes show specialization."], compareWith:["video-performance-fingerprint","performance-gauges"] },
 { id:"hook-effectiveness", exportName:"HookEffectiveness", title:"Hook Effectiveness", family:"retention", status:"advanced", metricIds:["audienceWatchRatio","averagePercentageViewed","views"], dataConcepts:["early retention"], controls:["video controls"], read:"Focus on the earliest retention behavior and connect drops to the opening promise, pacing, and expectation match.", patterns:["Fast early loss usually deserves hook/packaging alignment review."], compareWith:["shorts-retention","duration-sweet-spot"] },
 { id:"growth-pulse", exportName:"GrowthPulse", title:"Growth Pulse", family:"time-series", status:"advanced", metricIds:["views","subscribers","watchTime"], dataConcepts:["growth momentum"], controls:["window controls"], read:"Use the pulse as a momentum view and confirm its movement in the underlying time-series metrics.", patterns:["Multiple growth signals accelerating together are stronger than one spike."], compareWith:["performance-trend","audience-growth"] },
 { id:"stacked-engagement-pulse", exportName:"StackedEngagementPulse", title:"Stacked Engagement Pulse", family:"engagement", status:"advanced", metricIds:["likes","comments","shares"], dataConcepts:["engagement composition"], controls:["time/series controls"], read:"Read the total engagement envelope and then the contribution of each action.", patterns:["Composition changes can reveal a different audience response even when total engagement is stable."], compareWith:["engagement-lines"] },
 { id:"format-comparison-donuts", exportName:"FormatComparisonDonuts", title:"Format Comparison Donuts", family:"format", status:"live", metricIds:["views","watchTime","subscribers","revenue"], dataConcepts:["Shorts vs long-form"], controls:["metric controls"], read:"Use each donut as a share-of-total comparison for one metric; compare several donuts before judging a format.", patterns:["One format can dominate reach while another dominates watch time or revenue."], compareWith:["shorts-retention","revenue-efficiency"] },
 { id:"revenue-efficiency", exportName:"RevenueEfficiency", title:"Revenue Efficiency", family:"monetization", status:"advanced", metricIds:["revenue","views","watchTime"], dataConcepts:["monetization efficiency"], controls:["ranking/format controls"], read:"Separate total earnings from efficiency so high-volume videos do not automatically look most monetization-effective.", patterns:["Low-view/high-efficiency content can reveal valuable audience or format niches."], compareWith:["revenue-distribution","format-comparison-donuts"] },
 { id:"channel-progress", exportName:"ComboChannelProgress", title:"Channel Progress", family:"time-series", status:"live", metricIds:["views","watchTime","subscribers","revenue"], dataConcepts:["monthly totals","overall totals","delta/comparison"], controls:["metric","time window","delta/comparison when exposed"], read:"Bars communicate period totals while the line communicates cumulative progress. Read them together to separate current pace from long-term scale.", patterns:["A rising cumulative line with weakening bars means growth continues but current pace is slowing.","Delta mode is useful for spotting acceleration and deceleration."], compareWith:["performance-trend","multi-metric-timeline"] },
 { id:"traffic-source-evolution", exportName:"TrafficSourceEvolutionModule", title:"Traffic Source Evolution", family:"traffic", status:"live", metricIds:["views","watchTime"], dataConcepts:["traffic source","day"], controls:["source selection","metric/time controls"], read:"Follow how discovery-source contribution changes through time rather than reading only the current source mix.", patterns:["A transition from external/search to Browse/Suggested can mark a change in YouTube-native distribution."], compareWith:["performance-trend"] },
 { id:"keyword-treemap", exportName:"KeywordTreemapModule", title:"Keyword Treemap", family:"content-signals", status:"advanced", metricIds:["views"], dataConcepts:["title keywords","video aggregation"], controls:["metric/top-N controls"], read:"Area represents the selected keyword aggregate; use it to identify recurring title/topic language associated with performance.", patterns:["Large repeated terms are hypotheses for topic/packaging patterns, not proof that a word caused performance."], compareWith:["keyword-venn","signal-matrix"] },
 { id:"keyword-venn", exportName:"KeywordVennModule", title:"Keyword Venn", family:"content-signals", status:"advanced", metricIds:["views","averagePercentageViewed"], dataConcepts:["keyword overlap","ranked video groups"], controls:["ranking metric","selection controls"], read:"Use overlap to see which title/topic signals occur across different high-performing groups.", patterns:["Repeated overlap across independently ranked groups is more interesting than a term appearing in one list."], compareWith:["keyword-treemap","signal-matrix"] },
 { id:"upload-time-heatmap", exportName:"UploadTimeHeatmapModule", title:"Upload Time Heatmap", family:"publishing", status:"advanced", metricIds:["views","watchTime"], dataConcepts:["publish weekday","publish hour"], controls:["metric controls"], read:"Read cells as historical associations between publish timing and the selected outcome.", patterns:["Look for repeated zones rather than one bright cell with little sample support."], compareWith:["performance-trend"] },
 { id:"conversion-funnel", exportName:"ConversionFunnelModule", title:"Conversion Funnel", family:"conversion", status:"advanced", metricIds:["impressions","views","watchTime","subscribers"], dataConcepts:["viewer journey stages"], controls:["scope controls"], read:"Read from widest stage to narrowest and focus on where the largest proportional loss occurs.", patterns:["A weak click stage suggests packaging; strong clicks with weak watch depth shifts attention toward content delivery."], compareWith:["packaging","subscribers-gained"] },
 { id:"performance-gauges", exportName:"PerformanceGaugesModule", title:"Performance Gauges", family:"multi-metric", status:"advanced", metricIds:["views","watchTime","averagePercentageViewed","subscribers"], dataConcepts:["normalized performance"], controls:["selection controls"], read:"Gauges provide quick status against their configured scale; use detailed charts before diagnosing why a gauge is high or low.", patterns:["Several gauges moving together provide stronger evidence than one isolated dial."], compareWith:["golden-ratio-radar"] },
 { id:"lissajous-web", exportName:"LissajousWebModule", title:"Lissajous Web", family:"experimental", status:"experimental", metricIds:["views","watchTime","averagePercentageViewed"], dataConcepts:["multi-dimensional relationships"], controls:["metric/selection controls"], read:"Use this experimental visual for shape and relationship exploration, then verify any apparent pattern in conventional charts.", patterns:["Stable repeated shapes are more useful than decorative one-off geometry."], compareWith:["custom-scatter","golden-ratio-radar"] },
 { id:"orbital", exportName:"OrbitalModule", title:"Orbital", family:"experimental", status:"experimental", metricIds:["views","watchTime","subscribers"], dataConcepts:["multi-dimensional video/channel relationships"], controls:["metric/selection controls"], read:"Use orbital distance/size encodings to explore relative relationships, then confirm with the underlying metric views.", patterns:["Clusters and isolated objects are starting points for investigation."], compareWith:["custom-scatter"] },
 { id:"custom-scatter", exportName:"CustomScatterModule", title:"Custom Scatter", family:"exploration", status:"live", metricIds:["views","watchTime","averagePercentageViewed","revenue","likes","comments"], dataConcepts:["video-level canonical rows"], controls:["X metric","Y metric","bubble-size metric","color metric","Top N","format"], read:"X and Y define position, bubble size defines a third metric, and color defines a fourth. Change one encoding at a time so you know which relationship changed.", patterns:["Clusters reveal similar video profiles.","Large isolated bubbles are useful outliers.","Correlated diagonal patterns can reveal metric relationships but not causation."], compareWith:["shorts-retention","engagement-map","lissajous-web"] },
 { id:"signal-matrix", exportName:"SignalMatrixModule", title:"Signal Matrix", family:"content-signals", status:"live", metricIds:["views","revenue","likes","comments","averagePercentageViewed"], dataConcepts:["title keywords","videos containing keyword","average metric by keyword"], controls:["Top N keywords","click metric column to sort"], read:"Each row is a recurring title keyword; each heat cell is the average selected metric for videos containing it. Compare brightness within a metric column, not blindly across differently scaled columns.", patterns:["Keywords that stay bright across several metrics are stronger candidates for further analysis.","Require enough videos per keyword before treating a cell as a repeatable signal."], compareWith:["keyword-treemap","keyword-venn"] },
 { id:"trajectory-forecaster", exportName:"TrajectoryForecaster", title:"Trajectory Forecaster", family:"forecast", status:"advanced", metricIds:["views"], dataConcepts:["historical trajectory","projection"], controls:["forecast controls"], read:"Separate observed history from projected values and treat forecasts as scenarios rather than guaranteed outcomes.", patterns:["Forecast confidence should fall as the horizon extends or the input history becomes unstable."], compareWith:["performance-trend"] },
 { id:"multi-metric-timeline", exportName:"MultiMetricTimeline", title:"Multi-Metric Timeline", family:"time-series", status:"live", metricIds:["views","watchTime","subscribers","revenue"], dataConcepts:["daily time series"], controls:["metric/series controls"], read:"Align multiple metrics on the same chronology to see which changes lead, lag, or move together.", patterns:["A reach spike followed by subscriber or revenue movement can reveal downstream effects."], compareWith:["channel-progress","performance-trend"] },
 { id:"weekly-sparklines", exportName:"WeeklySparklines", title:"Weekly Sparklines", family:"time-series", status:"live", metricIds:["views","watchTime","subscribers","revenue"], dataConcepts:["weekly trend summaries"], controls:["metric controls"], read:"Use sparklines for rapid direction scanning, then open a larger time-series view for exact values.", patterns:["Repeated direction across several sparklines is a useful channel-level signal."], compareWith:["multi-metric-timeline"] },
 { id:"revenue-mosaic", exportName:"RevenueMosaic", title:"Revenue Mosaic", family:"monetization", status:"advanced", metricIds:["revenue","views"], dataConcepts:["video-level revenue contribution"], controls:["scope/ranking controls"], read:"Area communicates contribution to the selected revenue pool; use it to see concentration and long-tail earnings.", patterns:["A few dominant tiles indicate concentrated monetization."], compareWith:["revenue-distribution","revenue-efficiency"] },
 { id:"search-term-gravity", exportName:"SearchTermGravity", title:"Search Term Gravity", family:"traffic", status:"advanced", metricIds:["views","watchTime"], dataConcepts:["YouTube search terms"], controls:["metric/top-N controls"], read:"Treat stronger/larger search terms as higher-contribution query signals and inspect the exact query context before creating content around them.", patterns:["Repeated semantically related queries can reveal durable audience intent."], compareWith:["keyword-treemap","signal-matrix"] },
 { id:"channel-big-bang-timeline", exportName:"ChannelBigBangTimeline", title:"Channel Big Bang Timeline", family:"time-series", status:"advanced", metricIds:["views","watchTime","subscribers"], dataConcepts:["channel history","video events"], controls:["timeline controls"], read:"Use the long-range timeline to identify structural inflection points in channel history and connect them to releases or strategy changes.", patterns:["Persistent baseline changes after an event matter more than temporary spikes."], compareWith:["channel-progress","performance-trend"] },
 { id:"video-performance-fingerprint", exportName:"VideoPerformanceFingerprint", title:"Video Performance Fingerprint", family:"multi-metric", status:"advanced", metricIds:["views","watchTime","averagePercentageViewed","subscribers","revenue"], dataConcepts:["normalized video profile"], controls:["video selection"], read:"Read the fingerprint as a profile of strengths and weaknesses across normalized dimensions, not as raw metric magnitude.", patterns:["Similar fingerprints can identify repeatable content archetypes.","A distinctive high-performing fingerprint can become a comparison template."], compareWith:["golden-ratio-radar","custom-scatter"] },
])

export const guideAnalyticsVisualById = (id: string) =>
 GUIDE_ANALYTICS_VISUALS.find((visual) => visual.id === id || visual.exportName === id) ?? null
