/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useRef, useState } from "react"
import { generateCommunityPostDraft } from "../../services/brain/creatorAssets"
import { recordAssetOutcome } from "../../services/brain/assetOutcomes"
import { getPendingToolIntegrations, openToolIntegration, acceptToolIntegration, extractToolPrefill } from "../../services/brainLiveToolIntegration"
import { COMMUNITY_POST_CHANGED_EVENT, emptyCommunityPostDraft, normalizeCommunityPostDraft, readCommunityPostState, readCommunityPostVault, writeCommunityPostState, writeCommunityPostVault } from "./communityPostStore"
import type { CommunityPostController, CommunityPostDraftV1, CommunityPostMode, CommunityPostType, CreatorEngagementContext } from "./types"

export const buildChannelCommunityUrl=(context:Pick<CreatorEngagementContext,"channelId"|"channelHandle">):string|null=>{if(context.channelId)return `https://www.youtube.com/channel/${encodeURIComponent(context.channelId)}/community`;if(context.channelHandle)return `https://www.youtube.com/@${encodeURIComponent(context.channelHandle.replace(/^@/,""))}/community`;return null}
export const buildYouTubeShortUrl=(videoId:string):string|null=>{const normalized=videoId.trim();return normalized?`https://youtu.be/${encodeURIComponent(normalized)}`:null}
export const resolveCommunityPostVideoLink=(content:string,videoId:string):string=>{const url=buildYouTubeShortUrl(videoId);if(!url)return content;const resolved=content.replace(/\[\s*(?:link(?:\s+to)?|video\s+link)[^\]]*\]/gi,url).trim();if(resolved.includes(url))return resolved;return `${resolved}\n\n${url}`.trim()}
const mediaContextFor=(draft:CommunityPostDraftV1,videos:CreatorEngagementContext["videoAssets"])=>{const videoUrl=buildYouTubeShortUrl(draft.linkedVideoId);return [`Post format: ${draft.type}.`,draft.pollOptions.some(Boolean)?`Poll options: ${draft.pollOptions.filter(Boolean).join(" | ")}.`:"",draft.linkedVideoId?`Linked video: ${videos.find(video=>video.videoId===draft.linkedVideoId)?.title||draft.linkedVideoId}.`:"",videoUrl?`Required linked-video URL: ${videoUrl}. Include this exact URL in the finished post. Never use a bracketed link placeholder.`:""].filter(Boolean).join("\n")}

export const useCommunityPostController=(context:CreatorEngagementContext):CommunityPostController=>{
 const [draft,setDraft]=useState<CommunityPostDraftV1>(()=>readCommunityPostState());const [mode,setMode]=useState<CommunityPostMode>("write");const [videoSearch,setVideoSearch]=useState("");const [vault,setVault]=useState<CommunityPostDraftV1[]>(()=>readCommunityPostVault());const [isGenerating,setIsGenerating]=useState(false);const [error,setError]=useState<string|null>(null);const [clipboardStatus,setClipboardStatus]=useState<"idle"|"copied"|"error">("idle");const generatedAssetRef=useRef<{id:string;body:string}|null>(null)
 const update=(patch:Partial<CommunityPostDraftV1>)=>setDraft(current=>({...current,...patch,updatedAt:new Date().toISOString()}))
 useEffect(()=>{const timer=window.setTimeout(()=>writeCommunityPostState(draft),120);return()=>window.clearTimeout(timer)},[draft])
 useEffect(()=>{const sync=()=>setVault(readCommunityPostVault());const storage=(event:StorageEvent)=>{if(event.key?.includes("community_post")||event.key==="viewtube_post_vault")sync()};window.addEventListener(COMMUNITY_POST_CHANGED_EVENT,sync);window.addEventListener("storage",storage);return()=>{window.removeEventListener(COMMUNITY_POST_CHANGED_EVENT,sync);window.removeEventListener("storage",storage)}},[])
 useEffect(()=>{const applyImage=(payload:any)=>{if(!payload?.imageUrl)return;setMode("write");setDraft(current=>({...current,type:"image",imageUrl:String(payload.imageUrl),content:current.content.trim()?current.content:payload.prompt?`Generated concept: ${payload.prompt}`:current.content,updatedAt:new Date().toISOString()}))};const onBridge=(event:Event)=>{const detail=(event as CustomEvent<any>).detail;if(detail?.targetWidget==="community-post")applyImage(detail)};window.addEventListener("vt_dashboard_generated_image",onBridge as EventListener);try{const cached=localStorage.getItem("vt_bridge_image_community-post");if(cached)applyImage(JSON.parse(cached))}catch{}return()=>window.removeEventListener("vt_dashboard_generated_image",onBridge as EventListener)},[])
 useEffect(()=>{const destinationIds=["community-post","community-posts","audience-loop-studio"];for(const destination of destinationIds){for(const row of getPendingToolIntegrations(destination)){const prefill:any=extractToolPrefill(row.packet);openToolIntegration(row.handoff.id);acceptToolIntegration(row.handoff.id);setMode("write");setDraft(current=>{const imageUrl=String(prefill.imageUrl??prefill.url??"");const content=String(prefill.content??prefill.copy??prefill.text??prefill.summary??prefill.prompt??current.content);const pollOptions=Array.isArray(prefill.pollOptions)?[...prefill.pollOptions.map(String).slice(0,4),"","","",""] .slice(0,4):current.pollOptions;return {...current,type:imageUrl?"image":prefill.pollOptions?"poll":current.type,imageUrl:imageUrl||current.imageUrl,content,pollOptions,linkedVideoId:String(prefill.videoId??prefill.linkedVideoId??current.linkedVideoId??""),updatedAt:new Date().toISOString()}})}}},[])
 const recentTitles=context.videoAssets.slice(0,5).map(video=>video.title)
 const assetContext={channelId:context.channelId,channelName:context.channelName,recentVideoTitles:recentTitles}
 const normalizeGeneratedPollOptions=(options?:string[])=>options?[...options,"","","",""].slice(0,4):undefined
 const rememberGeneratedAsset=(assetId:string,body:string)=>{generatedAssetRef.current={id:assetId,body}}
 const recordGeneratedDecision=(kind:"accepted"|"exported")=>{const generated=generatedAssetRef.current;const current=draft.content.trim();if(!generated||!current)return;const original=generated.body.trim();if(current!==original){void recordAssetOutcome({assetId:generated.id,kind:"edited",correctedText:current,generatedText:generated.body})}if(kind==="exported"||current===original){void recordAssetOutcome({assetId:generated.id,kind})}}
 const refine=async()=>{if(!draft.content.trim())return;setIsGenerating(true);setError(null);try{const media=[draft.imageUrl,...draft.imagePollUrls].filter(Boolean);const result=await generateCommunityPostDraft({context:assetContext,instruction:`Refine this existing community post while preserving its intent and factual claims.\n\nCURRENT DRAFT:\n${draft.content}\n\nRequested style: ${draft.style}.`,postType:draft.type,mediaContext:mediaContextFor(draft,context.videoAssets),mediaAttachments:media});const refined=resolveCommunityPostVideoLink(result.body,draft.linkedVideoId);rememberGeneratedAsset(result.record.id,refined);const pollOptions=normalizeGeneratedPollOptions(result.pollOptions);update({content:refined,...(pollOptions?{pollOptions}: {})});setMode("write")}catch(cause){console.error("Community post refinement failed",cause);setError(cause instanceof Error?cause.message:"ViewTube could not refine this post. Try again.")}finally{setIsGenerating(false)}}
 const generate=async()=>{if(!draft.prompt.trim())return;setIsGenerating(true);setError(null);try{const media=[draft.imageUrl,...draft.imagePollUrls].filter(Boolean);const result=await generateCommunityPostDraft({context:assetContext,instruction:`${draft.prompt}\n\nRequested style: ${draft.style}.`,postType:draft.type,mediaContext:mediaContextFor(draft,context.videoAssets),mediaAttachments:media});const generated=resolveCommunityPostVideoLink(result.body,draft.linkedVideoId);rememberGeneratedAsset(result.record.id,generated);const pollOptions=normalizeGeneratedPollOptions(result.pollOptions);update({content:generated,prompt:"",...(pollOptions?{pollOptions}: {})});setMode("write")}catch(cause){console.error("Community post generation failed",cause);setError(cause instanceof Error?cause.message:"ViewTube could not generate this post. Try again.")}finally{setIsGenerating(false)}}
 const saveToVault=()=>{if(!draft.content.trim())return;const saved=normalizeCommunityPostDraft({...draft,id:emptyCommunityPostDraft().id,createdAt:new Date().toISOString()});const next=[saved,...vault];setVault(next);writeCommunityPostVault(next);recordGeneratedDecision("accepted")}
 const loadFromVault=(id:string)=>{const saved=vault.find(item=>item.id===id);if(saved){generatedAssetRef.current=null;setDraft(normalizeCommunityPostDraft({...saved,id:draft.id}))}};const removeFromVault=(id:string)=>{const next=vault.filter(item=>item.id!==id);setVault(next);writeCommunityPostVault(next)}
 const copyPost=async()=>{if(!draft.content.trim())return;try{await navigator.clipboard.writeText(draft.content);recordGeneratedDecision("exported");setClipboardStatus("copied");window.setTimeout(()=>setClipboardStatus("idle"),2000)}catch(cause){console.error("Community post copy failed",cause);setClipboardStatus("error");setError("ViewTube could not copy the post. Select the text and copy it manually.")}}
 const applyImageFile=(file?:File,optionIndex?:number)=>{if(!file)return;const reader=new FileReader();reader.onload=event=>{const url=String(event.target?.result||"");if(typeof optionIndex==="number")update({imagePollUrls:draft.imagePollUrls.map((item,index)=>index===optionIndex?url:item)});else update({imageUrl:url})};reader.readAsDataURL(file)}
 const filteredVideos=useMemo(()=>context.videoAssets.filter(video=>!videoSearch||video.title.toLowerCase().includes(videoSearch.toLowerCase())||video.videoId.toLowerCase().includes(videoSearch.toLowerCase())).slice(0,50),[context.videoAssets,videoSearch])
 return {mode,setMode,postType:draft.type,setPostType:(type:CommunityPostType)=>update({type}),content:draft.content,setContent:content=>update({content}),prompt:draft.prompt,setPrompt:prompt=>update({prompt}),pollOptions:draft.pollOptions,setPollOption:(index,value)=>update({pollOptions:draft.pollOptions.map((item,itemIndex)=>itemIndex===index?value:item)}),imageUrl:draft.imageUrl,setImageUrl:imageUrl=>update({imageUrl}),imagePollUrls:draft.imagePollUrls,setImagePollUrl:(index,value)=>update({imagePollUrls:draft.imagePollUrls.map((item,itemIndex)=>itemIndex===index?value:item)}),selectedVideoId:draft.linkedVideoId,setSelectedVideoId:linkedVideoId=>update({linkedVideoId}),videoSearch,setVideoSearch,style:draft.style,setStyle:style=>update({style}),isGenerating,error,clipboardStatus,vault,filteredVideos,channelCommunityUrl:buildChannelCommunityUrl(context),refine,generate,saveToVault,loadFromVault,removeFromVault,copyPost,applyImageFile}
}
