import React from 'react';
import type {EditorStore} from '../state/editorState';
import {readClipAudio,patchClipAudio} from '../state/audioClip';
import type {EditorCapabilityCategory} from '../../editorCapabilities';

const INK='#248b99',CYAN='#36E0F6',YELLOW='#FFFF61',PINK='#FA618A';
const card:React.CSSProperties={border:`2px solid ${INK}`,borderRadius:6,background:'#fff',padding:7,boxShadow:'2px 2px 0 rgba(54,224,246,.2)'};
const button:React.CSSProperties={minHeight:30,border:`2px solid ${INK}`,borderRadius:5,background:'#fff',fontSize:8,fontWeight:900,textTransform:'uppercase',padding:'4px 6px'};
const Label=({children}:{children:React.ReactNode})=><div style={{fontSize:8,fontWeight:950,textTransform:'uppercase',letterSpacing:.5,marginBottom:5}}>{children}</div>;
const Grid=({children}:{children:React.ReactNode})=><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:4}}>{children}</div>;

/** Page-specific creative workspace summary. It only mutates fields/actions already owned by the shared editor store. */
export const EditorCreativeWorkspace:React.FC<{store:EditorStore;category:EditorCapabilityCategory}>=({store,category})=>{
 const clip=store.selectedClips[0],track=clip?store.trackById(clip.trackId):undefined,a=clip&&track?.kind==='audio'?readClipAudio(clip):null;
 if(category==='media')return <section style={card}><Label>Project Media</Label><div style={{display:'grid',gap:4}}>{store.state.project.clips.slice(0,8).map(c=><button key={c.id} style={{...button,textAlign:'left',background:store.state.selection.clipIds.includes(c.id)?CYAN:'#fff'}} onClick={()=>store.dispatch({type:'selectClip',id:c.id})}><b>{String(c.id)}</b><small style={{display:'block'}}>{c.start.toFixed(1)}–{c.end.toFixed(1)}s · {store.trackById(c.trackId)?.kind??'clip'}</small></button>)}</div>{!store.state.project.clips.length&&<div style={{fontSize:9,fontWeight:800}}>No project clips yet. Import and Vault remain the source entry points.</div>}</section>;
 if(category==='text')return <section style={card}><Label>Text Inspector</Label>{clip&&('text' in clip)?<><textarea aria-label="Selected text content" value={String((clip as any).text??'')} onChange={e=>store.dispatch({type:'updateClip',id:clip.id,patch:{text:e.target.value}})} style={{width:'100%',minHeight:64,boxSizing:'border-box',border:`2px solid ${INK}`,borderRadius:5,padding:6,fontWeight:800,resize:'vertical'}}/><Grid><button style={{...button,background:CYAN}} onClick={()=>store.dispatch({type:'duplicateClip',id:clip.id})}>Duplicate</button><button style={{...button,background:PINK}} onClick={()=>store.dispatch({type:'deleteClips',ids:[clip.id]})}>Delete</button></Grid><div style={{fontSize:8,fontWeight:800,marginTop:5}}>Typography controls stay gated until their render-backed shared fields are confirmed.</div></>:<div style={{fontSize:9,fontWeight:800}}>Select a text/overlay clip to edit its live content.</div>}</section>;
 if(category==='audio')return <section style={card}><Label>Audio Mixer</Label>{store.state.project.tracks.filter(t=>t.kind==='audio').map(t=><div key={t.id} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:4,marginBottom:4}}><button style={{...button,textAlign:'left',background:store.state.selection.trackId===t.id?CYAN:'#fff'}} onClick={()=>store.dispatch({type:'selectTrack',id:t.id})}>{t.name}</button><button style={{...button,background:t.muted?PINK:'#fff'}} onClick={()=>store.dispatch({type:'muteTrack',id:t.id})}>{t.muted?'On':'Mute'}</button><button style={button} onClick={()=>store.dispatch({type:'lockTrack',id:t.id})}>{t.locked?'Unlock':'Lock'}</button></div>)}{a&&clip&&<><Label>Selected Clip</Label><div style={{fontSize:8,fontWeight:900}}>Volume {Math.round(a.volume*100)}%</div><input type="range" min={0} max={4} step={.01} value={a.volume} onChange={e=>store.dispatch({type:'updateClip',id:clip.id,patch:patchClipAudio(clip,{volume:+e.target.value})})} style={{width:'100%'}}/><div style={{fontSize:8,fontWeight:900}}>Rate {a.playbackRate.toFixed(2)}×</div><input type="range" min={.1} max={4} step={.05} value={a.playbackRate} onChange={e=>store.dispatch({type:'updateClip',id:clip.id,patch:patchClipAudio(clip,{playbackRate:+e.target.value})})} style={{width:'100%'}}/></>}</section>;
 if(category==='transitions')return <section style={card}><Label>Seam Editor</Label>{(store.state.project.transitions??[]).map((t,i)=>{const id=String((t as any).id??`${t.leftClipId}-${t.rightClipId}-${i}`);return <button key={id} style={{...button,width:'100%',textAlign:'left',marginBottom:4,background:store.state.selection.transitionId===id?CYAN:'#fff'}} onClick={()=>store.dispatch({type:'selectTransition',id})}><b>{String((t as any).presentation??'Transition')}</b><small style={{display:'block'}}>{t.leftClipId} → {t.rightClipId} · {(t.durationSec??0).toFixed(2)}s</small></button>})}{!(store.state.project.transitions??[]).length&&<div style={{fontSize:9,fontWeight:800}}>Select two clips and choose a transition presentation to create a seam.</div>}</section>;
 if(category==='effects')return <section style={card}><Label>Effects Stack</Label><Grid>{['Color','Blur','Motion Blur','Mask'].map(x=><div key={x} style={{...button,opacity:.55,background:YELLOW}}>{x}<small style={{display:'block'}}>contract gated</small></div>)}</Grid><div style={{fontSize:8,fontWeight:800,marginTop:5}}>The stack is represented without writing unsupported effect values into the project.</div></section>;
 return null;
};
