import React from'react';
import type{EditorStore}from'../state/editorState';
import{readClipVisualTransform}from'../state/editorState';
import{readClipAudio,patchClipAudio}from'../state/audioClip';
import{capabilitiesForCategory,type EditorCapabilityCategory}from'../../editorCapabilities';
import{VT_E1_TRANSITION_CATALOG}from'../../../../shared/vtE1TransitionCatalog.js';

const INK='#248b99',CYAN='#36E0F6',YELLOW='#FFFF61',PINK='#FA618A';
const box:React.CSSProperties={border:`2px solid ${INK}`,borderRadius:6,background:'#fff',padding:6,boxShadow:'2px 2px 0 rgba(54,224,246,.2)'};
const btn:React.CSSProperties={minHeight:28,border:`2px solid ${INK}`,borderRadius:5,background:'#fff',fontSize:8,fontWeight:900,textTransform:'uppercase',padding:'4px 6px'};
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:4};
const Label=({children}:{children:React.ReactNode})=><div style={{fontSize:8,fontWeight:950,textTransform:'uppercase',letterSpacing:.5,marginBottom:5}}>{children}</div>;
const statusBg={active:CYAN,available:YELLOW,planned:'#eee'} as const;
const State=({children}:{children:React.ReactNode})=><div style={{fontSize:8,fontWeight:800,lineHeight:1.3}}>{children}</div>;

/** Compact user-facing subtoolboxes for each editor page; actions use the shared store only. */
export const EditorControlManifest:React.FC<{store:EditorStore;category:EditorCapabilityCategory}>=({store,category})=>{const clip=store.selectedClips[0],v=clip?readClipVisualTransform(clip):null,track=clip?store.trackById(clip.trackId):undefined,a=clip&&track?.kind==='audio'?readClipAudio(clip):null,caps=capabilitiesForCategory(category);return <div aria-label={`${category} controls`} style={{display:'grid',gap:5}}>
 <section style={box}><Label>Functions</Label><div style={grid}>{caps.map(c=><div key={c.id} title={`${c.label} · ${c.status}`} style={{...btn,background:statusBg[c.status],opacity:c.status==='planned'?.55:1}}>{c.label}<small style={{display:'block',fontSize:6}}>{c.status}</small></div>)}</div></section>
 {category==='edit'&&<section style={box}><Label>Transform + Timing</Label>{clip&&v?<><b style={{fontSize:9}}>{String(clip.id)}</b><div style={{...grid,marginTop:5}}><div style={btn}>X <b>{Math.round(v.x)}</b></div><div style={btn}>Y <b>{Math.round(v.y)}</b></div><div style={btn}>Scale <b>{v.scaleX.toFixed(2)}</b></div><div style={btn}>Rotate <b>{Math.round(v.rotation)}°</b></div><button style={{...btn,background:CYAN}} onClick={()=>store.dispatch({type:'splitClipAtPlayhead',id:clip.id})}>Split</button><button style={btn} onClick={()=>store.dispatch({type:'duplicateClip',id:clip.id})}>Duplicate</button><button style={{...btn,background:PINK}} onClick={()=>store.dispatch({type:'deleteClips',ids:[clip.id]})}>Delete</button><button style={btn} onClick={()=>store.dispatch({type:'resetClipTransform',id:clip.id})}>Reset</button></div></>:<State>Select a clip to expose transform, crop and timing controls.</State>}</section>}
 {category==='media'&&<><section style={box}><Label>Media Sources</Label><div style={grid}><div style={{...btn,background:YELLOW}}>Import<br/><small>available</small></div><div style={{...btn,background:YELLOW}}>Vault<br/><small>available</small></div><div style={{...btn,opacity:.55}}>Record<br/><small>planned</small></div></div></section><section style={box}><Label>Timeline Media</Label><b style={{fontSize:18}}>{store.state.project.clips.length}</b><State>clips represented in the shared project</State></section></>}
 {category==='text'&&<section style={box}><Label>Text Composition</Label><div style={grid}><button style={{...btn,background:CYAN}} onClick={()=>store.dispatch({type:'openPanel',id:'text'})}>Add Text</button><div style={{...btn,opacity:.55}}>Typography<br/><small>planned</small></div><div style={{...btn,opacity:.55}}>Alignment<br/><small>planned</small></div><div style={{...btn,opacity:.55}}>Animation<br/><small>planned</small></div></div></section>}
 {category==='audio'&&<><section style={box}><Label>Audio Tracks</Label>{store.state.project.tracks.filter(t=>t.kind==='audio').map(t=><button key={t.id} style={{...btn,width:'100%',marginBottom:4,background:t.muted?PINK:'#fff'}} onClick={()=>store.dispatch({type:'muteTrack',id:t.id})}>{t.name} · {t.muted?'Unmute':'Mute'}</button>)}</section><section style={box}><Label>Clip Audio</Label>{a&&clip?<><State>Volume {Math.round(a.volume*100)}%</State><input aria-label="Manifest volume" type="range" min={0} max={4} step={.01} value={a.volume} onChange={e=>store.dispatch({type:'updateClip',id:clip.id,patch:patchClipAudio(clip,{volume:+e.target.value})})} style={{width:'100%'}}/><State>Playback {a.playbackRate.toFixed(2)}×</State><input aria-label="Manifest playback rate" type="range" min={.1} max={4} step={.05} value={a.playbackRate} onChange={e=>store.dispatch({type:'updateClip',id:clip.id,patch:patchClipAudio(clip,{playbackRate:+e.target.value})})} style={{width:'100%'}}/></>:<State>Select an audio clip for volume and playback-rate controls.</State>}</section></>}
 {category==='transitions'&&<section style={box}><Label>Transition Browser</Label><div style={grid}>{VT_E1_TRANSITION_CATALOG.map(definition=><button key={definition.id} style={btn} onClick={()=>store.dispatch({type:'openPanel',id:'transitions'})}>{definition.label}</button>)}</div><State>{(store.state.project.transitions??[]).length} transitions · select two clips to add at their seam.</State></section>}
 {category==='effects'&&<section style={box}><Label>Effects Rack</Label><div style={grid}><div style={{...btn,opacity:.55}}>Color<br/><small>planned</small></div><div style={{...btn,opacity:.55}}>Blur<br/><small>planned</small></div><div style={{...btn,opacity:.55}}>Motion Blur<br/><small>planned</small></div><div style={{...btn,opacity:.55}}>Mask<br/><small>planned</small></div></div><State>No fake effect values are written until the shared effect contract exists.</State></section>}
 {category==='templates'&&<section style={box}><Label>Template Library</Label><div style={{...btn,background:CYAN}}>Composition Templates</div><State>The live template browser remains the canonical template control surface.</State></section>}
 {category==='export'&&<section style={box}><Label>Project Output</Label><b style={{fontSize:16}}>{store.state.project.durationSec.toFixed(1)}s</b><State>{store.state.project.clips.length} clips · render remains capability-gated by hosted renderer readiness.</State></section>}
 {category==='settings'&&<section style={box}><Label>Editor Systems</Label><div style={grid}>{['Timeline','Preview','Performance','Diagnostics'].map(x=><div key={x} style={{...btn,background:YELLOW}}>{x}<small style={{display:'block'}}>available</small></div>)}</div></section>}
 </div>};
